### ISSUE TITLE
Dataset Designer Partial Class Files Reformatted on Visual Edits

### ISSUE THREAD

**Issue by AssisiSoft** [dotnet/winforms#10275]
### Environment

.NET 8 Visual Studio Dataset Designer

### .NET version

8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes, back before VS 2017 I think.

### Issue description

User code in partial class files for Datasets gets reformatted when a visual edit is made using the Dataset designer. Partial class files are not designer files and so should not be getting reformatted.

### Steps to reproduce

Create a Dataset using the Dataset Designer.
Add a DataTable.
Create a partial class file for the dataset.
Format some code in the partial class.
Make a visual change to the DataTable.
Source in partial class will be reformatted.

**Comment by elachlan** [comment]
@Olina-Zhang do we have a designer issue for this?

**Comment by Olina-Zhang** [comment]
We haven't designer issue about DataSet designer. As I known, DataSet designer is not owned by Winforms, is it owned by ProTools team? @merriemcgaw could you please confirm it?
@AssisiSoft Can you provide a specific sample to display the format some code is reformatted? I asked it because I tried it in VS 2017 with .Net framework application, it has same behavior. I added some test code ` int a; int b;` and format it, that code will be reformatted after did some modify in DataSet designer:

![dataSet_Format](https://github.com/dotnet/winforms/assets/26474449/d747d7c6-c111-47e8-8362-ef53f1e01de5)

**Comment by AssisiSoft** [comment]
Olina, Yes, that is a good example.  
I think it was versions before 2017.4 (is that versikon15.4) that did not reformat partial class code.  I'm not exactly sure, but try 15.3 or before if possible.
Rich

**Comment by merriemcgaw** [comment]
@Olina-Zhang that is correct. We don't own the DataSet Designer and it is not hooked up to work properly with .NET 8 apps.

**Comment by Olina-Zhang** [comment]
@AssisiSoft Please file a Visual Studio feedback ticket as the guidance: https://developercommunity.visualstudio.com/VisualStudio/report?, it will go to the right team to handle it. Thanks!

**Comment by AssisiSoft** [comment]
Done.
