### ISSUE TITLE
[Tracking] Update WinForms types that use BinaryFormatter

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#10726]
ImageListStreamer
ListViewGroup
ListViewItem
OwnerDrawPropertyBag
TreeNode
ListViewItem.ListViewSubItem

Part of #6267

**Comment by merriemcgaw** [comment]
@JeremyKuhne  here is the tracking issue. Please keep updated with the types you're migrating.

**Comment by JeremyKuhne** [comment]
`ListViewItem` and `ListViewGroup` serialize `object` tags, which will have to be kept to something in our safe set of types (such as `string`). `ListViewSubItem` is part of this scenario. Due to the recursive nature of the data, converting this is going to be a bigger chunk of work. Maybe a week or two? The three of these likely should have their own task.

**Comment by JeremyKuhne** [comment]
`OwnerDrawPropertyBag` serializes `Font` and two `Color` objects. I hadn't considered `Font` yet as its got a `TypeConverter`. Thankfully `Font` is easy to serialize so this set is one I'll likely do directly with this issue.

**Comment by JeremyKuhne** [comment]
`TreeNode` also serializes arbitrary `UserData` and is recursive so it will take a bit to implement. Similar to `ListView` item types above.

**Comment by merriemcgaw** [comment]
Related? #10738

**Comment by merriemcgaw** [comment]
Also #10736

**Comment by merriemcgaw** [comment]
@lonitra / @JeremyKuhne how are we doing with these types?

**Comment by JeremyKuhne** [comment]
We've updated everything we can that doesn't have an 'object' 'Tag'.
