### ISSUE TITLE
Clickonce installer does not detect updates for some users

### ISSUE THREAD

**Issue by statler** [dotnet/winforms#10731]
### .NET version

.Net 7

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

I have near on 1000 clients using a clickonce installer for my winforms app. Since migrating from framework about 8 months ago the behaviour has been unreliable. Some users get prompted for updates, others dont. I have run a full uninstall, delete cache reinstall and it is still unpredictably failing in some cases. The deployment is across a wide range of networks, with some able to autoupdate and some not within the same network.

Are there specific domain or security settings that impact whether a clickonce app can update itself?

### Steps to reproduce

Create a .net core clickonce, deploy it to enough people over enough networks and a reasonable number of Clients aren't prompted for an update. As there is no manual API for querying, it is really hard to debug where the problem is.

**Comment by merriemcgaw** [comment]
@statler this repo does not cover ClickOnce runtime, where it appears that your issue is happening. That said, is it possible share a detailed deployment log(remove the name of the user from the path though) from the customer machine, or at least the error code?
https://learn.microsoft.com/previous-versions/visualstudio/visual-studio-2015/deployment/how-to-specify-verbose-log-files-for-clickonce-deployments?view=vs-2015&redirectedfrom=MSDN 

I can't promise anything, but if we have a little more data we may have a suggestion here. And, of you enable verbose logging across your environments, you may be able to identify specific errors that are occurring across your deployments.  Windows Defender can sometimes interfere with deployments, but it sounds like something different may be happening here. 

ClickOnce deployment runtime is actually handled by .NET Framework components which do the copying of files to the ClickOnce cache in the user's machine and sets up the shortcuts. When the user launches the app ClickOnce runtime then hands off to .NET to execute the actual application. So I'm not convinced that this wouldn't be happening with a .NET Framework app as well.

Since this repository handles neither ClickOnce nor .NET Framework I must close the issue here. I'd recommend reaching out to CSS support to see if they can help diagnose via the logs you collect if it isn't something simple for us here. 

While I am closing this issue, in this repo you always can reply to closed issues. 😉 

FYI @Tanya-Solyanik

**Comment by statler** [comment]
thankyou @merriemcgaw for your helpful response. Your information regarding the .Net Framework vs. .Net Core handover was especially enlightening, I literally have not seen this mentioned anywhere ever, and I have been working with clickonce for over a decade.

I will try and compile a detailed log and see what that tells me.
