### ISSUE TITLE
Adding Nothing to TextBox.AutoCompleteCustomSource stops app without any info

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#10904]
### .NET version

.NET 9.0.0-preview.2.24079.1

### Did it work in .NET Framework?

No, `The program '[23732] FrameworkApp.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.`

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is not a regression issue, can reproduce from 3.1 ~ 9.0.

### Issue description

The app doesn’t respond for some seconds and will end after input the text for the textBox1. However there is no error message, exception or such a thing. And the user expect an exception message, like says: Adding null/Nothing to the AutoCompleteCustomSource is invalid.

### Steps to reproduce

1. Open attached the reproduce application, then build and run
[FeedBack1949667.zip](https://github.com/dotnet/winforms/files/14320889/FeedBack1949667.zip)
2. Click the button1
3. Entering the textbox and typing any letter

**Actual Results:**
 The app doesn’t respond for some seconds and will end after input the text for the textBox1. However there is no error message, exception or such a thing for user.
![FeedBack1949667](https://github.com/dotnet/winforms/assets/38325459/89c848cc-1b02-48f8-aa83-5df61df07f1a)

**Expected Results:**
Expect an exception message, that says: Adding null/Nothing to the AutoCompleteCustomSource is invalid.

**Comment by Zheng-Li01** [comment]
Original FeedBack: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1949667.

Filed the issue to track based on @KlausLoeffelmann comments.
```
[Zheng Li [MSFT]](https://developercommunity.visualstudio.com/user/38062): Since this seems to crash the app, I would consider this to be a bug. At least we should triage this in one of our upcoming runtime meetings.
Could you please file an issue in the WinForms GitHub Repo?

Thanks, Klaus.
```

**Comment by elachlan** [comment]
`AutoCompleteStringCollection` is annotated for null-ability. If you enable it in a project it will warn you not to pass it in.
![image](https://github.com/dotnet/winforms/assets/2433737/25f32371-d8b8-4673-8a7f-6dbbc4ccfc51)

If you do pass null, then you get the following:
```
Exception thrown at 0x00007FFD2AF552C9 (shell32.dll) in WinformsControlsTest.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

I suggest we add `ArgumentNullExceptions` to the public API to stop this invalid behavior. Since it is a string collection, you should pass in an empty string and not null.

@Zheng-Li01 I also tested combobox and it suffers from the same exception.

@lonitra There is some unusual code associated with autocomplete as well.

This seems redundant now we have a list backing it. Can we just use `ToArray`?
https://github.com/dotnet/winforms/blob/2441a36314a2312e219278e0459ba0aef8a2b7f6/src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBox.cs#L724-L733

This is calling `Array.Clear` when `size` is zero. So its redundant, and since its in the constructor it is run once. I suspect the code probably should call `StringSource.RefreshList` because the code is the same, or we can remove most of the code in the constructor.
https://github.com/dotnet/winforms/blob/2441a36314a2312e219278e0459ba0aef8a2b7f6/src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs#L16-L37

**Comment by merriemcgaw** [comment]
Thanks for picking this up @elachlan ! We'll let you run with it!

**Comment by John-Qiao** [comment]
@elachlan verified this issue with latest .NET 9.0.100-preview.3.24128.12 build from main branch, after clicked the button1 and typed letters in textbox, there's no exception popup and app is still running, is that the expected result?

https://github.com/dotnet/winforms/assets/45864985/61c3139b-e5f9-4427-9351-1b84ae31a74b

**Comment by elachlan** [comment]
Yes, before you had an application crash.

**Comment by Nora-Zhou01** [comment]
Verified this issue with .NET 9 Preview 2 test pass build, it was fixed. Test result is same as above.
