### ISSUE TITLE
PrintPreviewDialog ToolStripButton's tooltip is last work item's after changing zoom's value

### ISSUE THREAD

**Issue by Eudora-Li01** [dotnet/winforms#10970]
### .NET version

.NET 9.0.100-preview.3.24128.12

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

It doesn't repro on .NET 6.0, repro from .NET 7.0 to .NET 9.0.

### Issue description

PrintPreviewDialog ToolStripButton's tooltip is last work item's after changing zoom's value

### Steps to reproduce

1. Create Winforms .NET Core project.
2. Add button, PrintDocument and PrintPreviewDialog controls.
3. Double click button and add below codes:
"printPreviewDialog.Document = myDocument;
 printPreviewDialog.ShowDialog();"
4. Run project.
5. Click button to open PrintPreviewDialog.
6. Tab through to Zoom and change zoom's value.
7. Continue to tab through all ToolStripButton's  and observe ToolStripButton's tooltip.

https://github.com/dotnet/winforms/assets/130345015/ea28374c-ba7d-4e22-8f50-371be223d5eb

## Actual: 
All ToolStripButton's 's tooltip is correct.

## Expected: 
PrintPreviewDialog ToolStripButton's tooltip is last work item's.

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team take a look and see what might be happening here?

**Comment by ricardobossan** [comment]
This issue no longer repro in .NET 9.0.100-preview.1.24101.2:

![wfd-i-3978-2](https://github.com/dotnet/winforms/assets/30190295/03a8e4bf-c036-49b6-8644-f01e24ca325f)

Related code was changed very recently, which may have solved the issue:

![image](https://github.com/dotnet/winforms/assets/30190295/8a941a86-b3b3-48f6-854c-6ffcf754d882)

**Comment by ricardobossan** [comment]
Closing the issue, as it no longer repro on latest version.

**Comment by Eudora-Li01** [comment]
Verified this issue on .NET 9.0.100-Preview.3.24163.23, this issue still reproes. It only reproes when you tab through PrintPreviewDialog ToolStripButton.

https://github.com/dotnet/winforms/assets/130345015/d5d50d96-97b8-4e36-b25d-6b90182df83a

**Comment by LeafShi1** [comment]
It seems that this problem is because after changing Zoom, the keyboardToolTip still stores the previous Selected tool "Print".

Set `_currentTool = LastFocusedTool; ` can resolve this issue, but the tooltip will not be displayed in the correct position
https://github.com/dotnet/winforms/blob/fccada2ef35a4deb69e02f4ce558e68377f1fb35/src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/KeyboardToolTipStateMachine.cs#L184

Set a condition breakpoint (toolText == "Two pages (Ctrl+2)") in 
https://github.com/dotnet/winforms/blob/fccada2ef35a4deb69e02f4ce558e68377f1fb35/src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs#L2020  can watch the wrong value of the _currentTool

@ricardobossan Hope this information can provide some help

**Comment by Philip-Wang01** [comment]
Verified it in the latest .Net 9.0 SDK build: 9.0.100-preview.4.24177.8, it was fixed: All ToolStripButton's 's tooltip is correct.

https://github.com/dotnet/winforms/assets/86937911/6c40163b-e4a6-434e-8e53-441ad2c3cf94
