### ISSUE TITLE
[Multi-monitor] App window moves and resizes when second display disconnects

### ISSUE THREAD

**Issue by slpn-lampe** [dotnet/winforms#10972]
### .NET version

$ mono --version
Mono JIT compiler version 6.12.0.200 (tarball Tue Jul 11 21:37:50 UTC 2023)

### Did it work in .NET Framework?

Not tested/verified

### Issue description

Disconnecting a second display causes a Mono app to translate and resize. It does not happen with other non-Mono applications and also not in non-Wayland environments.
The effect is not always the same. A test app in one environment resizes to different sizes (0,0) in another.

A mono trace of the occurrence:
[mono-trace.txt](https://github.com/dotnet/winforms/files/14446034/mono-trace.txt)

It is currently not quite clear whether the event is handled incorrectly by mono, the XWayland layer or any of the deskop components.

### Steps to reproduce

Reproducable with the Weston compositor in [RebeccaBlackOS](https://sourceforge.net/projects/rebeccablackos/) live desktop

* Connect second display
* Run test app
* Disconnect second display
* App moves and resizes its window

Test source code:
```
using System.Windows.Forms;
 
public class TestApp : Form
{
    static public void Main ()
    {
        Application.Run (new Form());
    }
}
```

**Comment by elachlan** [comment]
Are you using High DPI mode? The team will probably not touch this since its via wayland (linux) and that isn't a supported platform for WinForms. But if you can track down the bug to Winforms then let us know. I suggest you raise the issue in the `Wine` issue tracker instead of here (or whatever translation/emulation software being used).
