### ISSUE TITLE
FontNameEditor rendering artifact - *just* the blue box

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1106]
**Problem description:**

`FontNameEditor` font preview is showing less characters.
For example on the below screenshots:

| Font | .NET 4.7.2 | .NET Core 3.0 |
|---|---|---|
| Arial Black | ab | a |
| Forte | abc | ab |
| Lucida Handwriting | ab | a |

**Actual behavior:** 

| .NET 4.7.2 | .NET Core 3.0 |
|---|---|
| ![image](https://user-images.githubusercontent.com/4403806/59082950-a6bba500-8938-11e9-8d07-cdae09a5e24b.png) |  ![image](https://user-images.githubusercontent.com/4403806/59082924-8be93080-8938-11e9-8d98-11eea254bb1f.png) |

🤔 ink It is possible the change may related to the change of the default font in #656.

**Expected behavior:**

We show the same amount of characters as with .NET FX.

It looks like we can achieve the same render by reducing the `fontSize` in `DrawFontSample`:
```
        private static void DrawFontSample(PaintValueEventArgs e, FontFamily fontFamily, FontStyle fontStyle)
        {
            float fontSize = (float)(e.Bounds.Height / 1.2);
            using (var font = new Font(fontFamily, fontSize, fontStyle, GraphicsUnit.Pixel))
            {
                e.Graphics.DrawString("abcd", font, SystemBrushes.ActiveCaptionText, e.Bounds);
            }
        }
```

**Minimal repro:**

* Run WinformsControlsTest in .NET 4.7.2 and .NET 3
* Compare

**Comment by RussKie** [comment]
@KlausLoeffelmann / @dreddy-work  - what do you think?

**Comment by weltkante** [comment]
Seeing the screenshots I also notice the property grid row heights differ between the two versions. Does the new default font have a different size? If so thats a really unfortunate breaking change because many Form layouts will suddenly be different. Since WinForms often uses hand placed pixel based control layout this has the potential of breaking a lot of migrated forms.

**Comment by KlausLoeffelmann** [comment]
A wild guess: The font spacing in the classic framework dialog in general is different and reminds me of the old GDI+ rendering. Are we using GDI in core, and GDI+ in classic framework, so are the `UseCompatibleTextRendering` settings different at one point? I, btw, would prefer Core rendering, since it seems crisper, even if it changes layouts bounderies slightly. There will be many changes necessary due to HighDPI requirement adjustments, anyway, so I'd vote for let the breaking change happen. @merriemcgaw? @Tanya-Solyanik, what do you think?

**Comment by RussKie** [comment]
Do we want to reduce the `fontSize` value to display more characters in the bluish box?

**Comment by RussKie** [comment]
I'm assigning to get people's attention. Once questions answered, we can reassign.

**Comment by KlausLoeffelmann** [comment]
Calling them out in posts will probably suffice. :smile:

**Comment by KlausLoeffelmann** [comment]
> Do we want to reduce the fontSize value to display more characters in the bluish box?

**Comment by KlausLoeffelmann** [comment]
Oh, I just saw you meant _just_ the box. Well, that would work for me!

**Comment by RussKie** [comment]
😄 Yes, **just** the blue box.

**Comment by Tanya-Solyanik** [comment]
Could you please find out if this regression is caused by the default font change? Is the blue box the same size on both FXs? Did the sample font  size change between the FXs? 
If other sizes might be broken as well, we have to triage if the root cause PR should be reverted. You could compare blue box and gridentry box sizes using winspy

**Comment by merriemcgaw** [comment]
We're going to take a fix here. It looks like it happens both in Framework and in Core and per @RussKie the implementation looks like just a line being added, with no particular purpose.
