### ISSUE TITLE
Add Analyzers/CodeFixes to guide implementing Custom Control Properties according to WinForms best practices

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#11161]
When we author Controls, Custom Controls or User Controls, we also introduce Properties. Whenever we introduce Properties, we need to be aware, that those Properties are the Interface for all sorts of Data, which might also be available already at Design Time. The Developer of a Control therefore always should ensure to implement a property according for Best Practice to avoid unnecessary Code Generation, accidental serialization of data into resource files or serialization of nested Object graphs, which cannot correctly roundtrip.

To this end, we want to introduce Analyzers to help guide this process:

- [ ] Make sure, Properties are attributed with the `DesignerSerializationVisibilityAttribute`
- [ ] Suggest implementing either a `DefaultValue` attribute or the methods `ShouldSerialize[PropertyName]` and `Reset[Propertyname]`.
- [ ] Check, if possible, in the context, for stock type converters for the respective types, the existence of custom type converters or alternatively for custom CodeDOMSerializers.

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/winforms/pull/11515/files

**Comment by paul1956** [comment]
@KlausLoeffelmann In RC 1 and VB much of this is not working. The auto fixes add extra document comments, which case issues that VS reports or the fixer crashes. After adding the annotation manually the errors don't go away and ignoring the errors with severity none AFTER annotation does nothing. I reported this via Visual Studio feedback because none of the an available issue categories in Repo seemed correct.
