### ISSUE TITLE
Derived form of a base form fails to accept and display new controls in it

### ISSUE THREAD

**Issue by nangelgr** [dotnet/winforms#11429]
### .NET version

8.0.200

### Did it work in .NET Framework?

Yes

### Issue description

I created a simple form that will be used as a base dialog for the rest of the dialogs.
The base dialog contains a docked tablelayoutpanel control with two rows and one column. The first row of this tableloutpanel contains a new tablelayoutpanel control with one col and one row and a label in the latter
So far so good
This compiles normally and the derived dialog displays normally
The problems begin when i try to add a new tablelayoutpanel  in the second row of the tablelayoutpanel coming from the base dialog. The new control can not be added and also not showing up not even into the Document outline pane.

### Steps to reproduce

Create a form that will be used as base dialog form named D1
in D1 create a tablelayoutpanel TLP1 with 1 col and 2 rows. In the first cell of the TLP1 create a new label L1
Now create a second form named derivedD2 : D1 instead of derivedD2  : Form
The contents of the D1 showing up correctly in the D2 dialog
Now try to add a new tablelayoutpanel in the second cell (cell of col 0 and row 1)
Mine? Fails!! No new control can be added to the empty cell and also no new control shows up in the document outline pane
Bug? or my mistake?

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by Olina-Zhang** [comment]
Tested it in .NET and .NET framework, they have same behavior.
It is "By design". Referring to "Note" area in the [Doc](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-use-the-modifiers-and-generatemember-properties?view=netframeworkdesktop-4.8&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(Designer_Modifiers)%3Bk(System.Windows.Forms.TableLayoutPanel)%3Bk(VS.Properties)%3Bk(System.Windows.Forms.TableLayoutPanel)%3Bk(Designer_System.Windows.Forms.Design.FormDocumentDesigner)%3Bk(VisualSelection)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.8.1)%26rd%3Dtrue):
 _By default, the Windows Forms Designer assigns the private (Friend in Visual Basic) modifier to container controls like [Panel](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.panel). If your base [UserControl](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.usercontrol) or [Form](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form) has a container control, it will not accept new children in inherited controls and forms. The solution is to change the modifier of the base container control to protected or public._
