### ISSUE TITLE
LinkDictionary seems to really slow down ResXResourceReader

### ISSUE THREAD

**Issue by smorrell** [dotnet/winforms#1239]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:** A large resx with 40k entries compiles to resource file very slowly ~ 30 seconds

**Expected behavior:** The same .resx file converted into a .txt file compiles very fast, under a second.  Of note,, the conversion is slow.  I would expect that both actions should take about the same time.  

I think the problem is the fact that the code is using a ListDictionary which states in its code comments

 /// <devdoc>
    ///  <para> 
    ///    This is a simple implementation of IDictionary using a singly linked list. This
    ///    will be smaller and faster than a Hashtable if the number of elements is 10 or less.
    ///    This should not be used if performance is important for large numbers of elements.
    ///  </para>
    /// </devdoc>

**Minimal repro:**  
1. Create a resx file with 40k entries and then run resgen.exe myfilename.resx 
==>slow

2. Convert this file to a txt file using: resgen.exe myfilename.resx myfilename.txt 
==> slow

3. Convert the txt file to resource dll using: resgen.exe myfilename.txt
==>fast

**Comment by dreddy-work** [comment]
This is old issue but i do not think there were any changes since then in that tool. I am not sure if this repo is right place for this. @Tanya-Solyanik,  "resgen.exe" tool owned by MSBuild team?

**Comment by rainersigwald** [comment]
No, and it's part of .NET Framework SDK, which is unlikely to see major changes in the future. MSBuild owns a fork of the `resgen.exe` code, though, in our `GenerateResource` task. If this repros there, without `resgen.exe`, that bug would belong to MSBuild. But that doesn't appear to be the case; `GenerateResource` worked over a 40k-resource-string resx in 308 ms on my machine.

If you can alter your build process to avoid `resgen.exe` (perhaps by unsetting `ResGenExecuteAsTool` or setting it to `false`) you might be able to avoid the problem.

**Comment by elachlan** [comment]
@dreddy-work after re-reading the issue description. I think the issue is more to do with:
https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs

It makes use of `ListDictionary` for its collections. This seems fine when the resources don't have many items. But when they have thousands of items it would be quite slow.

I think `Dictionary<string, object> might be better. Also if `UseResXDataNodes` is set we can use `Dictionary<string,ResXDataNode>`.

**Comment by dreddy-work** [comment]
@elachlan, did you experiment with that? I was under assumption that something from resgen.exe tool is causing the perf when loading resx. I might be wrong if it was using enumerators given by ResourceReader to read/load content.

**Comment by elachlan** [comment]
@smorrell, if you can remember. Was the issue in the direct call to resgen.exe to generate the resource?

**Comment by smorrell** [comment]
I think one way the problem manifest itself was if you accidentally opened one of the ResX-Files in Visual Studio it would completely bogged down for several minutes On Nov 10, 2022, at 5:24 PM, Lachlan Ennis ***@***.***> wrote:﻿
@smorrell, if you can remember. Was the issue in the direct call to resgen.exe to generate the resource?

**Comment by elachlan** [comment]
I think the usage of `ListDictionary` seems strange here. `HybridDictionary` might have made more sense, since is designed to handle different extremes in collection sizes.

Ultimately it would probably be a good idea to replace the `ListDictionary` with `List<string, object> so at least the key is typed correctly and we avoid the performance issues of `ListDictionary`. The way it's currently consumed internally, it's iterated start to finish to populate another collection (hashtable/dictionary).

**Comment by merriemcgaw** [comment]
We appreciate that this is a performance issue, but it isn't bubbling up to the top of our team's priority list. At this point we're not sure where the problem is that @smorrell is describing. We should revaluate after the work @elachlan is doing around replacing Collections is in to see if that resolves some of the problem.
