### ISSUE TITLE
WinForm RichTextBox LinkClicked event fails to fire when control loaded with RTF containing a friendly name hyperlink

### ISSUE THREAD

**Issue by Marie-Shi** [dotnet/winforms#1520]
* .NET Core Version: .Net Core 3.0.100-preview8-013587 build from master branch
* Have you experienced this same bug with .NET Framework?: Yes

**More info:**
There is a blocked GitHub issue [33714](https://github.com/dotnet/corefx/issues/33714) when use Test2.rtf
[Test2_Doc.zip](https://github.com/dotnet/winforms/files/3440865/Test2_Doc.zip)(just add more words than Test.rtf ). Please see the following screenshot:
![image](https://user-images.githubusercontent.com/45864017/62030629-143cd100-b218-11e9-8e83-3de1dda70a64.png)

**Problem description:**

1. Open attached app in VS and run it. 
[RichTextBoxCoreApp.zip](https://github.com/dotnet/winforms/files/3440825/RichTextBoxCoreApp.zip)

2. Click the “Click here”, then observe the behavior of browser. 

**Actual behavior:** 
There  is no response after clicking the “Click here”.

**Expected behavior:**
It opens the browser and navigates to the page of Google after clicking the “Click here”.

**Comment by weltkante** [comment]
You cannot use Process.Start with URLs in .NET Core because the default of `UseShellExecute` changed to false to be consistent between platforms (it used to default to true in Desktop Framework). Since only Windows supports `UseShellExecute` (which is required for "executing" URLs) you now have to specify this explicitly. Just use an overload which allows to specify `UseShellExecute`. 

(Also note that this isn't a WinForms issue, but a CoreFX issue, and it already has been resolved as "by design". Cross platform consistency has been deemed more important than backwards compatibility. This is not new for .NET Core 3 but has been a thing in the previews versions as well.)

**Comment by merriemcgaw** [comment]
@ericstj , @karelz can you help us locate the corefx bug that @weltkante links. Can you confirm the failure in the process.start call is by design?

@Marie-Shi - you should change the test as @weltkante suggests and confirm that it works.

**Comment by Marie-Shi** [comment]
@weltkante @merriemcgaw “More info” is another scenario when RichTextBox use **Test2.rtf**(just add more words than Test.rtf in attached project), click the “Click here”, it is blocked by GitHub issue [33714](https://github.com/dotnet/corefx/issues/33714). But using Test2.rtf in .Net Framework project, click the “Click here”, it opens the browser and navigates to the page of Google. The original problem is in “Problem description”, using **Test.rtf**, there is no response after clicking the “Click here”. 
The title is consistent with the bug reproduce steps & Actual behavior.

**Comment by karelz** [comment]
`UseShellExecute` default changed as described above. If that is the root cause, all is fine and by design.
cc @wtgodbe

**Comment by wtgodbe** [comment]
I believe this is the issue: https://github.com/dotnet/corefx/issues/24704

**Comment by weltkante** [comment]
@wtgodbe  No thats about what UseShellExecute should do on Linux, though the title doesn't reflect that.

The one I had in mind had a discussion about what the right thing to do was, from the three options
* always throw an exception on Linux because UseShellExecute defaults to true but is not supported
* have different behavior of the same API between Linux and Windows
* change the behavior on Windows to be consistent on all platforms

Option 3 was decided to be the one to go with (and I agree with that because the other two options make running the same code on different platform pretty much impossible). In hindsight it would probably have been a good idea to also obsolete the API or provide an Analyzer, to avoid the ongoing confusion.

Small side note, UseShellExecute=true is not even supported among all Windows platforms.

**Comment by weltkante** [comment]
@RussKie this is not a bug, but an intentional change in behavior in corefx. Please re-read my [reply](https://github.com/dotnet/winforms/issues/1520#issuecomment-515899341) above. As the screenshot shows the event gets fired, but the code *inside* the event runs into `Process.Start(string)` having changed semantics. You need to use an overload which allows setting `UseShellExecute=true`.

**Comment by Marie-Shi** [comment]
Verified this bug with .Net core 3.0.100-rc1-014190 from release branch, WinForm RichTextBox LinkClicked event can be fired when control loaded with RTF containing a friendly name hyperlink after clicking the “Click here”.
