### ISSUE TITLE
ListView slow and max width

### ISSUE THREAD

**Issue by riov** [dotnet/winforms#1606]
ListView becomes slow when it contains many columns, even if only a few of them are displayed. Here is a sample code that illustrates the issue. When you try to scroll it, it takes a long time to repaint. Virtual mode does not help. I am not really sure why it takes so long to paint 120 cells.

```vbnet
Private ListView1 As New ListView With {.Size = New Size(300, 400)}

Private Sub Form1_Load(sender As Object, e As EventArgs) Handles Me.Load
    Const columns = 600
    Controls.Add(ListView1)

    With ListView1
        .BeginUpdate()
        .View = View.Details
        .HeaderStyle = ColumnHeaderStyle.Nonclickable

        For c = 1 To columns
            .Columns.Add(c.ToString, 50, HorizontalAlignment.Center)
        Next

        For r = 1 To 20
            Dim l As New ListViewItem(r & "1")
            For c = 2 To columns
                l.SubItems.Add(r & c)
            Next
            .Items.Add(l)
        Next
        .EndUpdate()
    End With
End Sub
```
Another issue I found is that it looks like there is a limitation of how large the width of all columns can be, i. e. in my sample code you can change the column count to 700 and observe how the last columns will not be visible.  The last ones that will be visible will not allow you to change their width.

**Comment by merriemcgaw** [comment]
@riov can you please tell us a bit more about your scenario using 700 columns in the ListView? Is this something that is a regression from .NET Framework?

**Comment by r-aghaei** [comment]
@riov 

For the columns rendering, the behavior is the same in .NET Framework. 
For the scroll/repaint I couldn't see any problem.
For the resize issue, I believe it's a limitation in the Windows message. Consider [`WM_MOUSEMOVE`](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousemove), the `lParam` parameter determines the mouse position. The low-order word specifies the x-coordinate and the high-order word specifies the y-coordinate of the cursor. Using 16 bit for x and 16 bit for y means it can not handle coordinates larger that 32767.
That's why if you create a lot of columns, for the right most columns (which their x-coordinate is larger that 32767) you cannot change the column size, the column even do not get highlighted by mouse. If you take a look at `WM_MOUSEMOVE` message using spy++, you will see negative x-coordinate for them.

**Comment by riov** [comment]
@merriemcgaw, no it is not a regression. LV with my sample code performs even worse in .NET Framework. In my case, I needed to be able to display large data sets and that is how I have discovered its slow performance.
@r-aghaei, thank you for the insight about the x and y coordinate limitation. I would never think of that.
I am attaching a gif file so that you could see how slow LV is when I try to scroll it.
![LV](https://user-images.githubusercontent.com/53327149/62897723-8b1bb300-bd5c-11e9-8461-f1e69ed46d01.gif)

**Comment by r-aghaei** [comment]
@riov Here is what I get for `ListView`:
![listview](https://user-images.githubusercontent.com/25272166/62914820-91457a00-bdc4-11e9-968a-91eaf48037e7.gif)

As a workaround for large column numbers (even 10000 columns), I tried a double-buffered `DataGridView` and it worked well. [`DoubleBuffered`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.doublebuffered?view=netframework-4.8) is a protected property of the `Control` class. You can set `true` it for `DataGridView`, by deriving from control or using reflection. Also keep in mind, if you are using a lot of columns, explicitly set their [`FillWeight`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewcolumn.fillweight?view=netframework-4.8) to small number because sum of fill weight for all columns should not exceed 65535.

In general advice against showing a lot of columns/rows in a single view.

**Comment by RussKie** [comment]
@riov it doesn't look like `ListView` is the right control for your use-case, and you should use `DataGridView` as per @r-aghaei suggestion.

> [`DoubleBuffered`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.doublebuffered?view=netframework-4.8) is a protected property of the `Control` class. You can set `true` it for `DataGridView`, by deriving from control or using reflection.

Yes, it is (sadly) inaccessible to consumers.
Another way is to create a derived contol where you'd have access to both `DoubleBuffered` property as well as to `SetStyle()` method.

**Comment by riov** [comment]
@RussKie, actually, neither `ListsView` nor `DataGridView` will be suitable for my application because of the max total column width limitation that @r-aghaei has talked about.

As @r-aghaei has suggested, I have tried `DataGridView` and it works as expected and there is no lag. It remains a mystery to me, why `ListsView` cannot show the same performance.
![comparison](https://user-images.githubusercontent.com/53327149/62954629-683edc80-bdf8-11e9-83e8-7e3e0f70b485.gif)

Anyway, I would like to suggest two new features:
- Let the user know when `ListView` cannot add any more columns. For example, `DataGridView` throws an exception: `Sum of the columns' FillWeight values cannot exceed 65535`.
- Make `DoubleBuffered` property public

**Comment by RussKie** [comment]
> Anyway, I would like to suggest two new features:

Could you please raise separate issues for each one, thank you.
Because both of these suggestions affect public API we'll need to have an assessment how these changes will affect existing consumers.

> It remains a mystery to me, why `ListsView` cannot show the same performance.

Not sure, it could be an underlying limitation of Win32 API...
A Windows Explorer struggles to scroll when one has beyond certain number of files in a folder too.
