### ISSUE TITLE
RichTextBox link handling is broken

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1644]
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

`RitchTextBox` does not react to `LinkClicked` events at all.

**Actual behavior:** 
Created two apps - .NET 4.6.1 and .NET Core side-by-side targeting msftedit.dll (not the old riched20.dll), loaded the same rtf:
![rtb-link-issue](https://user-images.githubusercontent.com/4403806/63113455-3e71eb00-bf9b-11e9-8407-69f0f47db803.gif)

**Expected behavior:**

.NET Core reacts to the events like .NET Fx did.

**Minimal repro:**

https://github.com/RussKie/Test-RichTextBox-links

**Comment by weltkante** [comment]
Move your initialization from constructor into load event then it works.

I think I'm starting to see a pattern here, with ComboBox (#1311) and ListView (#1607) not working when doing certain things in constructor initialization ;)

**Comment by weltkante** [comment]
Should be tested again once PR #1661 is in.

**Comment by Marie-Shi** [comment]
Verified this bug with .Net Core 3.0.100-preview9-014004 from release branch, this bug is fixed, please see the below screenshot:
![LinkEvent](https://user-images.githubusercontent.com/45864017/63762844-1fa61980-c8f6-11e9-850b-5e35bc537e15.PNG)
![LinkEvent1](https://user-images.githubusercontent.com/45864017/63762848-22087380-c8f6-11e9-8c01-97deed2399ab.PNG)

**Comment by RussKie** [comment]
Thank you!
