### ISSUE TITLE
Question: Implement APIs formerly provided by WindowsAPICodePack?

### ISSUE THREAD

**Issue by nikeee** [dotnet/winforms#181]
Some time ago, there was the [WindowsAPICodePack](https://stackoverflow.com/questions/24081665/windows-api-code-pack-where-is-it), which essentially vanished from the public. Most of the APIs provided for WinForms do not exist to the current day.

Is there any plan to re-implement some of these APIs? There are #146 and #57 which already did some of this work.

There are numerous packages from different people on NuGet trying to bring back some of these APIs: https://www.nuget.org/packages?q=WindowsAPICodePack

There is also a suggestion on UserVoice: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/5648009-start-developing-the-windows-api-code-pack-again

If adding these APIs to WinForms is not an option, what about providing updated versions that run on .NET Core? WinForms and WPF packages could be distributed separately.

**Comment by jnm2** [comment]
E.g.: https://github.com/dotnet/winforms/issues/146

**Comment by merriemcgaw** [comment]
Thank you for the suggestion! Bringing these APIs into WinForms is not currently on our radar for our published [roadmap](https://github.com/dotnet/winforms/blob/master/roadmap.md). I suggest that whichever APIs are most important to you to be added are filed as individual issues so that we can evaluate them one by one. I'm going to close this issue and look forward to seeing the individual issues you file.
