### ISSUE TITLE
CodeDomSerializationStore in not marked as Serializable

### ISSUE THREAD

**Issue by MrB0nd** [dotnet/winforms#1831]
* .NET Core Version: 3.0.100-preview9-014004
* Have you experienced this same bug with .NET Framework?: No

We faced a problem when porting our application to .NET Core 3.  We have a copy/paste functionality which is implemented similar to the standard copy/paste (via [IDesignerSerializationService](https://github.com/dotnet/winforms/blob/abd5a3d167ef57ee478912e97f194ff3a21d14b2/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs#L1269)). 
On copying we get the SerializationException:
'Type System.ComponentModel.Design.Serialization.CodeDomComponentSerializationService + CodeDomSerializationStore' in Assembly 'System.Windows.Forms.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.'

Сan we expect the attribute to appear in the next release?

**Comment by RussKie** [comment]
The serialisation was removed in #1425.

@Tanya-Solyanik the list of types that should still be serialisable includes `System.ComponentModel.Design.Serialization.CodeDomComponentSerializationService.CodeDomSerializationStore` (https://github.com/dotnet/winforms/issues/889#issuecomment-513040581) however it appears to have been marked as non serialisable:
https://github.com/dotnet/winforms/commit/44b5076b843a67ab8497fe73c17576ef3e4dbd99#diff-9b75c5f1a3a9a26efe5f949b35d2b0b0L231-L232

Was this intentional, or have we just missed it?

**Comment by RussKie** [comment]
This serialization mechanism has had serious maintenance and security concerns in the past. 
The Core designer will not put binary content on the clipboard, and hence the attribute was removed.

**Comment by RussKie** [comment]
Here's the list of types that are no longer serialisable in Windows Forms going forward https://github.com/dotnet/docs/issues/14175
You may also find this post useful https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization
