### ISSUE TITLE
Eliminate elevation required to init/build repo

### ISSUE THREAD

**Issue by AArnott** [dotnet/winforms#2039]
From what @russkie says over at https://github.com/AArnott/Xunit.StaFact/issues/30#issuecomment-538639542, the reason that `build-local.ps1` is required to elevate is to create a symlink. 

It's true that VS requires the .NET SDK to be installed at the machine-wide location. Installing that would require elevation if it were not already installed. But building and testing from the command line should not require a machine-installed SDK. The build-local.ps1 is a local build and thus shouldn't (by default) require elevation.

I think it's odd that the repo *requires* a local (per user or per repo?) install of the .NET SDK (if I read @russkie's comment correctly). But if it does, IMO it shouldn't be symlinked from the machine location because that requires that it actually be installed at the machine location. But even if it were sym-link'd, that does *not* require elevation. the `mklink /j` command creates directory junctions without elevation.

So: can we remove the elevation requirement?

**Comment by weltkante** [comment]
When I debugged the tests yesterday building from the command line via `build.cmd` worked for me after an initial `Restore.cmd` run, both without having to elevate. I then ran the tests from within VS, but its kinda clunky to have to run `build.cmd` from commandline when changing something. At least it didn't require closing and reopening VS.

**Comment by AArnott** [comment]
hmmmm.... mklink required elevation later today. Odd. I wonder if I was in developer mode earlier... or if directory junctions *don't* require elevation where soft links of *files* do require elevation.

**Comment by RussKie** [comment]
`build.cmd` facilitates running from a cli.
To run from VS is significantly more cumbersome:
- start a command prompt
- run `build.cmd` and wait for all downloads, builds, tests etc
- prepend `\<path>\winforms\.dotnet` to the `%PATH%`
- launch VS from this command prompt

Because we get a constant stream of updates from arcade and core-sdk, switching between commits is a royal PIA and you have to close VS and perform these steps over and over again.

This is why I created the script to automate this.
To create symlinks to restricted folders (such as C:\Program Files\dotnet) requires elevated privileges. The `build-local` script has some smarts that checks if a symlink is established and correct, it won't ask for an elevation; else it would.

**Comment by RussKie** [comment]
Use `start-vs.cmd` and `start-code.cmd`.
