### ISSUE TITLE
The CellFormatting event of datagridview cannot be fired for cells that are not headers

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#2048]
* .NET Core Version: (3.1.100-preview1-14455 from release branch)
* Have you experienced this same bug with .NET Framework?: No

**Minimal repro:**
1. Build and run the attached application.
[CellFormattingEvent.zip](https://github.com/dotnet/winforms/files/3701402/CellFormattingEvent.zip)
2. **Double click** on "D" cell, so that entire cell cannot be selected(only selected cell 's text). 
3. Then **focus on(not click)** the first cell of "A".
![ReproSteps gif](https://user-images.githubusercontent.com/49627022/66378630-70755b80-e9e6-11e9-8719-30e577768fe9.gif)

**Actual behavior:** 
The CellFormatting event of datagridview cannot be fired, and the tooltip will display .

**Expected behavior:**
The CellFormatting event of datagridview should be fired.

**Comment by RussKie** [comment]
@Amy-Li02 could you please provide product versions for System.Windows.Forms.dll in both
* C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.100-preview1-14455
* C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.100-preview1-014076

![image](https://user-images.githubusercontent.com/4403806/66380664-98bf8300-ea03-11e9-859c-0c9caed5bbf5.png)

**Comment by RussKie** [comment]
This looks like a regression introduced in https://github.com/dotnet/winforms/pull/1681
Prior to #1681 `CellFormatting` event would be raised on cell hover, however now a tooltip is shown and the event isn't raised.

@vladimir-krestov please see what we can do to restore the original behaviour and have the tooltips.

**Comment by vladimir-krestov** [comment]
Ok, I'll investigate this.

**Comment by vladimir-krestov** [comment]
I have investigated a case when added a ToolTip text for a TextBox cell (without #1681 changes):

![image](https://user-images.githubusercontent.com/49272759/66411678-cce37580-e9fc-11e9-8eb9-c336bee725c6.png)

I have got the following result:

![otF94hrOSp](https://user-images.githubusercontent.com/49272759/66412628-960e5f00-e9fe-11e9-8ba1-633f15be987e.gif)


Сonclusion:
- If a cell has a tooltip text CellFormating event is not fired
https://github.com/dotnet/winforms/blob/1934207dfd7aa570337791a67e4eeec4f6b82265/src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs#L3009-L3012
I could not find changes in this code part in history.

#1681 changes added default tooltips for all cells ("Edit" or cell Value for DataGridViewTextBoxCell for example)

@RussKie @merriemcgaw @Tanya-Solyanik could you please say what implementation we need?
At the moment everything works correctly because if a cell has a tooltip CellFormatting event is not fired in this specific case as before.
Or do we need to call CellFormatting event in this case regardless of tooltips?

**Comment by merriemcgaw** [comment]
Did this scenario call the CellFormatting event in Framework?

**Comment by Amy-Li02** [comment]
@merriemcgaw @vladimir-krestov Yes, your investigation result is right.
1. In .NET Core, added default tooltips for all cells, so CellFormatting event is not fired.
2. In .NET Framework, there is no default tooltips for all cells, so by default, CellFormatting event can be fired. However when added a ToolTip text for a TextBox cell, CellFormatting event is not fired.

Now we worried CellFormatting event will never be fired when hover a cell in core app.

**Comment by vladimir-krestov** [comment]
@merriemcgaw, @Amy-Li02 does it need to implement calling `CellFormating` event when hovering a cell by mouse regardless of tooltips?
At the moment a DataGridView cell has a tooltip always. Except when the user sets an `empty string` or `null `as a tooltip text (then `CellFormating` event is fired).

Also, if you set `dataGridView1.ShowCellToolTips = false;` then `CellFormatting` event is not fired.
![3](https://user-images.githubusercontent.com/49272759/66457807-db23a700-ea79-11e9-96e4-7f6f9779e663.gif)

**Comment by merriemcgaw** [comment]
We would not expect the CellFormatting event to fire until the user leaves the cell that is being edited. Simply hovering elsewhere doesn't end the editing of the cell and it's when the editing is done that I would expect the CellFormatting would fire. I'd argue that not triggering the event when hovering over another cell is what I'd expect. @M-Lipin just mention this when you document #1680
