### ISSUE TITLE
Consider using structs to wrap simple native typedefs

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#2069]
We've been using enums to wrap `typedef`s from Windows. For example:

``` C
typedef int BOOL;
```

We're [wrapping as](https://github.com/dotnet/winforms/blob/master/src/Common/src/Interop/Interop.BOOL.cs):

``` C#
public enum BOOL : int
{
    FALSE = 0,
    TRUE = 1
}
```

While enums are more directly aligned with `typedef`, they don't provide other advantages that C# can provide, such as implicit operators. This can be useful in the case of `BOOL`, where checking `if (b == BOOL.TRUE)` is **not** correct as anything other than `BOOL.FALSE` is true.

We mitigate this somewhat with extension methods and copious comments, but it still makes for less than ideal consumption. `if (SomeMethod().IsTrue())` isn't natural.

Using a struct with a single internal field is functionally equivalent from an interop perspective. It allows you to use operators with can make code much easier to write:

``` C#
public readonly struct BOOL
{
    public int RawValue { get; }
    public BOOL(bool b) => RawValue = b ? 1 : 0;
    public BOOL(int b) => RawValue = b;
    public bool IsTrue => RawValue != 0;
    public bool IsFalse => RawValue == 0;
    public static implicit operator bool(BOOL b) => b.IsTrue;
    public static implicit operator BOOL(bool b) => new BOOL(b);
}

[DllImport]
BOOL SomeMethod(BOOL value);

// Can now be used like
if (SomeMethod(true))

// Instead of
if (SomeMethod(BOOL.TRUE).IsTrue())
```

The downsides are:

1. It isn't technically correct, but .NET treats it the way we want
2. It isn't as easy to optimize as `enum`, but the difference is trivial
3. Core turned down the struct pattern, but doesn't have the volume of APIs WinForms does

Upsides are:

1. Natural code flow
2. Less risk of misuse

Another thing that is possible with structs that _isn't_ with enums is wrapping pointers. Notably things like `HWND`, `HBITMAP`, etc. Using structs can allow us to strongly type our APIs:

``` C#
public readonly struct HWND
{
    public IntPtr Value { get; }
    public HWND(IntPtr handle) => Value = handle;
}
```

With pointer size objects added to the mix I'd argue that using structs for `typedef` is the best pattern to be using in WinForms.

Discussed [here](https://github.com/dotnet/winforms/pull/1978#pullrequestreview-299083926).

cc: @hughbe, @zsd4yr, @russkie, @weltkante

**Comment by weltkante** [comment]
> Using a struct with a single internal field is functionally equivalent from an interop perspective.

Technically this isn't true, which was discovered after a [bugfix](https://github.com/dotnet/coreclr/issues/19474) was made, which started crashing WPF (which already uses struct wrappers). This has lead to a technical discussion in the [PR](https://github.com/dotnet/coreclr/pull/23974) which highlighted that the native calling conventions for struct returns differ depending on whether the method has an implicit this parameter.

```C#
SomeStruct(__stdcall SomeInterface::*SomeMethod)(); // struct by reference
SomeStruct(__stdcall *SomeMethod)(SomeInterface*); // struct in register
```

This means if CoreCLR were implemented correctly then struct wrappers don't work in COM interfaces, only in P/Invokes. It was not investigated at all if struct wrappers in other positions, other calling conventions, or other platforms than Windows x86/x64 would cause any incompatibles, since all those cases were out of scope as far as the WPF usage was concerned.

So while the particular scenario of struct wrappers as return values in Windows x86/x64 has ensured compatibility the assumption that struct wrappers are equivalent is based on a bug, it is unclear if it holds in other scenarios.

I'd like to point out two particular risks going forward without checking this:
* While it is common to use `BOOL` or `HRESULT` as return value there also the occasional cases where they are passed or returned as a parameter. You'd want to ensure that wrapper structs work in both positions, being usable only in return positions is very easy to forget. (Alternatively you could create an analyzer which detects and prevents such usage, but I don't know if that is worth the effort.)

* When Windows moves on to new platforms, in particular Windows ARM64 is [already being considered](https://github.com/dotnet/winforms/issues/2053#issuecomment-540269844), it is unclear whether these assumptions will still hold up.

**Comment by JeremyKuhne** [comment]
> Technically this isn't true, which was discovered after a bugfix was made

It is true from the .NET Framework perspective. As you pointed out, even though it is technically incorrect, the runtime could never change their treatment of these as it would essentially break the world. What would likely happen is that they would add additional modifiers that allow you to get structs to pass per spec. For the record I was the source of the break you mentioned as I stumbled across the fact that I couldn't wrap some COM interfaces correctly and requested the original "fix". :) (COM interfaces that returned a struct rather than an HRESULT).

> While it is common to use BOOL or HRESULT as return value there also the occasional cases where they are passed or returned as a parameter

They work fine as parameters (by ref or otherwise). I use structs in my WInterop library, which has several hundred P/Invokes.

> When Windows moves on to new platforms, in particular Windows ARM64 is already being considered, it is unclear whether these assumptions will still hold up.

It would break a ton of apps (as you've pointed out with WPF). The runtime will keep compatibility- there really is no choice.

**Comment by JeremyKuhne** [comment]
I'm going to assert that using structs would be the best choice as it would improve encapsulation and "type safety". This came up again with #2218, where we really should have a `COLORREF` with conversion methods hanging off of it. For [example](https://github.com/JeremyKuhne/WInterop/blob/db4242c9036471adbde859895a455b64ba55271e/src/WInterop.Desktop/Gdi/Native/COLORREF.cs) (I give this code freely to .NET without need for attribution, in headers or otherwise).

**Comment by weltkante** [comment]
Generally I'm ok with this, but I'd like to point out that its not been clearly answered on whether this will work for ARM64. Would be nice if this could be verified. I only could check the native side, the C/C++ ABIs seem the have the same difference of how structs are passed, I can't test if CoreCLR will generate the right assembly code for everything to work out. The workaround in CoreCLR doesn't look like it would be x86/x64 specific but it would be nice to make sure.

That said its not something to block on, if it can't be tested now I'm fine with moving it either into #2053 or a separate issue.

**Comment by RussKie** [comment]
We will be getting access to ARM64 hardware in near to medium term future, so we should be able to test the hypothesis.

**Comment by JeremyKuhne** [comment]
Another valuable thing we could get out of "structifying" type definitions is that we could guard against sign extension problems with handles.  See https://github.com/dotnet/winforms/issues/2004#issuecomment-538536982 and the bug fix with #2736.

An `OLE_HANDLE` and `HBITMAP` struct could handle conversions properly and with context.

**Comment by elachlan** [comment]
Should we close this since winforms is now moving to CsWin32?

**Comment by RussKie** [comment]
Yes, thank you.
