### ISSUE TITLE
Support injecting forms with DI

### ISSUE THREAD

**Issue by raffaeler** [dotnet/winforms#2211]
The new "Worker Service" template in VS2019 provide a very elegant way to use dependency injection even for simple console applications, by using the ASP.NET Core infrastructure.
I created a small sample that is able to use the same infrastructure to inject forms and the ability to receive DI-registered services into the forms constructor.

The problem is of course the designer pretending to deal with default constructors. The designer should be modified to support the DI and non-default constructors.

Once the designer will support DI, it would also be useful to create a new template for Winforms creating a skeleton application with all the required references and code to use DI, logging and configuration normally used in ASP.NET Core apps.

P.S. I added this requesti for WPF in Visual Studio Developer Community because designer-related features are managed there: https://developercommunity.visualstudio.com/idea/795364/modify-the-wpf-designer-to-support-dependency-inje.html

**Comment by RussKie** [comment]
> I created a small sample that is able to use the same infrastructure to inject forms and the ability to receive DI-registered services into the forms constructor.

Could you please provide more details and the sample?



> The designer should be modified to support the DI and non-default constructors.

Why does the designer need to invoke non default constructors and execute DI code in design scenarios?

**Comment by raffaeler** [comment]
Hi @RussKie here is the sample:
```
    static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main(string[] args)
        {
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            var host = CreateHostBuilder(args).Build();

            var form = (Form)host.Services.GetRequiredService(typeof(Form1));
            Application.Run(form);
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .ConfigureLogging(options =>
                {
                    options.ClearProviders();
                    options.AddDebug();
                })
                .ConfigureAppConfiguration(config =>
                {
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.Configure<Test>(hostContext.Configuration.GetSection("TestConfig"));
                    //services.AddHostedService<Client>();

                    services.AddTransient<Form1>();
                });
        }
    }
```

And this is the form:

```
public partial class Form1 : Form
{
        private readonly ILogger<Form1> _logger;
        private readonly Test _options;

        public Form1(ILogger<Form1> logger, IOptions<Test> options)
        {
            _logger = logger;
            _options = options.Value;
            InitializeComponent();
        }
}

```

From that point on:
1. instead of "new-ing" a form, I can ask the DI to provide me the appropriate Form.
2. every form can request the DI to receive any appropriate service (like a viewmodel) in the constructor

At this point the default constructor will not exist anymore and the designer historically complained about not having a default constructor.
Since you are building a new designer, it would be appropriate to modify the way the forms are created in the designer to take into account the DI factory.

> Why does the designer need to invoke non default constructors and execute DI code in design scenarios?
There are multiple possible reasons:
- provide design-time data
- inject styling
- configurations
- ...

HTH

**Comment by RussKie** [comment]
Thank you, it is helpful.

Why would you want the designer to resolve dependencies and execute arbitrary code though?

There are two independent experiences in WinForms - a design-time and a runtime experiences, and we need to be clear what experience we are trying to enhance.
* The design-time experience is all about allowing a user to create a UI; and
* The runtime experience is about running the app, executing desired functionality and delivering a user experience.

DI is all about runtime, and it doesn't fit in the design-time context. It feels inappropriate to ask the designer to execute your app (because that what it would have to do in order to resolve dependencies) in order to allow you tweak a label on a that button.

WinForms is an old tech, and it lacks a clear separation of UI (view) and logic layers, that WPF/UWP/web developers may be taking for granted. In the nutshell, the view is constrained to `InitializeComponent()` method, and it is the only thing the designer is only interested in and cares about, everything else is largely irrelevant and likely to have detrimental effects on the design-time experience.

To accommodate both experiences your example above would look something like the following:
```cs
public partial class Form1 : Form
{
        private readonly ILogger<Form1> _logger;
        private readonly Test _options;

        public Form1(ILogger<Form1> logger, IOptions<Test> options)
        {
            _logger = logger;
            _options = options.Value;
            InitializeComponent();
        }

		// required for the designer
        private Form1()
        {
            InitializeComponent();
        }
}
```

/cc: @DustinCampbell @merriemcgaw

**Comment by weltkante** [comment]
As far as I'm aware it is not a problem designing a Form/Control having no parameterless constructor. Like @Russkie mentions
> In the nutshell, the view is constrained to InitializeComponent() method, and it is the only thing the designer is only interested in and cares about

We have plenty of forms taking constructor parameters in Desktop Framework and it works fine editing them in the designer.

What does not work however is
* inheriting from a form that takes a constructor parameter and editing it in the designer
* placing controls that require constructor parameters on the designer

For both cases the designer wants to instantiate the control (or base class form) but if it requires parameters it doesn't know how to fill them. The statement on `InitializeComponent` is only valid for the element currently edited, not for elements *placed on top of the design surface*.

The requirement here is that elements placed on the design surface at design time must have a parameterless constructor. I think this is an entirely valid requirement, if you want something to be injected via DI you wouldn't place it manually on a design surface. If you place it on the design surface then its type is fixed and selected by the user and not determined by DI.

I would make the following statements about DI support
* if you want content of the designer be generated by DI you would probably be placing a placeholder, not the DI component itself
* passing DI context around can happen through the controls [Site](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.site?view=netframework-4.8) object. This would allow placeholder controls do get access to DI context when filling themselves. Furthermore the concept can be made work both at design time and runtime, since the sites are different (of course it would require implementing a design time site that understands DI, which is not trivial).

   The "control site" concept is not well known and kinda ancient, I think the concept comes from OLE/ActiveX controls and WinForms just took it over, if the framework would be redesigned it would probably be made different (WPF got rid of it, but in my opinion the WPF designer never was as great as the WinForms designer, so its unclear if the design deicsions WPF made for its designer are actually the right ones. I never have programmed design time extensions for WPF so I don't have personal experience. WinForms design time experience allows for great customizations though, some of which come through the control site concept.)

   That said I never tried fitting DI into the control site, I just think it would be possible and the right place to do so.

That leaves the question, is there anything actionable to actually *fix* - considering designing Forms with parameters seems to work for me (at least it used to on Desktop)?

**Comment by DustinCampbell** [comment]
Adding DI support to the designer would be a major undertaking. Part of the problem is that the designer doesn't _actually_ create an instance of your class. Instead, it creates an instance of the base type of your class and applies the contents of the `InitializeComponent()` method via CodeDom serialization. Consider this:

```C#
public class Form1 : System.Windows.Forms.Form
{
    public Form1()
    {
    }

    private void InitializeComponent()
    {
        this.Text = "SuperForm";
    }
}
```

The designer doesn't actually create an instance of the class, `Form1`, because it's entirely likely that `Form1` hasn't even been compiled yet. So, it creates an instance of the class, `System.Windows.Forms.Form` and the constructor of `Form1` isn't even called at all. Then, it takes the contents of `InitializeComponent()` and applies particular CodeDom statements to `System.Windows.Forms.Form` instance (in this case, a property set).

Given that, let's consider the example above:

```C#
public partial class Form1 : Form
{
        private readonly ILogger<Form1> _logger;
        private readonly Test _options;

        public Form1(ILogger<Form1> logger, IOptions<Test> options)
        {
            _logger = logger;
            _options = options.Value;
            InitializeComponent();
        }
}
```

This should already work today since the designer doesn't ever call the constructor of `Form1` (since it's not compiled), and instead calls the parameterless constructor of `Form`. However, if the desire is to have the designer construct an instance of `Form1` (forcing a compile first) and pass some default arguments (defined somewhere?) into the constructor, that will require a full re-think of how the designer works. This is more on the order of a rewrite rather than just adding support. I honestly can't see that happening.

**Comment by raffaeler** [comment]
Thank you all.
I started from this small repro, but the goal was to decouple the forms fromt the logic. With the above suggestions I think I can workaround the issues.

**Comment by RussKie** [comment]
Please let us know if you have something to showcase, it would be awesome to have real world examples of DI for WinForms.
Personally it is something I've been wanting to get into [Git Extensions project](https://github.com/gitextensions/gitextensions) for years.
