### ISSUE TITLE
Self-contained deployment always include WPF assemblies

### ISSUE THREAD

**Issue by filipnavara** [dotnet/winforms#2426]
* .NET Core Version: 3.0; 3.1
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

- Create a simple WinForms application (either through `dotnet new` or VS)
- Add Publish profile, change it from "framework dependent" to "self-contained" 

**Actual behavior:**

Published output contains large part of WPF stack (eg. PresentationCore.dll, PresentationUI.dll, PresentationFramework*.dll, etc.) which amounts to over 30 Mb (> 10 Mb compressed) of unused assemblies. The files are pulled from the "runtimepack.Microsoft.WindowsDesktop.App.Runtime.win-x86/3.0.0" NuGet package.

**Expected behavior:**

No WPF assemblies in the output.

**Minimal repro:**

[WindowsFormsApp1.zip](https://github.com/dotnet/winforms/files/3886266/WindowsFormsApp1.zip)

**Comment by weltkante** [comment]
As far as I know the compiler looks at project file properties `UseWindowsForms` and `UseWPF` and if those are not present he won't add the references.

As such I'd expect that the publish process should respect the same properties when deciding which assemblies to publish.

**Comment by filipnavara** [comment]
> As far as I know the compiler looks at project file properties `UseWindowsForms` and `UseWPF` and if those are not present he won't add the references.
> 
> As such I'd expect that the publish process should respect the same properties when deciding which assemblies to publish.

I'd expect that as well but it does not.

**Comment by weltkante** [comment]
Yes I was just trying to point out where the problem is. There already exists a way to differentiate between WPF/WinForms projects but apparently its not used consistently.

**Comment by RussKie** [comment]
@danmosemsft @ericstj can you please help directing the issue to the right team? I'm guessing this issue belongs to dotnet/runtime.

**Comment by filipnavara** [comment]
This also affects WPF apps that end up bundling parts of WinForms. /cc @vatsan-madhavan

**Comment by filipnavara** [comment]
It's been three weeks and there is still no answer where this issue belongs. Any help would be really appreciated. /cc @terrajobst @danmosemsft

**Comment by ericstj** [comment]
This is by design as the SDK deploys shared frameworks as a whole and WPF and WinForms are in the same shared framework.  You can enable trimming in order to drop the WPF assemblies if your app doesn't use them.

@filipnavara WPF actually depends on WinForms for some of its UI so even when enabling trimming a WPF app will still bring in WinForms.

Winforms could techincally be deployed without WPF, assuming WPF is never referenced.  In 3.x the way to achieve this is with publish trimming.  https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#assembly-linking

If WinForms wanted to fix this they could split their runtime into its own shared framework.  Alternatively they could ask the SDK to implement some sort of *runtime* mapping of UseWindowsForms / UseWPF, today these only represent a reference mapping.  As of today, neither of these are implemented by WinForms nor SDK, so the behavior is by-design.

**Comment by filipnavara** [comment]
@ericstj I enabled trimming. It didn't help.

**Comment by ericstj** [comment]
If you enabled trimming on a self-contained WinForms app that doesn't use WPF and WPF wasn't removed by the linker that sounds like it could be a linker bug.  You can open an issue with repro here: https://github.com/dotnet/sdk/issues.

**Comment by filipnavara** [comment]
Thanks. The repro is the same as presented here. It already has `PublishTrimmed` enabled. I will open new issue on the SDK project.
