### ISSUE TITLE
Setting ListViewGroup.HorizontalAlignment does not work once handle is created

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2554]
E.g. with the following form
![image](https://user-images.githubusercontent.com/1275900/71325761-7b219600-24e9-11ea-8b95-879f17c64404.png)

Setting `listView1.Groups[0].HeaderAlignment = HorizontalAlignment.Left;` causes no update to the alignment of the group.

However, calling 'RecreateHandle` on the `ListView` does fix this.

The fix would be make the setter of `ListViewGroup.HeaderAlignment` recreate the handle: i.e.
```cs

        /// <summary>
        ///  The alignment of the group header.
        /// </summary>
        [DefaultValue(HorizontalAlignment.Left)]
        [SRCategory(nameof(SR.CatAppearance))]
        public HorizontalAlignment HeaderAlignment
        {
            get => _headerAlignment;
            set
            {
                if (!ClientUtils.IsEnumValid(value, (int)value, (int)HorizontalAlignment.Left, (int)HorizontalAlignment.Center))
                {
                    throw new InvalidEnumArgumentException(nameof(value), (int)value, typeof(HorizontalAlignment));
                }

                if (_headerAlignment != value)
                {
                    _headerAlignment = value;
                    ListView?.RecreateHandleInternal();
                }
            }
        }
```

![Screen Recording 2019-12-22 at 06 35 pm](https://user-images.githubusercontent.com/1275900/71325794-e10e1d80-24e9-11ea-97b3-85e079776c21.gif)

**Comment by hughbe** [comment]
This also repros in .NET Framework

**Comment by weltkante** [comment]
> The fix would be make the setter of ListViewGroup.HeaderAlignment recreate the handle

I didn't inspect this scenario but recreating handles has risk of flickering (maybe not noticeable on normal machines, but low end machines and remote connections may observe it) and causing issues with focus/accessibility/etc. so this suggestion by default sounds wrong to me and should only be chosen as a last resort (with explicitely testing for above issues) if there is no Win32 API to update whatever stores this property on the native side.

**Comment by hughbe** [comment]
I did notice flickering on my Remote Desktop actually when testing the fix.

The problem according to my investigation appears to be that calling LVM_SETGROUPINFO and changing the uAlign field (https://docs.microsoft.com/en-us/windows/win32/controls/lvm-setgroupinfo) doesn’t update the group alignment.

This problem is the same for ListViewGroup.Header, which explicitly calls `RecreateHandle` which is why I adopted this approach

**Comment by weltkante** [comment]
I debugged this and something fishy is going on

> Setting listView1.Groups[0].HeaderAlignment = HorizontalAlignment.Left; causes no update to the alignment of the group.

[UpdateGroupNative](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L5570) is not checking the return value of `LVM_SETGROUPINFO`, when I'm stepping through in the debugger I'm getting `-1` for the update, according to the [doc](https://docs.microsoft.com/en-us/windows/win32/controls/lvm-setgroupinfo) this means the update was not processed.

If I manually change the group ID in the `LVGROUP` struct in the debugger (but not in the `SendMessageW` call - effectively renaming the group to a different ID) then I'm getting the old group ID as return value of the message and the control correctly updates itself showing the changed alignment. (Of course now the group has a different ID, so if I want to change the ID back to the original value I have to send another message.)

I don't have time to try other combinations of settings in the `LVGROUP` struct, but it is very strange that `LVM_SETGROUPINFO` fails unless the group ID is changed. I wonder if its purpose is underdocumented and/or its implementation has bugs.

Even if further investigation doesn't yield new insights it may be a better workaround to rename the group twice instead of recreating the whole ListView.

**Comment by hughbe** [comment]
Noting current implementation:
```cs
internal void UpdateGroupNative(ListViewGroup group)
{
    Debug.Assert(IsHandleCreated, "UpdateGroupNative precondition: list-view handle must be created");

    var lvgroup = new LVGROUP();
    try
    {
        lvgroup = GetLVGROUP(group);
        int retval = (int)User32.SendMessageW(this, (User32.WindowMessage)LVM.SETGROUPINFO, (IntPtr)group.ID, ref lvgroup);
    }
    finally
    {
        DestroyLVGROUP(lvgroup);
    }

    // The comctl32 ListView does not correctly invalidate itself, so we need to invalidate the entire ListView
    Invalidate();
}
```

I shall experiment :)

**Comment by hughbe** [comment]
http://users.skynet.be/oleole/Listview_grouping_feature.htm

> Changing the caption (or alignment) of a group follows the same philosophy except that you have to use a workaround because of a bug in the LVM_SETGROUPINFO message / ListView_SetGroupInfo() macro. The bug (unless Microsoft defines it as a feature) prevents you from changing the caption if you don't change the identifier of the group.

> Hopefully there is a workaround that requires two steps. First you change the caption and the identifier and then you change back the identifier to its original value (see Listing 5).

Maybe we could avoid recreating the handle in HeaderText setting too!

**Comment by weltkante** [comment]
Thanks for the link, I've thought some more about what I observe and I think I understand why this happens. Setting `LVGROUP.mask` to `LVGF_GROUPID` when calling `LVM_SETGROUPINFO` probably asks to rename the group. I think if the group ID to which you want to rename it already exists this fails, removing the `LVGF_GROUPID` flag when doing updates should do the trick:

```csharp
lvgroup = GetLVGROUP(group);
lvgroup.mask &= ~ComCtl32.LVGF.GROUPID;
int retval = (int)User32.SendMessageW(this, (User32.WindowMessage)LVM.SETGROUPINFO, (IntPtr)group.ID, ref lvgroup);
```

**Comment by RussKie** [comment]
You're both awesome! 💯
