### ISSUE TITLE
VB core project template missing Settings, Resourses, Application.myapp and ApplicationInfo

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#2609]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
 Microsoft.WindowsDesktop.App 5.0.0-alpha.1.19625.2
* Have you experienced this same bug with .NET Framework?: No
**Problem description:**
A default VB project template should also include Resources, Settings, AssemblyInfo and allow for the setting of the same values that a Framework project allows (SingleInstance might be an issue for now). Many of the values that were in My.Application.Info in Framework are now set elsewhere in VS Core Projects or are disabled (Application/AssemblyInfo).
**Actual behavior:**
The only thing included in a core project is Form1
**Expected behavior:**
![image](https://user-images.githubusercontent.com/12789369/71639992-e597ac00-2c36-11ea-89cd-32ed176f98b0.png)

**Minimal repro:**

**Comment by weltkante** [comment]
Just for the record, a lot of AssemblyInfo content is now in the project file instead - you should only bring back AssemblyInfo for settings which are __not__ in the project file, like WPF did. If all settings are covered by the project file then you don't bring back AssemblyInfo (instead just update documentation where those settings can be found)

**Comment by paul1956** [comment]
@weltkante yes I noticed that, and it is a breaking change that should have been documented as a breaking change but it also means About.vb and SplashScreen.vb need new Core templates and there needs to be a UI and storage for missing items like Save My.Settings on Shutdown, Authentication mode, Shutdown Mode, Splash Screen and someday Make single instance application. Most of these are stored in Application.myapp in Framework and some used in Application.Designer.vb at runtime. 

The purpose of this issue was to ask for **Project parity** with Framework not suggest an implementation.

**Comment by paul1956** [comment]
I am willing to do a PR for singleInstance would it be OK?

**Comment by weltkante** [comment]
If you didn't already start working on something, you may want to discuss first how its supposed to work, as the underlying technology (.NET remoting) is gone it needs to be replaced by something else and its unclear what that should be. I previously suggested using a named pipe instead of remoting, but that was just from a quick scan through the code, so I may have missed some details.

Note that there exists already an issue for this (#2056), so probably discussion should happen there.

**Comment by paul1956** [comment]
@weltkante moving discussion of Single Instance implementation to #2056. The issue of how to set it from the UI still needs to stay here.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can you update this issue?

**Comment by KlausLoeffelmann** [comment]
We will address this iteratively:

* An Application Framework template we will have most likely for 16.8 Preview 4. Also, the Project System work for this will most likely be done for Preview 4, but it will not include the new HighDpiSetting, which we will see later in the 16.9 time frame.
* This will also not include Settings, though, since they are not ready yet in the Designer, so we will add them later.
* We will not include a Default Resource file for now, but I expect a Resource file can be added via the App Designer at this time.

So, I am closing this for now, if there are no other objections. (Then please reopen this.)

**Comment by weltkante** [comment]
If this is closed, is there a tracking issue for updating the templates? I understand not tracking designer/project system issues here, but as far as I'm aware the templates are part of this repo?

**Comment by KlausLoeffelmann** [comment]
It depends. We're discussing this at the moment, what the flow for the templates is.

Problem is, that we would like to have a different VB templates for CLI and for AppFramework in VS. The reason for this is actually having the AppFramework template for the CLI doesn't make much sense since there is no way to trigger the source generators for MyApp.settings (Project System does this). 

But we may ending up with having the AppFramework templates also for the CLI until we have VS 16.9/net 6.0 and a different approach.

**Comment by paul1956** [comment]
Does anyone use CLI with VB WinForms apps? Is it possible to just include a default Application.myapp and Application.Designer.VB and any other needed files, for CLI that gets overridden by project system (not sure if that is what @KlausLoeffelmann  is referring to), Visual Studio users have to hand edit Application.Designer.VB and Setting.. today.
