### ISSUE TITLE
Support third-party languages with .NET Core WinForms Designer

### ISSUE THREAD

**Issue by sae42** [dotnet/winforms#2641]
* .NET Core Version: 3.1
* Visual Studio 2019 16.5 Preview 1
* Have you experienced this same bug with .NET Framework?: No

**Problem description:** Unable to use .NET Core Win Forms Designer with third-party languages

I'm not sure if this is the correct place to raise issues related to the Visual Studio .NET Core Win Forms designer, but I wanted to get some visibility into enabling support for third-party languages. Many VSIP language vendor partners spent a lot of time and effort into supporting the .NET Framework Win Form designer and at some point in the future customers that have .NET Framework Win Forms applications will want to move to .NET Core (.NET 5). It would be good if the new designer package could avoid hard-coded checks for project types which appears to be the cause of this particular issue. In the .NET Framework designer, the third-party project system can provide support for the language CodeDomProvider which doesn't appear possible with the current designer.

**Actual behavior:**

Issue occurs due to hard coded project type checks (for C#/VB) in get_Provider():

 	Microsoft.VisualStudio.WinForms.Package.dll!Microsoft.VisualStudio.Shell.Design.Serialization.CodeDom.Private.VSCodeDomDocDataAdapter.Provider.get()	Unknown
 	Microsoft.VisualStudio.WinForms.Package.dll!Microsoft.VisualStudio.Shell.Design.Serialization.CodeDom.Private.VSCodeDomDocDataAdapter.CompileUnit.get()	Unknown
 	Microsoft.VisualStudio.WinForms.Package.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(System.ComponentModel.Design.Serialization.IDesignerSerializationManager serializationManager)	Unknown
 	Microsoft.VisualStudio.WinForms.Package.dll!Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.DeferredLoadHandler.Microsoft.VisualStudio.TextManager.Interop.IVsTextBufferDataEvents.OnLoadCompleted(int fReload)	Unknown

**Expected behavior:**

Support for third-party language integration by using the language supplied CodeDomProvider

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann do you foresee any issues doing this in the Core Designer? Let's copy this issue over there if we can do it on our end. @sae42 we can keep you posted in this issue. We haven't yet implemented everything in our Core Designer so it may just be a case that this isn't implemented yet.

FYI - Future Designer specific issues you can totally raise on Developer Community, or better yet using the VS Feedback tool. It sends along telemetry and diagnostic information that helps us understand what is happening in your particular case more effectively.

**Comment by sae42** [comment]
@merriemcgaw Thanks, please keep me posted on this issue! Right now, because of the hard block I don't really have much indication of any future issues - it's a pity the VS designer extension is not open source as I'd be able to fix it myself and be able to progress.

**Comment by merriemcgaw** [comment]
I will open an issue in our designer repo and see what the thoughts of the team are, and how difficult this request might be.

**Comment by rodar21** [comment]
What is happening to this issue - it affects Synergex too. So often extensibility is missing. another chose is to just allow Languages like Cobol and Synergy/DBL to give you there GUIDS to hard code into the list, with other open source Microsoft projects we can do this by submitting PR's.

**Comment by merriemcgaw** [comment]
We're still looking into this issue, but to be fair our priority is getting the designer functionality to parity with the classic designer, and ensuring that control vendors have the tools they need to create custom controls. We'll be revisiting this once we've got the bulk of the expected functionality in place. All I can say for now is to say "stay tuned".

**Comment by spgennard** [comment]
@rodar21 - I can understand your point of view but I expect the customers of other languages wanting to use .NET Core WInForms won't.

**Comment by weltkante** [comment]
I'm worrying a bit that usability of WinForms outside of C# isn't considered "parity with classic designer". The flexibility and extensibility of the WinForms designer was its major strong point, and I'm not seeing much communication with developers how to port the design time experience of their controls or VS extensions (which includes third party languages).

> and ensuring that control vendors have the tools they need to create custom controls

Maybe more open communication would be good, not just with a few select vendors.

That said, I understand that the designer was/is lagging a lot behind the .NET Core port of WinForms, and also that the simple usage scenarios have higher priority than extensibility. It just feels lacking any mention in communication, so its totally unclear what your roadmap and goals are.

**Comment by merriemcgaw** [comment]
> Maybe more open communication would be good, not just with a few select vendors.

We're working on blog posts to help everyone who wants to create controls so that everyone knows what the current approach needs to be. We'll also be doing blog posts about which features are coming next and giving a much better roadmap for everyone to watch. Most of this should be coming up as we gear up to ship .NET 5. We do thank everyone for their patience with the designer. It turns out that much was rearchitected internally to support the out-of-process components and how those communicate with the VS process. 

/cc: @OliaG as FYI.

**Comment by viktoriad** [comment]
Hello. Do you have any plans to support third-party languages in .NET Core WinForms Designer for VS2022?

**Comment by merriemcgaw** [comment]
At this point it is not on our current roadmap. We're still focusing on bringing the performance and stability of the designer up to snuff. If the customer demand increases, we may consider being able to do this, but for now I don't see it on our roadmap for a while. We'll keep an eye on this issue and listen to our customers and if we do hear a lot of requests, I'd be happy to reopen and discuss the possibility. I don't see it coming into Visual Studio Dev 17.0 however, hence closing this issue.

**Comment by rodar21** [comment]
marty

From: Merrie McGaw ***@***.***>
Sent: Tuesday, August 3, 2021 12:41 PM
To: dotnet/winforms ***@***.***>
Cc: Roger Andrews ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [dotnet/winforms] Support third-party languages with .NET Core WinForms Designer (#2641)


Closed #2641<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fissues%2F2641&data=04%7C01%7CRoger.Andrews%40synergex.com%7C849445b60f5744b04adf08d956b6aa2a%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C637636164808131760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u4g%2FQeSKKiR53xRH6PCjPJWAW7Eg0jngQbkOX9pcVUQ%3D&reserved=0>.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fissues%2F2641%23event-5106780390&data=04%7C01%7CRoger.Andrews%40synergex.com%7C849445b60f5744b04adf08d956b6aa2a%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C637636164808131760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EeD1O%2BSqN4wqshndTHS%2F9dfbQMgycL0BJiINCxDwefk%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAE7VYFGXDKWMR3LOUQOW3ZDT3BA55ANCNFSM4KDGY4OQ&data=04%7C01%7CRoger.Andrews%40synergex.com%7C849445b60f5744b04adf08d956b6aa2a%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C637636164808141708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BmaUc24un7B%2BBMVxyIvZ2%2FODWH1RG%2B9Ro2doBxQ3QhY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CRoger.Andrews%40synergex.com%7C849445b60f5744b04adf08d956b6aa2a%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C637636164808141708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mUDxumCkkxTl5gPBufa1spkC7UFRQu1Q46F4ZY1eGfs%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CRoger.Andrews%40synergex.com%7C849445b60f5744b04adf08d956b6aa2a%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C637636164808151662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ShgaYyndyNLO6o889u7f0IpZqPVFOmZLRxvZx8GzJr0%3D&reserved=0>.
CAUTION: This email originated from outside of Synergex. Please do not click links or open attachments from an unknown or suspicious sender.
