### ISSUE TITLE
SendKeys.SendWait() sends wrong characters for some particular characters

### ISSUE THREAD

**Issue by scalablecory** [dotnet/winforms#2660]
_From @Naimad1CZ on Wednesday, December 18, 2019 10:55:26 PM_

Using:
Windows 10
.NET Core 3.1
Library System.Windows.Forms
Function SendKeys.SendWait()

Reproduce steps:
1. create a new project with those 2 lines in Main:
```
Thread.Sleep(5000);
SendKeys.SendWait("ĚŠČŘŽÝÁÍÉÚŮĎŤ");
```
2. Switch to Czech QWERTZ keyboard on Windows (on standard English keyboard you get the expected result)
3. Run the project and (during the first 5 second since the start) open some notepad or something like this
4. observe `ěščřžýáíéúůĎŤ` being written

Expected result:
observe `ĚŠČŘŽÝÁÍÉÚŮĎŤ` being written

Note + possible cause of problem:
On Czech Keyboard, all of letters `ĚŠČŘŽÝÁÍÉÚŮ` could be written by pressing a single button on keyboard in case that `CapsLock` is turned on, but `ĎŤ` couln't (`Ď` has to be written by pressing `ˇ` (actually `Shift` + key on the left of Backspace) and then `D` (`Shift` + `d`)), so maybe SendWait() gets info about keyboard keys, and if the characters that could be written on this keyboard using 1 key (+`Shift`/`CapsLock`), then it presses according keys, but in other case, it just presses maybe `Alt`+KeyCode or something. And in the first case, it forgets about pressing `CapsLock` when writing letters that are keyboard language-dependent.

_Copied from original issue: dotnet/core#4016_

**Comment by merriemcgaw** [comment]
Just to be clear, your code is working as expected if you've got the ENU keyboard, but when set to Czech it's failing?

Can you tell us more about your use case and whether this is blocking you?

**Comment by Naimad1CZ** [comment]
@merriemcgaw Yes, the code is working as expected if user of my program has English keyboard, but not when the user has Czech keyboard.

My case: I made (and will contuinue on developing probably during summer holidays) an auto-complete program for PC which offers relevant words to user even before typing the first letter of the word (the offer is based on previous word in this case). And uses `SendKeys.SendWait()` function to type the selected word.
So let's say that user wrote "Ahoj, kamaráde. " and selects word "Čeněk" from the offer. Then the written text would be "Ahoj, kamaráde. čeněk ", not "Ahoj, kamaráde. Čeněk ", which is a fail of the program based on the bug in the library that belongs to .NET Core.

And it looks like I don't have any other way how to fix this bug other than convince you to fix this bug in the library.

**Comment by RussKie** [comment]
> And it looks like I don't have any other way how to fix this bug other than convince you to fix this bug in the library.

There's at least one more option - you can send us a PR with a fix.

**Comment by weltkante** [comment]
Big warning in the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.sendkeys?view=netcore-3.1):
> If your application is intended for international use with a variety of keyboards, the use of Send could yield unpredictable results and should be avoided.

While it just says `Send` it probably is meant to also include `SendWait` and similar overloads.

What this is basically saying is that the input needs to be specific to a keyboard. You cannot use the same input and expect it to work on every keyboard.

> Use SendKeys to send keystrokes and keystroke combinations to the active application. [...] 

The WinForms SendKeys API is about sending key presses, not about translating arbitrary text into sequences of keypresses (which often isn't even possible). You already have to encode the input yourself by specifying which modifier keys you want to press (`+` being shift, `^` being control, `%` being alt). If you need different modifier keys (like CapsLock) I think you are out of luck since CapsLock usually isn't even a modifier key, its a sticky shift. I think you picked the wrong tool for what you are trying to achieve.

There is no general solution to the problem of translating arbitrary strings into keypresses. Keyboard maps are written in a binary code which is not reversible, it is not possible to figure out the necessary information expect by brute force and trying to press every key combination in the background until the right character pops out. Since there are potentially infinite combinations of input key sequences this is not feasible.

**Comment by merriemcgaw** [comment]
I agree with everything that @weltkante has said. The current implementation doesn't appear in my mind to be intended to do what the @Naimad1CZ is requesting. Making a new implementation of SendKeys() and SendWait() is not on our current roadmap.

**Comment by Naimad1CZ** [comment]
My friend advised me a pretty good workaround: just normalize the string using `Normalize(NormalizationForm.FormD)` and then put it as an argument to `SendKeys.SendWait(string keys)`.

I also discovered that `SendKeys.SendWait(string keys)` sometimes produces completely wrong letters when switching the keyboard layout during runtime, but that's a minor issue and I don't much need it to be fixed.
