### ISSUE TITLE
Erroneous border or spacing margin on TabControls

### ISSUE THREAD

**Issue by hsmoccio** [dotnet/winforms#2722]
* .NET Core Version: **3.1.1 (current)**

* Have you experienced this same bug with .NET Framework?: **Yes**

**Problem description:**

Since inception, there has always been a thin border or spacing margin present on `TabControl` objects when its appearance property is set to `Normal` (the default). This border usually measures 1 pixel high on the bottom and 2 pixels wide on the right. It cannot be hidden or styled, and is not the same as the usual `BorderStyle` property which some controls implement.

This is a tiny but long-standing appearance bug. I have attached a screenshot with the border highlighted in red. This was done in MSPAINT as the the border cannot actually be styled.

![TabControlBorderBug](https://user-images.githubusercontent.com/51760052/72478348-c749b880-37bf-11ea-9251-30bfed39884c.png)

**Expected behavior:**

The border/spacing margin should not be present. The `TabControl` should fill in these holes with its content.

**Suggestions:**

* Fix the underlying painting event to remove the border by filling in the empty space with the selected tab page's content.

* Implement a `BorderStyle` property which can show or hide this border. However, it may technically not be considered a border since it only encases the control on the bottom and left.

* Remove the spacing altogether. This may cause issues with control positioning on older projects because the size of the control changes slightly.

**Minimal repro:**

Create a .NET Core WinForms project and add a `TabControl` and a few `TabPages` to the main form. Here's some code if you are using a version of Visual Studio which does not have the WinForms designer ready. Some color is added for visibility:

```
BackColor = Color.Pink;

TabControl tc = new TabControl();

tc.TabPages.Add("tp1");
tc.TabPages.Add("tp2");
tc.TabPages.Add("tp3");

TextBox tb = new TextBox();
tb.BorderStyle = BorderStyle.None;

tc.TabPages[1].BackColor = Color.LightBlue;

Controls.Add(tc);
tc.SelectTab(1);
```

**Comment by weltkante** [comment]
> This is a tiny but long-standing appearance bug. [...] The border/spacing margin should not be present. The TabControl should fill in these holes with its content.

Just calling out that this may not be a genuine bug (investigation required). You may have to consider the case that the spacing is intentionally "built into" the common controls visual style to enforce a certain look when the control "fills" its container. I've also seen artificial margins on the visual style of buttons (they go away when visual styles are disabled) and always thought it was intentional.

**Comment by hsmoccio** [comment]
I figured this at first, but the other two appearance styles do not display this padding and neither do the various MFC, WPF or UWP tab controls. I do believe it's just an oversight with the control being drawn.

**Comment by RussKie** [comment]
More investigation is definitively required given the behaviour is not new and exists in .NET Framework.

**Comment by mikedn** [comment]
> I figured this at first, but the other two appearance styles do not display this padding and neither do the various MFC, WPF or UWP tab controls. I do believe it's just an oversight with the control being drawn.

WPF and UWP do not have anything to do with this, they're not using the Win32 tab control. I don't have MFC installed to check but I'm pretty sure that it too has those borders because a non-MFC Win32 app has it too and I'm not aware of MFC having its own tab control rendering (unless you're perhaps referring to the newer MFC controls that do not rely on existing Win32 controls).

As already stated, the border does come from visual styles. When visual styles were introduced, back in WinXP days, that border was used to draw a drop shadow. The shadow is gone now but the border has remained, either because they forgot to remove it or because it was considered a potential breaking change.

You can see the visual style border if you try to render `VisualStyleElement.Tab.Pane.Normal`.

**Comment by dreddy-work** [comment]
Thank you @hsmoccio for raising this.  Unfortunately, this requires support from Windows/Common controls and given the Winforms priorities, we will not be able to work/investigate on this further at this time.
