### ISSUE TITLE
PropertyGrid: Enum Property with DefaultValueAttribute for Vb.Net Classes are readonly

### ISSUE THREAD

**Issue by poutine70** [dotnet/winforms#2748]
* .NET Core Version: 
3.1.101

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

"Enum Type Read/Write Properties" of a class defined in Vb.Net with a DefaultValueAttribute are render "Readonly" (ghosted/can't be modified) in a property grid. Without the DefaultValueAttribute, the property grid behaves normally. The property grid works correctly if the class if defined in C#.

**Expected behavior:**
Property Grid should show the property as Read/Write regardless of the presence of DefaultValueAttribute or the language used to define the class owning the property.

**Minimal repro:**
See attached VisualStudio 2019 Solution

![image](https://user-images.githubusercontent.com/12993055/72824780-ddce9480-3c43-11ea-868a-9bfbfa4afd67.png)
[TestCase.zip](https://github.com/dotnet/winforms/files/4092286/TestCase.zip)

**Comment by merriemcgaw** [comment]
This could potentially be something in the underlying VB language. We should investigate. @dreddy-work / @KlausLoeffelmann can you guys comment on whether this is us or VB?

**Comment by KlausLoeffelmann** [comment]
I am pretty sure (although not entirely) this might be related to an issue we recently fixed in the .net runtime (not in the WinForms repo), and which especially surfaces for VB scenarios. If it is, it'll be fixed for .NET 6. I don't know if it's gonna meet the bar to get serviced for .Net 5 or .Net 3.1.

https://github.com/dotnet/runtime/issues/52116

**Comment by KlausLoeffelmann** [comment]
@poutine70, follow-up question: Is it important for you to have for 3.1, and if, I'd like to ask why? Would you be able to use .NET 6 when it becomes available? I am asking also, because a lot of things for VB are completely missing in 3.1 - like the entire Application Framework support. .Net 6 might be also more attractive, since we enabled a bunch of new WinForms features via Application Events of the AppFramework.

**Comment by dreddy-work** [comment]
Closing this given the fix is in latest runtime. Will revisit if this needed servicing.

**Comment by Jenna-Zheng** [comment]
Verified this issue with  .NET SDK 6.0.100-rc.2.21429.3, it is fixed that Property Grid show the property as Read/Write regardless of the presence of DefaultValueAttribute or the language used to define the class owning the property.
![Issue_Test](https://user-images.githubusercontent.com/64949616/131308187-ff480784-80ab-45da-b3a2-b77913592e96.gif)
