### ISSUE TITLE
[Proposal] Add a new kind of dialog box ---- InputDialog

### ISSUE THREAD

**Issue by ygc369** [dotnet/winforms#2891]
InputDialog can be used to get user's input text. VB already has this kind of dialog box. I hope that C# winform can have a more powerful one. (Although C# can use VB's InputBox, but it is ugly.)

**Comment by RussKie** [comment]
Please provide more details, including (but no limited to) references to Win32 API, screenshots, a proposal for the new API proposals, and what usecases it would be addressing.

**Comment by ygc369** [comment]
@RussKie 
I don't know much about Win32 APIs, I just want an InputDialog as a new control.
Roughly it should be a new kind of MessageBox with a TextBox. It would be used when the program need user's input.
It can be like this:
+-----------------------------------------------------------------------+
|  Title Text                                                                                          |
+-----------------------------------------------------------------------+
|    Content Text                                                                                  |
|     +-------------------------------------------------------+                |
|      |   Input Text                                                               |                 |
|     +-------------------------------------------------------+                |
|                  (OK Button)               (Cancel Button)                              |
+-----------------------------------------------------------------------+

**Comment by weltkante** [comment]
I can confirm the need for a generalized input mechanism for simple text requests. Usually everyone builds his own dummy form for such a purpose but of course that means in practice it doesn't have uniform user experience across applications. Message boxes, save file dialogs etc. all get a uniform user experience so IMHO the same should be applied to simple input requests.

There already exists a [VB API `Interaction.InputBox`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction.inputbox?view=netframework-4.8) for this purpose so theoretically it is now available to everyone since those VB APIs are part of WinForms now (I think you automatically reference the VB assembly also in C#? can't test right now since VS preview 3 broke the whole editor for me). In either way the API is not discoverable and the user experience needs modernization.

Example usage of existing API:
```csharp
Interaction.InputBox("Description or prompt for requested input:", "Dialog Title", "Default Response");
```

![image](https://user-images.githubusercontent.com/5845814/75037525-a8bc9880-54b4-11ea-8e1b-555a42d71fcd.png)

Issues with the existing input form:
- As you can see for example on a german OS the cancel button doesn't fit its label and is cut off.
- You cannot set an owner, even though its a modal form, so it will just assume the currently focused form is the owner. Normally WinForms APIs like `MessageBox.Show` and `ShowDialog` take an `IWin32Window` to use as the owner.
- The layout of the buttons is not modern, you usually have ok/cancel buttons at the bottom of the dialog these days. I don't know if Microsoft still has general guidelines how the layout of simple dialogs should look like, but if in doubt I'd say keep it as similar to a message box as possible.
- The API is not discoverable as it is part of the `VisualBasic` namespace, hidden as a static method inside a class. Ideally the input dialog would have an object oriented API akin to `SaveFileDialog` etc. in order to fall into the common usage pattern of dialogs in WinForms, even though there is no underlying Windows API to call.

I assume if there is nobody to drive the proposal the best we can get is reworking the existing VB form to meet minimum user experience requirements?

**Comment by ygc369** [comment]
@weltkante 
I used VB's InputBox before, but I dislike it, for it is ugly and looks inconsistent with other part of my application.

**Comment by merriemcgaw** [comment]
@ygc369 what would your ideal InputDialog look like? Is there a reason you would be blocked creating a simple InputDialog for your application which is consistent and aligns with the visuals in your app?

**Comment by ygc369** [comment]
@merriemcgaw 
It should look like a MessageBox with a TextBox in the center. 
Everybody can create his own InputDialog, but as it is commonly used, many people have to do the same and repeated work, so they waste a lot of time. If the InputDialog can become an official control, it would save people's time.

**Comment by merriemcgaw** [comment]
In answer to your question @weltkante, it's not really high on the radar or on the road map at this point. The case is interesting, but we don't have a lot of data points that would tell us we need to prioritize this above say the ARM64 work. That said, if the community wants this feature and is able to propose specific changes to the VB.NET one or it's own API, I'm totally happy to consider it and help shepherd it through the API review process.

**Comment by merriemcgaw** [comment]
This unfortunately doesn't align with our general principle of generally exposing Win32 APIs. The InputBox is available if needed as well.
