### ISSUE TITLE
NullReferenceException is thrown when creating a control in an MDI child form

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#2979]
* .NET Core Version: 5.0.100-preview.3.20163.3.9

* Have you experienced this same bug with .NET Framework?: 
Yes

**More Info**
This is a not regression issue, it can reproduce from .Net 2.0 to .Net 4.8.

**Minimal repro:**

1. Extract the attached “Core.zip” and open it in VS.
2. Build and run this solution, then click the “Exception occurs by click” button on the form, an exception will show.
[Core.zip](https://github.com/dotnet/winforms/files/4337922/Core.zip)

**Expected behavior:**
The application can be run successfully.

**Actual behavior:**
An exception is thrown when Add a New Control to the Panel.
![image](https://user-images.githubusercontent.com/45864649/76754447-61d26380-673f-11ea-830d-1cb0b4bb9b79.png)

**Comment by merriemcgaw** [comment]
Given this is how Framework worked, we will address this sometime in the future.

**Comment by RussKie** [comment]
Here's where it fails:
![image](https://user-images.githubusercontent.com/4403806/77501867-556fa880-6ead-11ea-96dd-a383af58cec9.png)

I've tested and the bug replicates as far as net452. Not sure if this worked ever...

**Comment by weltkante** [comment]
I want to note that this is not a general problem, I can use MDI child forms with controls just fine.

The example can be made working by moving `Controls.Add(new Control())` out of the Resize callback into the constructor or load event.

I'd say adding new controls in a resize callback is a bit of an edge case so I'm not surprised there are bugs. Also for other controls (like Button, CheckBox) I don't get the exception.

So I think while this is a bug it has low priority (either to fix or providing a better exception) because the normal use cases where you add controls in the constructor/load event work just fine.

**Comment by RussKie** [comment]
Thank you. Doing further tests today I got a new insight - the crash **only** occurs if the "ChildForm" maximised.

Here I made it "float", and was able to create new children:
![image](https://user-images.githubusercontent.com/4403806/77599921-7d691580-6f5a-11ea-92ce-e22f5922bddf.png)


If I maximise the ChildForm, and click the button - crash!

**Comment by merriemcgaw** [comment]
Let's address the NullRef because we want to avoid those.
@JeremyKuhne to review.

**Comment by weltkante** [comment]
The bug ist that `NativeWindow.CreateHandle` is not reentrant. [this line](https://github.com/dotnet/winforms/blob/62c17fe35b2f00f8156828148a5fbbb910cc52a1/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs#L434) assumes the variable `windowClass._targetWindow` is null and [resets it here](https://github.com/dotnet/winforms/blob/62c17fe35b2f00f8156828148a5fbbb910cc52a1/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs#L477) back to null.

In the failure case the [CreateWindowEx](https://github.com/dotnet/winforms/blob/62c17fe35b2f00f8156828148a5fbbb910cc52a1/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs#L456) call will trigger a user code event (your resize handler) which will create another control while being in the process of creating a control. The inner control creation stomps over the `_targetWindow` variable of the outer control creation.

The fix is probably to make `NativeWindow.CreateHandle` reentrant by storing the old value of `_targetWindow` and restoring it when done, instead of resetting to null.

**Comment by RussKie** [comment]
Knowing you, you're probably right in your conclusions :)

I suspected as much, but I'm struggling to see how it is happening:

line:422 - create a new instance of a `WindowClass`
line:434 - assign itself as `_targetWindow` on that instance
line:456 - call `User32.CreateWindowExW`
line:477 - unassign itself from `_targetWindow` on that instance

A re-entrant code would be operating on its own instance pf `WindowClass`, no? What am I missing?

**Comment by weltkante** [comment]
> A re-entrant code would be operating on its own instance pf `WindowClass`, no? What am I missing?

Window classes have to be registered, so [WindowClass.Create](https://github.com/dotnet/winforms/blob/5bd006cc675cfa378cff76dcc3e44e6c627cbed7/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.WindowClass.cs#L61) reuses already registered window class instances. If your resize callback adds a `Button` instead of a `Control` you don't get the exception because reentrant `NativeWindow.CreateHandle` will operate on a different window class.

**Comment by weltkante** [comment]
@RussKie Added PR with the "obvious" fix to the problem, storing the _targetWindow in a local variable and restoring it afterwards, instead of assuming it is null. You mentioned you were running into problems when you tried to fix the issue on your side, if these problems also occur here or if I missed something I'll be happy to debug.

Also this really needs a unit test, but I have no idea how to test this.

**Comment by RussKie** [comment]
Thank you, I'll test your fix on Monday.

We can code the test as an integration test in our maui suite. Just take the code from the example and observe that it doesn't crash 🤗

**Comment by Jessie-Zhang01** [comment]
Verified this issue with .Net Core 5.0.100-preview.4.20209.25 from Master branch, this issue is fixed, The application can be run successfully and not crash.

**Comment by RussKie** [comment]
Thank you @weltkante
