### ISSUE TITLE
How to change ActiveWindow

### ISSUE THREAD

**Issue by Jmales** [dotnet/winforms#3009]
I have a .NET Framework app where I need to change the active window that is focused. This does the trick:

```
    public override void SetFocus (IntPtr window) {
        Win32.SetForegroundWindow(window);
    }
```
And with this I'm able to select either a Chrome browser or one of my app windows as the active window.

Now I'm in the process of moving it to .NET Core to work in Mac as well and I can't find any way of changing the selected window.

Is this possible to do in .NET Core in any way?

**Comment by RussKie** [comment]
@Jmales from the description it isn't easy to see whether the question is Windows Forms related or more inquiring about BCL x-plat capabilities.

On Windows [`SetForegroundWindow` API](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow) hasn't gone away and is still available.

> moving it to .NET Core to work in Mac

.NET Desktop (i.e. Windows Forms, WPF and UWP) only work on Windows. Equally Win32 API are Windows-only too, so you will need to find how window management is implemented on Linux or Mac OS. 
I don't know for sure, but I doubt BCL provides that capability because (I would think) it falls under the "Desktop" category, which isn't x-plat.
Overall I suspect you will have a hard time porting your UI app to non-Windows platforms without a significant effort (rewrite).

Mono has/had a Windows Forms implementation that provided certain functional parity with Windows on other platforms, but you will need to ask there for any advice.
My quick search hasn't yielded much, but you could start there: https://github.com/mono/mono/search?q=SetForegroundWindow&unscoped_q=SetForegroundWindow
