### ISSUE TITLE
Can not find the file "alg.exe" with OpenFileDialog

### ISSUE THREAD

**Issue by 15092368540** [dotnet/winforms#3044]
App with x86 build, then running in x64 System, OpenFileDialog's Filter properties don't work either,
and can not find the file "alg.exe"

.Net Framework and .Net Core have same problem

[Test.zip](https://github.com/dotnet/core/files/4433456/Test.zip)

![X86OpenFileDialog](https://user-images.githubusercontent.com/49462433/78472808-4f5fae80-776e-11ea-90c6-cbeb2fe1d8d3.png)

**Comment by weltkante** [comment]
I'm not sure I understand the problem description, but note that running x86 on x64 OS will enable folder redirection, you might be seeing `C:\Windows\SysWOW64` which contains the x86 version of `System32`. In this case this is expected and [documented](https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector) behavior, unrelated to WinForms.

**Comment by RussKie** [comment]
@weltkante  I think the issue depicted if that the filter (i.e. `ofd.Filter`) sets "*.exe" but the dialog shots *.dll.

@15092368540 does it work correctly if you build a x64 app and run it on x64 OS? And equally, if you run a x86 app on x86 OS?

**Comment by 15092368540** [comment]
with "FileInfo" test again, Isn't it right that as long as the program is working properly, it should get the right results? 
[test-2.zip](https://github.com/dotnet/winforms/files/4450387/test-2.zip)

**Comment by RussKie** [comment]
I am unable to reproduce the issue on Win10 x64.

* "test.zip" netcoreapp3.1
  ![image](https://user-images.githubusercontent.com/4403806/78845030-cfc23000-7a4a-11ea-9acf-a9453a375d63.png)
  ![image](https://user-images.githubusercontent.com/4403806/78844978-ab665380-7a4a-11ea-8de8-41b1dafaed25.png)


* "test-2.zip" netcoreapp3.1
  ![image](https://user-images.githubusercontent.com/4403806/78844808-3561ec80-7a4a-11ea-991e-c5ca6b28f1cd.png)
  ![image](https://user-images.githubusercontent.com/4403806/78844739-f5026e80-7a49-11ea-97ef-48c4bec9583b.png)

**Comment by kpreisser** [comment]
I noticed this issue (filter in the `OpenFileDialog` is not applied) on Windows Server 2019 that was installed using the **Server Core** option, and where the [Server Core App Compatibility Feature on Demand](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19) is installed. However, I also cannot reproduce it e.g. on a regular Windows 10 machine.

E.g., when using the following code (which opens the native `System32` directory by using `sysnative` if present):
```c#
    [STAThread]
    static void Main()
    {
        Application.EnableVisualStyles();

        string sysNativePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.Windows, Environment.SpecialFolderOption.DoNotVerify),
            "sysnative");

        string systemDir = Directory.Exists(sysNativePath) ? sysNativePath : Environment.SystemDirectory;

        var openFileDialog = new OpenFileDialog()
        {
            Filter = "*.exe|*.exe",
            InitialDirectory = systemDir
        };
        openFileDialog.ShowDialog();
    }
```

Running the application with an **x64** runtime (the filter is correctly applied):
![grafik](https://user-images.githubusercontent.com/13289184/81109953-2c661d00-8f1b-11ea-8c31-c31b3954a280.png)

Running the application with an **x86** runtime (the filter doesn' seem to be applied, and all files are shown):
![grafik](https://user-images.githubusercontent.com/13289184/81109979-3425c180-8f1b-11ea-8778-d8b815b6757b.png)

However, this issue doesn't seem to be related to WinForms, because it also happens with other native programs like `notepad.exe`, when running the **x86** version from `SysWOW64`:
![grafik](https://user-images.githubusercontent.com/13289184/81110167-78b15d00-8f1b-11ea-8dad-b162ea04ad9b.png)

**Comment by RussKie** [comment]
@kpreisser  thank you for looking into it!
