### ISSUE TITLE
MouseWheel: WHEEL_DELTA not public

### ISSUE THREAD

**Issue by SommerEngineering** [dotnet/winforms#3069]
* .NET Core Version: 3.1.102

**Problem description:**
The documentation of the `MouseEventArgs.Delta` property (see [link](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.mouseeventargs.delta?view=netcore-3.1)) mentions the constant `WHEEL_DELTA` . However, this constant is not available to the public. It is located in the internal class `NativeMethods`, see [link](https://github.com/dotnet/winforms/blob/c7fdb009b620fc50f14f35250429df666c9a280d/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs#L80).

**Expected behavior:**
The constant is available to the public in order to perform calculations with it. Alternatively, the constant gets not mentioned in the documentation.

Inconsistently, this constant is not mentioned in the `Control.MouseWheel` event documentation (see [link](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.mousewheel?view=netcore-3.1)). Instead, it refers to `SystemInformation.MouseWheelScrollLines`. Might these two documentations should be unified.

**Minimal repro:**
Not necessary in this case.

**Comment by weltkante** [comment]
Note that in the remarks the `WHEEL_DELTA` is defined:
> One wheel notch, a detent, is defined by the windows constant WHEEL_DELTA, which is 120.

So `WHEEL_DELTA` in the docs does _not_ refer to the [NativeMethods constant](https://github.com/dotnet/winforms/blob/c7fdb009b620fc50f14f35250429df666c9a280d/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs#L80) you linked, they are just named the same because they represent the same concept.

`SystemInformation.MouseWheelScrollLines` is a different value you _also_ have to respect. It is not a constant but a system setting the user can adjust to indicate how far one `WHEEL_DELTA` is supposed to scroll.

The [event documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.mousewheel?view=netcore-3.1) you linked spells out the `WHEEL_DELTA` without mentioning giving it a name:
> The UI should scroll when the accumulated delta is plus or minus 120.

So what the doc tries to convey is that the C/C++ headers have a constant `WHEEL_DELTA` with value 120 and you should be using that value 120 when processing wheel deltas.

**Comment by merriemcgaw** [comment]
@SommerEngineering did @weltkante answer your question (thanks, btw)? I'll be happy to transfer this issue to the docs repo and have someone there put it on the backlog.
