### ISSUE TITLE
The text and icon of tooltip are not displayed on the same horizontal line

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#3153]
* .NET Core Version: 
5.0.100-preview.5.20227.13

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
The text and icon of tooltip are not displayed on the same horizontal line.
![Coe](https://user-images.githubusercontent.com/62929087/80458532-838c5080-8963-11ea-8e64-5c8db719e9b5.png)

**Expected behavior:**
The text and icon of tooltip should be displayed on the same horizontal line.

**Minimal repro:**
1. Create a winforms core project.
2. Add a button and a tooltip controls to form designer.
3. Set the button's ToolTip on toolTip1 as: hello, this is button1.
4. Set the tooltip's ToolTipIcon as **Info**.
5. Run the core project.
6. Focus on the button using mouse to see the tooltip of button.

Or
1. Run the attached project. 
[TooltipApp.zip](https://github.com/dotnet/winforms/files/4543969/TooltipApp.zip)
2. Focus on the button using mouse to see the tooltip of button.

**Comment by elachlan** [comment]
The space is because we set the `ToolTipTitle` to an empty space if one isn't provided and the `ToolTipIcon` is set. There is a comment in the `ToolTipIcon` property about it.
https://github.com/dotnet/winforms/blob/e199c86138cf8fee176bddd3f7e19ec62a526765/src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs#L448-L450

![image](https://github.com/dotnet/winforms/assets/2433737/af72d8df-40c7-4029-83a1-00b29c664f98)

@merriemcgaw not sure what the team wants to do with this. I think its a limitation of the ToolTip control that we can't work around.

**Comment by elachlan** [comment]
Also it isn't documented that a title is required for an icon: https://learn.microsoft.com/windows/win32/controls/ttm-settitle

**Comment by merriemcgaw** [comment]
Then let's not worry about this issue!
