### ISSUE TITLE
The default title of MsgBox is not correct

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/winforms#3161]
* .NET Core Version: 
5.0.100-preview.3.20216.6

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The default title is "Microsoft.VisualBasic.Core" instead of the name of the calling assembly.
![image](https://user-images.githubusercontent.com/10798596/80573038-daf8f200-8a31-11ea-94aa-875afa229d5f.png)

**Expected behavior:**
The default title should be the name of the calling assembly.
![image](https://user-images.githubusercontent.com/10798596/80573409-7e4a0700-8a32-11ea-89ff-88d9d0fe4b20.png)

**Minimal repro:**
Run the following code in a VB winforms project:
```vbnet
MsgBox("Content")
```

**Comment by Nukepayload2** [comment]
https://github.com/dotnet/winforms/blob/f2739b430fbd2f729cf665d1df8c928da9c0eb0c/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb#L398
`System.Reflection.Assembly.GetCallingAssembly()` should be executed in `Microsoft.VisualBasic.Core`.

**Comment by weltkante** [comment]
Or it could just use the WinForms `Application` API which also exposes the application name (and already had bugfixes to make it work for .NET Core, I don't know if VB's version of GetTitleFromAssembly needs updates, WinForms did)

**Comment by hamarb123** [comment]
I'd like to fix this, I can do a PR.
One way I could fix it is by moving `GetTitleFromAssembly` to the dotnet/runtime repo and moving the `Title` check there.
Another way it could be done is by writing `InvokeMethod`s in IL code and then just calling the function without reflection, and forcing inlining to happen with `aggressiveinlining` (which should pretty much always inline it since it is just a simple method call) - this way might cause a new dll (unless there's one it could easily go into), but should be faster and keep code separation as well. This would be my preferred way.
Alternatively, "Or it could just use the WinForms `Application`", but you'd have to tell me what to do with that.

**Comment by RussKie** [comment]
This API is being deprecated (see https://github.com/dotnet/runtime/pull/73838). [`MessageBox` API](https://docs.microsoft.com/dotnet/api/system.windows.forms.messagebox) should be used instead.
