### ISSUE TITLE
Flaky test: `ProfessionalColorTable_ChangeUserPreferences_GetColor_ReturnsExpected` deadlock

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#3254]
**Problem description:**

After #3226 was merged, `ProfessionalColorTable_ChangeUserPreferences_GetColor_ReturnsExpected` tests started deadlocking in x86 mode that caused CI builds to fail again.
I managed to reproduce the deadlock locally, though it took few attempts to do so.

Looks like the test deadlocks on itself, there are no other user-code executed:
![image](https://user-images.githubusercontent.com/4403806/81555995-eacaeb80-93cc-11ea-9af3-78e5f32ee5e5.png)

![image](https://user-images.githubusercontent.com/4403806/81555946-ccfd8680-93cc-11ea-880a-7ef98bf4bc56.png)

**Expected behavior:**

The tests work as expected.

**Minimal repro:**

A repro is bit convoluted. Unfortunately `build.cmd -test -platform x86` command doesn't appear to work unless `Winforms.sln` is configured for x86 platform (which breaks other modes).

**Comment by weltkante** [comment]
> Looks like the test deadlocks on itself, there are no other user-code executed:

When it looks like its "deadlocking on itself" it instead is usually sending a window message to a control without message loop.

SendMessageOnUserPreferenceChange sends a message to the desktop, which probably tries to notify all forms, so if there is _any_ that has not been properly disposed and still hanging around without a message loop you'll probably see this hang.

You could try running the test under RemoteExecutor like the other one @hughbe recently moved, forgot which it was, something with visual styles I think.

Alternatively figure out which control is not properly disposed, but that probably needs some tracking infrastructure.

**Comment by weltkante** [comment]
The SystemEvents class will "take over" the STA thread from which it is invoked and expects it to live until the process terminates.

That means SystemEvents are incompatible with multiple UI threads, you'll have to test SystemEvents in a RemoteExecutor.

**Comment by RussKie** [comment]
Thank you.

> Alternatively figure out which control is not properly disposed,

That's _probably_ not too difficult - throw an exception in `~Control` :) Though I think we could drown in those.

> You could try running the test under RemoteExecutor

The trouble with the RE - https://github.com/dotnet/arcade/issues/5325
So while it is runnable locally, it doesn't appear to be runnable on the build agents...

**Comment by RussKie** [comment]
> The SystemEvents class will "take over" the STA thread from which it is invoked and expects it to live until the process terminates.
> 
> That means SystemEvents are incompatible with multiple UI threads, you'll have to test SystemEvents in a RemoteExecutor.
> 
> Alternatively, if you could force SystemEvents to be first accessed on an MTA thread, then it would create and maintain its own STA thread and not cause failures. But I don't see how you can easily enforce that the first access to SystemEvents happens on MTA.

Wow, thank you!

**Comment by weltkante** [comment]
> That's probably not too difficult - throw an exception in ~Control :) Though I think we could drown in those.

Yeah and it doesn't help here either way, the HWND which deadlocks doesn't inherit from Control, SystemEvents has its own implementation.

**Comment by RussKie** [comment]
If it deadlocks on a undisposed control, wouldn't we just need to catch those via the finalizer calls?
Or is there something else that you have in mind?

**Comment by weltkante** [comment]
Its a native control (HWND) which it creates for message dispatching purposes. The control is created the first time someone accesses SystemEvents, it checks the apartment. If its STA it creates the HWND on the current thread, otherwise it creates a separate STA thread.

So if your first invocation of SystemEvents is on a WinFormsFact then SystemEvents will create its broadcast HWND on that thread, but the thread is not going to live until process exit, so any message sent to SystemEvents by anything else than the very first WinFormsFact will hang.

**Comment by hughbe** [comment]
FYI it is implemented here: https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Win32.SystemEvents/src/Microsoft/Win32/SystemEvents.cs

Would a fix be to change the `WinFormsFact` to be `Fact`?

**Comment by weltkante** [comment]
> Would a fix be to change the WinFormsFact to be Fact?

Probably, but you need to enforce that on every usage of SystemEvents (including indirect usages). I don't know if WinForms itself depends on SystemEvents, but if the first invocation happens indirectly through Application.Run or something you still are flaky since you depend on the "right" test to be executed first.

Running it in RemoteExecutor seems to be the safer thing to do.

**Comment by Tanya-Solyanik** [comment]
We had seen this bug in the .NET framework, in Watson crash dumps and from customer service. Here is a small repro in the .Net Framework. Would be good to have it fixed.

```
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TwoStaThreads
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            Thread staThread = new Thread(NonAlwaysPumpingThreadProc)
            {
                IsBackground = true
            };
            staThread.SetApartmentState(ApartmentState.STA);
            staThread.Start();

            Application.Run(new Form
            {
                Text = "Main UI Thread"
            });
        }

        static void NonAlwaysPumpingThreadProc()
        {
            Form f1 = new Form
            {
                Text = "non-pumping thread - close me",
                Size = new System.Drawing.Size(600, 100)
            };

            f1.ShowDialog();

            // at this point we are no longer pumping messages, 
            // but the thread and it's message only marshaling window is alive
            while (true)
            {
                Thread.Sleep(1000);
            }
        }

    }
}

```

**Comment by weltkante** [comment]
Just for the record, your snippet has a bug, a form that is displayed with `ShowDialog` needs explicit disposal, you only get automatic disposal when calling `Show`. That is because after `ShowDialog` the user usually wants to read out dialog results and if the handles are already gone it may not be possible to read all entered data anymore.

I don't think you can do anything if a STA thread decides to no longer pump messages, this is basically a bug in user code the user has to fix. Any COM call on an STA object created on this thread would hang as well, so this problem is not .NET specific. Its a general problem and the users fault, marking a thread STA means it needs to pump messages or be shut down.

The design issue with SystemEvents is that there is no infrastructure to uninitialize itself when a thread _shuts down_ (which is different from stopping to pump messages)

**Comment by JeremyKuhne** [comment]
This is something we've gotten user feedback on (CSS & Watson).

**Comment by Tanya-Solyanik** [comment]
This could be fixed in this test, but it would be even better to re-design how SystemEvents are initialized.

**Comment by hughbe** [comment]
would have to open issue in dotnet/runtime. @weltkante you're an infinitely busy guy but if could open an issue, would be awesome since you know everything!

**Comment by weltkante** [comment]
Created an issue, not sure I can do much more, basically just analyzed the stacktrace and did some guesswork. The cleanest solution would be if thread shutdowns were observable, then it could automatically unregister the HWND before the thread is gone.

**Comment by weltkante** [comment]
This has now been fixed in the runtime

**Comment by RussKie** [comment]
Thank you ;)
