### ISSUE TITLE
Fully-themed controls

### ISSUE THREAD

**Issue by jnm2** [dotnet/winforms#357]
If you want to obtain a native look and feel in your projects, you currently have to redo minor implementations over and over to obtain these effects:

- Getting the fade effects on some common controls (Buttons, Checkboxes, Radiobuttons, Textboxes, Comboboxes)
- Getting images working on Buttons while preserving fade effects
- Getting the fade effects on Toolbars
- Getting the new theming on MainMenus and ContextMenus
- Getting CommandLinks and SplitButtons
- Getting different colored Progressbars
- Getting the explorer-like interface for ListBoxes and TreeViews 

Articles like this one explain how: https://www.codeproject.com/Articles/18858/Fully-themed-Windows-Vista-Controls (has images)

Would you consider including some or all of these upgrades in the box? I'm willing to contribute.

**Comment by zsd4yr** [comment]
Looking over the link. 

For example, this would mean adding out-of-the-box options for the color of a progress bar?

**Comment by wjk** [comment]
Quick note: The fade effect on buttons, checkboxes, and radio buttons is currently supported. The reason why it doesn't show up is because the controls in question default to `FlatStyle.Standard`. If you change them to use `FlatStyle.System`, then the fade effect will trigger. [As the documentation notes](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.flatstyle?view=netframework-4.7.2), setting the FlatStyle to System by default would break things, so I don't recommend changing that.

**Comment by jnm2** [comment]
@wjk I'd specifically like to achieve feature parity with `FlatStyle.Standard` while gaining the system fade effect. I've coded custom controls directly against BeginBufferedAnimation etc, so that route is an option if there's a roadblock preventing parity any other way.

**Comment by CatGirlsAreLife** [comment]
Well I am currently writting my own version of winforms based upon reference source and what resources I can dump from ILSpy and then removing the controls I know that I never use.
However the special buttons I find linked here seem usefull to add to mine. Heck I was planning on getting what all I can from wpf as well in the same binary too (and maybe find a working Save/OpenFileDialog or or FolderBrowserDialog that is actually more WPF friendly.

That and I want to experiment on hacking the wpf controls to work on normal forms too in that test library too so.

**Comment by merriemcgaw** [comment]
Circling back on this issue. I can tell you that certainly we would be interested in some of these apis to be added in the box to WinForms. I really like several of the ideas you mention. The best way to go about them is to create an issue for the item you'd really like to implement and make the api suggestion. We would evaluate each one independently, and would totally take community contributions. I particularly love the idea of Explorer theme on ListViews and TreeViews. Have at it!

Note that we're going to be starting to add accessibility testing to the system as soon as we can using the new [Accessibility Insights ](https://github.com/Microsoft/accessibility-insights-windows)tool. Any new features would need to be run against this tool so that we can ensure an accessible experience for our customers. Stay tuned for more on that.

I'm going to close this issue, as I think I've answered your basic question - would we take the apis if the community provided the work. And the answer is a resounding yes, as long as we go through the appropriate API Review Board process.  Let me know if you guys have any other questions about this. I look forward to seeing these. It will be awesome to make WinForms apps feel more modern!

**Comment by AraHaan** [comment]
Idk if this would or could go here but; I am now working on themeing my controls and this includes some test hacking on NCPAINT as well on the form’s nc area.

However I have a question; can I have a class that provices a custom ScrollBar renderer be applied to the scrollbars of any ScrollableControls with autosize set to true?

**Comment by weltkante** [comment]
> Idk if this would or could go here 

@AraHaan no, this issue was about fully enabling the native themes (unfortunately the issue name is ambigous). Your request is better served as a separate feature request issue.

**Comment by AraHaan** [comment]
Alright thanks.

**Comment by RussKie** [comment]
@AraHaan this is awesome!

In the interest of having the most productive and enjoyable experience for everyone please open a new discussion for each control you want to style/theme.
This is necessary so we together can discuss requirements, implementations and other considerations (e.g. accessibility) we need to have in order for changes to be accepted into the codebase.

It is extremely sad when someone spends a considerable amount of time and effort working on a change and that change can not be accepted.

**Comment by devliber** [comment]
I'm very interested in enabling the Explorer theme on ListViews and TreeViews by default, but I didn't find an issue for this so far.

As a side note, it seems there is already a [ApplyListViewThemeStyles](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs#L880) method in the `System.Windows.Forms.Design.DesignerUtils` internal class that implements this.

**Comment by RussKie** [comment]
@devliber please open a new issue for this. The more information you put - the better. If you have a proposal on a fix - great!
