### ISSUE TITLE
There is no detailed description for some properties of ToolTip control

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/winforms#3579]
* .NET Core Version: 
5.0.100-preview.8.20363.2

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
There is no detailed description for some properties of ToolTip control.
![image](https://user-images.githubusercontent.com/54019172/87495262-830e7680-c683-11ea-8810-7687689bec65.png)

**Expected behavior:**
The description of the property should describe the function of the property in detail.
![image](https://user-images.githubusercontent.com/54019172/87495269-89045780-c683-11ea-9096-84aef787ccb7.png)

**More info:**

1. Affected Properties of ToolTip control: InitialDelay, OwnerDraw, ReshowDelay, ShowAlways, Tag, ToolTipIcon, ToolTipTitle.
2. This issue also occurs in the "ToolTip on tooltip" property of other control.
3. This issue also can reproduce with .Net Core 3.1.

**Minimal repro:**

1. Create a Winforms core app
2. Drag and drop a ToolTip control to the form
3. Observe the property description of the ToolTip control in Property Browser window

Or

1. Extract the attached project and open it
[ToolTipPropertyDescription.zip](https://github.com/dotnet/winforms/files/4922648/ToolTipPropertyDescription.zip)
2. Build and run it, observe the property description in PropertyGrid

**Comment by RussKie** [comment]
Looks like we're using incorrect attribute decorations:
https://github.com/dotnet/winforms/blob/2ae45c66fdcb8e6aadf43288b7429f17f1fd0f49/src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs#L330-L331
https://github.com/dotnet/winforms/blob/2ae45c66fdcb8e6aadf43288b7429f17f1fd0f49/src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs#L357-L358

...instead of
https://github.com/dotnet/winforms/blob/2ae45c66fdcb8e6aadf43288b7429f17f1fd0f49/src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs#L282-L284

We appears to have regressed in 60acd0e81b25067b6cbf5d6a987e540f1106e71c (@hughbe 👀)
