### ISSUE TITLE
An error pops up after clicking the smart tag of ToolStrip/MenuStrip/StatusStrip/TreeView/PictureBox controls

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#3637]
* .NET Core Version: 
5.0.100-rc1.20373.1

* Have you experienced this same bug with .NET Framework?: 
No

**More info:**
This is a regression issue of .NET5.0 5.0.100-rc1.20373.1, it cannot reproducing with 5.0.100-rc.1.20371.1 build and .NET Core 3.1 version.

**Problem description:**
User try to show the Tasks dialog to modify some properties using smart tag, but an error pops up after clicking the smart tag button.

![Actual](https://user-images.githubusercontent.com/18568603/88367764-2451a700-cdbf-11ea-8a24-3f6614bc169b.png)

**Expected behavior:**
The Controls' Tasks dialog should be shown normally.
![Expected](https://user-images.githubusercontent.com/18568603/88367780-2ddb0f00-cdbf-11ea-92ca-0b96b8fb50bc.png)

**Minimal repro:**
1.	Create a winforms core project.
2.	Drag and drop a ToolStrip control to form designer.
3.	Click the smart tag in the top right corner of the ToolStrip control.

**Comment by DustinCampbell** [comment]
Is this the case of another type getting moved without a type forwarder?

**Comment by weltkante** [comment]
Could be related to #2411 where attributes link to non-ported classes. Not sure if these are now private to the designer or still need to be ported, but as it stands the annotations within WinForms are still broken (thus the issue is still open).

I don't think there are any "unknown" missing type forwarders, I had created structural tests which checked the attributes and documented all that were missing.

**Comment by Vino-Wang** [comment]
Verified with latest .NET 5.0 5.0.100-rc.1.20377.7 build, this issue is not reproducing, the controls' Tasks dialog can be opened normally, no error pops up.
