### ISSUE TITLE
[Accessibility] Keyboard focus is not clearly visible on "Categorized", "Alphabetical" and " Property Pages" for PropertyGrid control

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#3659]
* .NET Core Version: 
.Net SDK 5.0.100-rc.1.20378.13

* Have you experienced this same bug with .NET Framework?: 
Yes

 **More info**
1. The issue also can reduce when focus with mouse.

**Minimal repro:**
1. Extract “[PropertyGrid.zip](https://github.com/dotnet/winforms/files/4993278/PropertyGrid.zip)” and open it in VS.
2. Build and run the project.
3. Press "Right/Left" arrow to focus on  "Categorized", "Alphabetical" and " Property Pages".

**Expected behavior:**
Keyboard focus should clearly visible on "Categorized", "Alphabetical" and " Property Pages".

**Actual behavior:**
While navigating through Keyboard that focus is not clearly visible on "Categorized", "Alphabetical" and " Property Pages".
![RunTime](https://user-images.githubusercontent.com/38325459/88770358-45940800-d1b0-11ea-9bc8-8db96af74300.gif)

**Comment by merriemcgaw** [comment]
If we add dotted box to ToolStrip base class we should pick the change up.

**Comment by merriemcgaw** [comment]
.NET 6.0 issue now.

**Comment by Jessie-Zhang01** [comment]
The brightness contrast of controls boundary line is less than 3:1 on "Categorized", "Alphabetical" and " Property Pages" for property page. Please see following details:

**PropertyGrid:**(Blue, Dark, Light VS themes have same results )
![image](https://user-images.githubusercontent.com/45864649/94221779-5cd84300-ff1e-11ea-92bb-25714a904e21.png)

**Properties window:**
Blue theme:
![image](https://user-images.githubusercontent.com/45864649/94223458-98750c00-ff22-11ea-9755-8f52f3cb156e.png)
Light theme:
![image](https://user-images.githubusercontent.com/45864649/94222176-441c5d00-ff1f-11ea-9da3-e748164b67c4.png)
Dark theme: The brightness contrast of the control boundary line is greater than 3:1. But it is difficult to distinguish between focused and unfocused states.
![image](https://user-images.githubusercontent.com/45864649/94223200-e3425400-ff21-11ea-9d05-4d0d43e02897.png)

**Comment by SergeySmirnov-Akvelon** [comment]
Hi @merriemcgaw. Could you please clarify if we should change colors within this task? If so, should we add a dotted box for ToolStripButtons?

**Comment by merriemcgaw** [comment]
It looks like we've got a couple things we need to do here:

1. Update the PropertyGrid here to make sure selection rectangle meets the requirements with default settings.
2. The dark mode selection color is likely a VS specific thing. We need to investigate and get that fixed for our VS customers.
3. Find where we need to update VS or Framework to get VS PropertyBrowser to meet the criteria in all of its different modes and get those changes scheduled.

Let me know what your investigation uncovers offline and we'll get the right issues created in the right places to make sure both our WinForms runtime customers and our VS customers have the most accessible experience possible.

**Comment by merriemcgaw** [comment]
Since we have the information from our SME that color contrast on button outline is not required, it means that buttons in a ToolStrip are also not required to follow this rule. Visual Studio is able to use our APIs to create an accessible color scheme so we can be confident that it is possible to create the desired contrast experience with a bit of property setting. I think we can close this issue now.

**Comment by merriemcgaw** [comment]
I may have spoken too soon. We do need to do something by default in the PropertyGrid so that a user knows when there is focus on either of the two ToolStrip buttons. It doesn't necessarily need to be a border, but some visual indicator that one is in focus but not selected, or one is in focus and selected. Because today the user can't distinguish between the focused button and the control that is chosen (Alphabetical/Categorized). I will chat with Dante and Guy internally about how we want to accomplish this. I am adding you to the appropriate Teams site internally and we can follow up directly with the right people.
