### ISSUE TITLE
The description of 'Document' property  of PageSetupDialog control displayed incorrect

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#3822]
* .NET Core Version: 
.NET 5.0.100.rc1.1.20451.10

* More info:
The issue can reproduce on PrintDialog/PrintPreviewControl/PrintPreviewDialog contorls.

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
The description of 'Document' property  of PageSetupDialog control displayed incorrect, can't provide useful info for user.

**Expected behavior:**
The description of 'Document' property  of PageSetupDialog control displayed correct.

**Minimal repro:**
1. Create a .NET Core winforms project with a PageSetupDialog control.
2. Observer the  description of 'Document' property of pageSetupDialog1 control in the properties window.
![Issue8](https://user-images.githubusercontent.com/38325459/91960185-27d03a80-ed3c-11ea-82ae-ddedccab7cd8.png)

**Comment by RussKie** [comment]
These classes belong to BCL: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Drawing.Common/src/System/Drawing/Printing/PrintDocument.Windows.cs

**Comment by RussKie** [comment]
@Zheng-Li01 could you please re-test against an RC2 build?

**Comment by Zheng-Li01** [comment]
@RussKie, verified the issue with latest .NET 5.0.100-rc.2-20467.7, the issue still can reproduce.

**Comment by merriemcgaw** [comment]
@JeremyKuhne we should consider fixing this now 😄

**Comment by elachlan** [comment]
Narrowed it down. The issue is that `System.Drawing.Common`'s version of the `SRDescriptionAttribute` is calling `SR.Format` instead of `SR.GetResourceString`. If I replace it, it fixes the issue. Can anyone see any issues me submitting a PR changing it?

https://github.com/dotnet/winforms/blob/43c5f2b3ea81496793f0b14ae5d28877f593bfeb/src/System.Drawing.Common/src/SRDescriptionAttribute.cs#L9-L29

https://github.com/dotnet/winforms/blob/43c5f2b3ea81496793f0b14ae5d28877f593bfeb/src/System.Windows.Forms/src/SRDescriptionAttribute.cs#L10-L31

**Comment by Philip-Wang01** [comment]
Verified this on .NET latest build: 8.0.100-rc.1.23375.11, issue was fixed. The description of 'Document' property of PageSetupDialog control displayed correct.
![image](https://github.com/dotnet/winforms/assets/86937911/a0656577-ecf3-4897-b5ff-60fa5afce877)

**Comment by Nora-Zhou01** [comment]
Verified with .NET SDK 8.0.100-preview.7.23376.3 test pass build, this issue was fixed, test result same as above.
