### ISSUE TITLE
Op wants to display ContextMenuStrip's items in multiple columns

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#3836]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/496005/op-wants-to-display-contextmenustrips-items-in-mul.html)._

---
<p>https://social.msdn.microsoft.com/Forums/vstudio/en-US/de6834c3-5620-483b-8e5a-a9e44d51274d/contextmenustrip-with-multiple-columns?forum=vbgeneral</p><p></p>

---
#### Alex Li [MSFT] on 3/18/2019, 01:54 PM: 

Op wants to display ContextMenuStrip's items in multiple columns

#### Jane Wu [MSFT] on 3/18/2019, 04:30 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Feedback Bot on 9/4/2020, 07:00 AM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it for community input</p>

**Comment by Olina-Zhang** [comment]
This issue is from SuggestionTicket, and Merrie suggests file an issue in here.

Description for this issue from that website:
_with ContextMenu we have MenuItems, which have property called Break. Setting this property to True will display this item in a new column of that ContextMenu.

With ContextMenuStrip we have ToolStripItems, wich do'nt have a property called Break.

My question: How to use ContextMenuStrip, to display it's items in multiple columns? And if possible, preferably automatically?_

**Comment by merriemcgaw** [comment]
Closing due to lack of traction on the issue.
