### ISSUE TITLE
  Dotnet core 3.1 windows forms cannot run on win7 virtual machine after being packaged into a single file

### ISSUE THREAD

**Issue by toolgood** [dotnet/winforms#3889]
.NET Core Version:  3.1.402
  

**Problem description:**   Dotnet core 3.1 windows forms cannot run on win7 virtual machine after being packaged into a single file
 
**Expected behavior:**

![QQ截图20200912224438.png](https://i.loli.net/2020/09/12/L7CIqkvml8DHYNR.png)

**Comment by toolgood** [comment]
---------------------------
ToolGood.Decompression_HD_any.exe - 系统错误
---------------------------
无法启动此程序，因为计算机中丢失 api-ms-win-crt-runtime-l1-1-0.dll。尝试重新安装该程序以解决此问题。 
---------------------------
确定   
---------------------------

**Comment by weltkante** [comment]
This is a system component and not deployed by .NET Core, are you sure you have installed all updates  for Windows 7 and installed all documented [dependencies](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31#dependencies)? In particular the [MSVC 2015](https://www.microsoft.com/en-us/download/details.aspx?id=52685) runtime is required.

Also note that .NET Core 3.1 no longer officially supports Windows 7 according to that page. Since .NET Core 3.0 is also out of support, Windows 7 can be considered out of support for .NET Core 3.x (just FYI, not saying it doesn't work, just that it isn't officially supported)

**Comment by RussKie** [comment]
Thank you @weltkante, I raised this internally.
