### ISSUE TITLE
ListView is in virtual mode throws IOE when user disables checkboxes

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4042]
- .NET Core Version:
.NET SDK 5.0.100-rc.1.20420.14

- Have you experienced this same bug with .NET Framework?:
Yes

**Minimal repro:**

1. Create application with ListView in virtual mode
2. Enable checkboxes
3. Disable checkboxes
4. Or use attached [WindowsFormsApp3.zip](https://github.com/dotnet/winforms/files/5310459/WindowsFormsApp3.zip)

![ListView - checkboxes](https://user-images.githubusercontent.com/23376742/94779836-360f8600-03d0-11eb-87d7-654cf082fd46.gif)
**StackTrace:**
```
   at System.Windows.Forms.ListView.CheckedListViewItemCollection.get_Count()
   at System.Windows.Forms.ListView.set_CheckBoxes(Boolean value)
   at WindowsFormsApp3.Form1.Button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
```

**Expected behavior:**
Checkboxes should be disabled without exceptions

**Actual behavior:**
'Cannot access the checked items collection when the ListView is in virtual mode.' exception is displayed

**Comment by jbhensley** [comment]
The problem would appear to be here:

https://github.com/dotnet/winforms/blob/6dfe634b722120b575cb6ac9904e6d95cc161894/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L471-L482

Since `CheckedItems` cannot be used in conjunction with virtual mode, it would seem that the fix would be changing line 471 to `if (CheckBoxes && !VirtualMode)`.

I made this change and validated that the error went away with a new unit test. However, there is another unit test that specifically ensures this exception is thrown:

https://github.com/dotnet/winforms/blob/6dfe634b722120b575cb6ac9904e6d95cc161894/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs#L4429-L4442

@SergeySmirnov-Akvelon this test was added in dbd0a038c67bad1fec15d5db5309134c3a7a8719. Was this like a bulk load of existing tests or...?

**Comment by RussKie** [comment]
Thank you @jbhensley for spotting this and your investigation. 
It is plausible that some bug have managed to sneak in, as while updating the `ListView` functionality (primarily for the accessibility scenarios) we overlooked the virtual mode scenario, and had to close the gaps very late in the .NET 5.0 dev cycle. To be fair (though not trying to excuse ourself) `ListView` has a very broad functionality, and permutations of its various properties (like `CheckBoxes`, `VirtulaMode`, `View`, etc.) make it very hard to keep track of everything.

Would you mind submitting a fix?
Also does this bug affect your apps and/or blocking your from migrating to any .NET version?

@SergeySmirnov-Akvelon holler if you have any thoughts.

**Comment by jbhensley** [comment]
I submitted a PR with the changes.

We have an app that's part WinForms and part WPF that's being converted to full WPF, but slowly. In the meantime, we'd like to migrate to .NET >= 5

**Comment by VinoWang01** [comment]
Verified this issue on .NET SDK 7.0.100-alpha.1.22060.5, this issue was fixed, there is no exception when disable or enable CheckBoxes property in virtual mode.
![Fixed](https://user-images.githubusercontent.com/90816462/148878754-5480212f-cbe2-4467-bd9b-9c5af0dcedb4.gif)
