### ISSUE TITLE
DataGridView Memory Leaks

### ISSUE THREAD

**Issue by RioInf** [dotnet/winforms#4129]
* .NET Core Version: 5.0 rc1, 5.0 rc2 and Final 5.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
When the app run, per cell click in DataGridView even at VerticalScrollBar, when i looked at Task Manager, the app drains memory 10 to 30 MB per click before automatic reclaim at 590 MB

**Expected behavior:**
Memory should not leaks

**Minimal repro:**
Download Sample Project
https://drive.google.com/file/d/10HW6VtUgY2vfrWV0YG71ozZ_v5wTx5cp/view?usp=sharing
Download SQL Server 2000 Sample DB (Northwind)
https://github.com/Microsoft/sql-server-samples/tree/master/samples/databases/northwind-pubs
Download Sample Pictures (From Windows 7 Sample Pictures)
https://drive.google.com/file/d/1o_YNwXmkZjSzvcxCHai0DdJxgajc07W0/view?usp=sharing

1. Create a winforms app. Add to Form1 a DataGridView, a PictureBox and two Button (browse and save) control
2. Form1 Load method, get data from Northwind Categories table with a DataTable using SqlDataReader and bind it to DataGridView.
3. Form1 Load method, set DataGridImageColumn.ImageLayout = Zoom at picture column, DataGridView.AutoSizeRowsMode =DisplayedCellsExceptHeaders
4. Button Browse Click method, using OpenFileDialog to get the image from Libraries\Picture\Sample Pictures such as Hydrangeas, Lighthouse etc with size < 1MB.
5. Button Save Click method, add some new records using SqlCommand
6. Run the app, click a cell in DataGridView or at VerticalScrollBar and take a look at Task Manager
7. Memory not leaks with default image from Northwind Catagories table. It leaks when DataGridView shows data with new JPEG Image

![BUG](https://user-images.githubusercontent.com/73053504/98507414-1d787280-2290-11eb-8402-ba2e17f901a8.png)

**Comment by kirsan31** [comment]
@RioInf  can you use bug report template pls?

<details><summary>bug report template</summary>

```

<!-- Read https://github.com/dotnet/winforms/blob/master/docs/issue-guide.md -->

* .NET Core Version: 
<!-- e.g. 3.0 Preview1, or daily build number, use `dotnet --info` -->

* Have you experienced this same bug with .NET Framework?: 
<!-- Yes / No -->

**Problem description:**

<!--
    Describe the current behavior, what is wrong or not working as expected.
    Provide as much information as possible, including callstack for crashes/exceptions, screenshots or animations.
  -->


**Expected behavior:**


**Minimal repro:**

```

</details>

**Comment by RussKie** [comment]
Please provide a sample project.

**Comment by RioInf** [comment]
> 
> 
> Please provide a sample project.
a sample is provide @RussKie 
sorry it's late because I'm so busy

**Comment by RioInf** [comment]
> 
> 
> Please provide a sample project.

**Comment by RioInf** [comment]
@RussKie 
a sample is provided
sorry it's late because I'm so busy

**Comment by RussKie** [comment]
@RioInf thank you, will have a look.

**Comment by weltkante** [comment]
> the app drains memory 10 to 30 MB per click before automatic reclaim at 590 MB

Does the memory remain stable after that, even if you repeat the process? If so then its technically not a memory leak, which would be characterized by unbounded growth until the process crashes.

If the memory is bounded then it can still be desireable to optimize this, especially if Desktop Framework had a much smaller footprint, but making optimizations requires a very different approach than identifying and fixing a memory leak.

**Comment by RussKie** [comment]
I tried to restore the provided database but it looks like the backup consists of two files, but only one was provided:
![image](https://user-images.githubusercontent.com/4403806/101712037-ceb93500-3ae8-11eb-8543-03d445cc57b4.png)

**Comment by RioInf** [comment]
> 
> 
> > the app drains memory 10 to 30 MB per click before automatic reclaim at 590 MB
> 
> Does the memory remain stable after that, even if you repeat the instructions without restarting? Or does this limit of 590 MB keep increasing if you keep repeating the instructions? If it remains stable after some point then its technically not a memory leak, which would be characterized by unbounded growth until exceptions start to happen or the process crashes.
> 
> If the memory usage is bounded then it can still be desireable to optimize this, especially if Desktop Framework had a much smaller footprint, but making optimizations requires a very different approach than identifying and fixing a memory leak.

Memory consumption returns to normal after automatic claim, but if you repeat the same steps, the same thing happens. Sometimes it can be more than 600MB

**Comment by RioInf** [comment]
> 
> 
> I tried to restore the provided database but it looks like the backup consists of two files, but only one was provided:
> ![image](https://user-images.githubusercontent.com/4403806/101712037-ceb93500-3ae8-11eb-8543-03d445cc57b4.png)

@RussKie  I'm sorry about that. You can use any northwind database. I have provided the northwind & sample pictures link to try the project

**Comment by RussKie** [comment]
> 7\. Memory not leaks with default image from Northwind Catagories table. It leaks when DataGridView shows data with new JPEG Image

I don't think this is entirely correct - there is an observable memory consumption with the default images provided in the database.
![dgv-scroll-memory2](https://user-images.githubusercontent.com/4403806/102308189-3de7cb00-3fba-11eb-9b18-06883987e523.gif)

The growth is not as prominent because images are small, only 10K or so, whilst the custom images you load are around 550-600K. Unpacked into bitmaps they take MB of memory.

You can also see there are drops, where the memory is being released or the GC kicks in and collects some of those stray images:
![image](https://user-images.githubusercontent.com/4403806/102308061-eba6aa00-3fb9-11eb-96bf-1eb386e36632.png)


With the big images the consumption is significantly more pronounced (with added large images):
![image](https://user-images.githubusercontent.com/4403806/102308153-26104700-3fba-11eb-9004-f844a4a23132.png)
![image](https://user-images.githubusercontent.com/4403806/102308896-b56a2a00-3fbb-11eb-9579-7fa4f0bc6891.png)


I've run the sample on net472, and observed a similar behavior - i.e. growth in memory consumption, and then drops. Though the peaks and falls are significantly tighter and constrained:
![image](https://user-images.githubusercontent.com/4403806/102308792-85bb2200-3fbb-11eb-83f5-456e675eabea.png)


I was unable however to observe any unconstrained growth. 


This said, the `DataGridView` can do with a better implementation of image handling, but since this is an existing behaviour I'm marking it as up for grabs.

**Comment by elachlan** [comment]
@merriemcgaw I think this could probably be closed as Russkie pointed out there is no memory leak. Another issue should be created for the "better implementation of image handling" but Its unclear what needs to be done.

**Comment by merriemcgaw** [comment]
Done!
