### ISSUE TITLE
MyApplication_Startup and MyApplication_Shutdown are not executed in Windows Forms project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#4183]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/MyApplication_Startup-and-MyApplication_/1235910?preview=true)._

---
[severity:It's more difficult to complete my work]
The following events:
- MyApplication_Startup
- MyApplication_Shutdown
are not executed in Windows Forms project (.Net 5), even if windows application framework is activated.

---
#### Feedback Bot on 10/29/2020, 02:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Amy Li [MSFT] on 10/29/2020, 04:25 PM: 

<p>Hi customer,<br>
Thank you for your feedback ticket.<br>
In order to investigate this issue further, could you please provide a sample app for us?</p>

####  on 11/1/2020, 03:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Amy-Li03** [comment]
### .NET Core Version:
.NET SDK 5.0.100-rtm.20515.8
### Have you experienced this same bug with .NET Framework?:
No

## Problem description:
Startup and Shutdown Events are not executed when Startup object is Form1, they are executed if Startup Object is Sub Main.

## Expected behavior:
Startup and Shutdown Events should be executed when Startup object is Form1. 

## Minimal repro:
[DemoApp.zip](https://github.com/dotnet/winforms/files/5473327/DemoApp.zip)

1, Create a WinForms core (VB) project.
2. Right click Properties in solution, then change Startup object from **Sub Main** to **Form1**.
3. Add MyApplication_Shutdown and MyApplication_Startup events in ApplicationEvents file.
4. Build and run the project.

**Comment by KlausLoeffelmann** [comment]
This is a known issue.
Project System (namely the WinForms Project Properties Designer) isn't currently able to change the Start Form interactively in the UI. This needs to be done manually. Also, the start object in vbproj must always stay "Sub Main" - which is not the case in the sample.

* So, to change this, put "Sub Main" back as the start object in the .vbproj file.
* in _Application.Myapp_ change `<MainForm>` to the desired form.
* Save the file, to generate the required code changes in to _Application.Designer.vb_ (the code generator automatically kicks in on _Save_).

That should do the trick for now.

I am closing this for now. If there are any follow up question, feel free to reactivate this issue!
