### ISSUE TITLE
Windows Forms App (.NET) .NET5.0 SkiaSharp throws Attempted to read or write protected memory

### ISSUE THREAD

**Issue by CBrauer** [dotnet/winforms#4261]
# Issue
I have built a Windows Forms App (.NET) using .NET 5.0 rc2 and SkiaSharp. It is throwing the error: “Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”

# General

I have put my reproducible solution on GitHub at: https://github.com/CBrauer/TestSkia
I hope you guys can use this complete solution to fix the error.

# Environment
Microsoft Windows 10 Enterprise, version 10.0,19042 Build 19042
Microsoft Visual Studio Professional 2019 Preview Version 16.9.0 Preview 1.0
.NET 5.0 rc2

Charles

**Comment by RussKie** [comment]
@CBrauer I can't see any code which directly belongs to Windows Forms, the issue appears to be in the SkiSharp code:
![image](https://user-images.githubusercontent.com/4403806/100053434-2b271e00-2e74-11eb-9da0-4ec5660e9445.png)

You need to raise to the SkiSharp maintainers. If it can be demonstrated the issue is caused by the Windows Forms runtime we'll investigate.
