### ISSUE TITLE
Windows Forms Designer doesn't use an assigned Designer Type in DesignerAttribute

### ISSUE THREAD

**Issue by Pilzinsel64** [dotnet/winforms#4304]
* .NET Core Version: 
5.0

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The Windows Forms Designer seems to not be able to load the designer type that's given in a DesignerAttribute of any custom Control.

This does load the default designer:
![image](https://user-images.githubusercontent.com/23138465/100709153-e2a8bc80-33ad-11eb-8ef5-e9340bb5f38a.png)

This doesn't load any designer (control acts like a component):
![image](https://user-images.githubusercontent.com/23138465/100709176-eccabb00-33ad-11eb-9e91-e729298e7b9a.png)

This does load only the given baseDesignerType:
![image](https://user-images.githubusercontent.com/23138465/100709211-fb18d700-33ad-11eb-9f79-ee030b59f06e.png)

**Expected behavior:**
The given designerType should be used and not the baseDesignerType (like in .NET Framework) to use the extended Designer for this control.

**Minimal repro:**
1. Create a new project solution.
2. Create two new Windows Forms projects (targeting .NET 5).
3. In the second project create a custom control (or UserControl, that doesn't matter).
4. Create a designer, put in some custom codes, and reference it like in the screenshots above.
5. Compile the project.
6. Reference the project to the first project.
7. Create a new Windows Form and add your custom control from the Toolbox.
8. You can now see the behavior ...

**Notes**

I am porting all my custom control libraries with hundreds of custom user controls and components to .Net 5 and all of them did work in .Net framework 4.8. And of all controls the designer attribute gets ignored or behaves like described above.

Please give me a feedback if this is a bug and if there is a workaround or what I can do to get my custom designer working again. Thanks!

**Comment by merriemcgaw** [comment]
This is something we're currently working on and will be sharing how-to docs in the coming VS Preview versions.

**Comment by Pilzinsel64** [comment]
Thannk you very much for your response. Nice to hear, that's in progress/paned.  So, I will wait until the next VS Preview and try again with the given instructions.

**Comment by StevenBonePgh** [comment]
I noticed that the `EditorAttribute` also works inconsistently in the designer for .NET Core vs the .NET Framework. [I created a Feedback Item for this earlier today](https://developercommunity.visualstudio.com/t/net-5-winforms-designer-ignores-systemcomponentmod/1398197). 

In the Core/NET5 designer, it ignores the specified Editor and uses the base class variant instead. The property is declared as:
```
[System.ComponentModel.Editor("BrightIdeasSoftware.Design.OLVColumnCollectionEditor", "System.Drawing.Design.UITypeEditor")]
public new ListView.ColumnHeaderCollection Columns
```
My money is on the .NET Core designer's reflection on the control does not pick up the `EditorAttribute` on the 'new' property like the .NET Framework's editor did. I've used this approach a handful of times to get custom editors on top of pre-existing properties and have seen this done in more than just this control.

Is the above instance related to this github issue? If not, should I open another issue here or is the Developer Community Feedback tool sufficient?

**Comment by Pilzinsel64** [comment]
You're right, the EditorAttribute also doesn't work correctly.

> I've used this approach a handful of times to get custom editors on top of pre-existing properties and have seen this done in more than just this control.

DotNetBar is a big collection of useful Controls and Components for Windows Forms. It use both attributes for many controls. And they prevents me from porting DotNetBar as well as my projects that uses DotNetBar. Even if it works at run-time, it just doesn't load the designer correctly at design-time.

**Comment by StevenBonePgh** [comment]
[I updated the Feedback Item for this earlier today](https://developercommunity.visualstudio.com/t/net-5-winforms-designer-ignores-systemcomponentmod/1398197). Turns out that the EditorAttribute is also ignored for overridden virtual properties and even properties that are declared on the type directly. I'm not sure how existing built-in controls work - the .NET 5's ListView's Columns collection specifies `[Editor("System.Windows.Forms.Design.ColumnHeaderCollectionEditor, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", typeof (UITypeEditor))]` that seems to work just fine in the designer.

**Comment by davi1td** [comment]
Hi, checking in on the excellent submission by @StevenBonePgh, is there a reason there has been no update here since April 15th? 
And its still broken in vs2022, .net 6.
Regards

**Comment by merriemcgaw** [comment]
@davi1td Actually that's a great question! Keep an eye out on the .NET Blogs starting later this month. We'll be doing a new series of blogs to explain the new Out-of-process architecture for the .NET WinForms Designer and then some blogs to describe how you then go and create controls and designers in this new model.

**Comment by davi1td** [comment]
Thanks for the update!

**Comment by jmarioiii** [comment]
@merriemcgaw is there any update on this?  I have a library of user controls that rely on custom UITypeEditors for design mode configuration and when we ported over from Framework 4.8 to 6.0 we lost all functionality.

**Comment by merriemcgaw** [comment]
Keep an eye out for a blog from @KlausLoeffelmann later this month. It will give you a basic idea of what the new architecture is and why it has to be the new way. We're working on future blog posts to give much more detail on how to develop controls and their designers.

**Comment by jmarioiii** [comment]
Thanks @merriemcgaw.  Our entire UI development foundation relies upon custom designers and we are at a critical blocakage trying to gauge rework efforts and expense recreate this functionality in 6.0.   @KlausLoeffelmann can you give us a preview of the changes to the way custom UITypeEditors will be implemented in the future?  More importantly, will they be implemented using property attributes?:

`[Description("Click to edit Foo"), Category("_Foo"), Browsable(true), Editor(typeof(FooCustomPropertiesEditor), typeof(UITypeEditor)), TypeConverter(typeof(ExpandableObjectConverter)), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]

public FooCustomProperties CustomProperties { get;set; }`

I think everyone following this issue is looking for resolution ultimately, but would settle for some basic information in the interim.  Any info would be helpful as we are literally dead in the water due to this item.

Thanks in advance.

**Comment by gitskotjuko** [comment]
If I see it right, this is about designer SDK mentioned in this thread https://github.com/dotnet/winforms/issues/4887. 
Looks to me as a serious obstacle on porting from Framework to 6.0.

**Comment by KlausLoeffelmann** [comment]
Please take a look [at this blog](https://devblogs.microsoft.com/dotnet/state-of-the-windows-forms-designer-for-net-applications/), to read about the background of the new designer architecture.

For designers to work in .NET (and because of the reasons stated in that blog), a redesign for control designers is necessary. Depending on the scenarios, it might be as easy as recompiling against the SDK, when you show custom UI (editors), there are bigger changes needed.

At this time, we have the [Winforms Designer Extensibility SDK](https://www.nuget.org/packages/Microsoft.WinForms.Designer.SDK) in a prerelease version. 
We expect a blog post about this finalized around start of February. Around then, we will also publish the first final 1.0 release of this SDK.

**Comment by KlausLoeffelmann** [comment]
Also, for folks who are interested in early adaptation of the SDK (which is still in prerelease, but we don't expect breaking changes at this point!), take a look here:

https://github.com/KlausLoeffelmann/NetControlDesigners

**Comment by RussKie** [comment]
> But the thing where i hangs on is that the event listeners still are not working in the control designers.

Can you please file a new issue with a sample repro and as much info as possible. Thank you.

> Do you have a documentation/blog about how to debug a control designer?

It is coming, but our timeline has sadly stretched beyond our expectations. Apologies.

**Comment by stanko75** [comment]
Hello, 

can you please confirm if we gonna need NuGet packages in order to show our custom controls in the Toolbox? Is there a way to keep them always there, without installing them every time we start a new project?

Thanks in advance.

**Comment by merriemcgaw** [comment]
Hi @stanko75 at this point, yes you will want to use a NuGet package to get your controls on the ToolBox. And yes, there is a way to put them in a location such that they don't need to be added to every new project you create. We're working on the docs ourselves at the moment, but we are following the same patterns as the xaml designer, and I can point you to their docs for [unreferenced NuGet packages](https://github.com/microsoft/xaml-designer-extensibility/blob/main/documents/toolbox-population.md#toolbox-items-from-unreferenced-nuget-packages). We will be creating similar docs for WinForms soon.

**Comment by rashid201143** [comment]
I noticed that the EditorAttribute also works inconsistently in the designer for .NET Core vs the .NET Framework. [I created a Feedback Item for this earlier today](https://developercommunity.visualstudio.com/t/net-5-winforms-designer-ignores-systemcomponentmod/1398197).

In the Core/NET5 designer, it ignores the specified Editor and uses the base class variant instead. The property is declared as:
`[System.ComponentModel.Editor("BrightIdeasSoftware.Design.OLVColumnCollectionEditor", "System.Drawing.Design.UITypeEditor")]
public new ListView.ColumnHeaderCollection Columns`
My money is on the .NET Core designer's reflection on the control does not pick up the EditorAttribute on the 'new' property like the .NET Framework's editor did. I've used this approach a handful of times to get custom editors on top of pre-existing properties and have seen this done in more than just this control.

Is the above instance related to this github issue? If not, should I open another issue here or is the Developer Community Feedback tool sufficient?

**Comment by RussKie** [comment]
The .NET designer does not work the same way as the .NET Framework designer - i.e., the .NET designer is run out-of-proc, and thus requires a different control-authoring approach. You can find more information for this in [State of the Windows Forms Designer for .NET Applications](https://devblogs.microsoft.com/dotnet/state-of-the-windows-forms-designer-for-net-applications/) blog post.
Unfortunately the control authoring documenation was severly delayed, and @KlausLoeffelmann is working on it as a priority. In mean time yoy may be able to find some information to your questions in https://github.com/dotnet/winforms/discussions/7073 and in the @KlausLoeffelmann's repo https://github.com/KlausLoeffelmann/NetControlDesigners.

**Comment by KlausLoeffelmann** [comment]
Yes, that is correct!
