### ISSUE TITLE
Add MainMenu, ToolBar, and ContextMenu back and update them

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/winforms#4326]
**Is your feature request related to a problem? Please describe.**

MainMenu, ToolBar, ContextMenu and StatusBar should be readded to WinForms and updated to include features that weren't added to winforms so we can maintain backward compatibility to win32 controls.

here are some features that would need to be updated..
- Allow mdi children to contain separate mainmenus
- Update style to fit win 10 and possibly win 8
- Allow any control to be added to MainMenu, ToolBar, ContextMenu, StatusBar
- Allow Icons

**Describe the solution you'd like and alternatives you've considered**

I have already tried using plain win32 and mfc to replace winforms but find the libraries to either be too difficult to use or it uses c++ which I would rather use c or c#.

I am not sure what needs to be changed to do this
This implementation would be used to maintain backward compatibility with older windows operating systems.

**Will this feature affect UI controls?**

Yes
It would need supported by the designer

**Comment by RussKie** [comment]
These controls technically have been deprecated since .NET 2.0 (circa 2005) and have been removed from the VS Designer Toolbox. They are not coming back.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core#removed-controls

**Comment by Shadowblitz16** [comment]
@RussKie They were removed prematurely.
We don't have backwards compatible and native controls to replace these.

Not everyone wants custom drawing

please reopen this

**Comment by RussKie** [comment]
All these types weren't meant to be ported into .NET Core in the first place. It was a blunder on our side.
This types aren't coming back, sorry.

**Comment by Shadowblitz16** [comment]
No what's a blunder on your side is that fact we are forced to use custom rendered controls implemented in C# instead of native windows controls that are compatible with older versions of windows.

Not everyone wants custom rendered controls if that were the case we would use wpf.

**Comment by JensNordenbro** [comment]
@RussKie ; we also are experiencing friction with thirdparty needing this. For us the problem is not the removal of these components but the lack of control for using thirdparty. 
I guess in the end we will just replace these thirdparty dependencies. 

This "not full compatiblity" leads me however to ask the questions: 
1. Is there a roadmap for further component deprecation? 
2. Are there plans to do some (compatibity breaking but long-term nice) project reunion stunts on winforms?

**Comment by RussKie** [comment]
> 1. Is there a roadmap for further component deprecation?

I'm not currently aware of any plans to deprecate any more controls. But calls of this nature generally involve more than just the engineering team. 
If any more components will be made obsolete I fully expect our communication to be better and well in advance.



> 2\. Are there plans to do some (compatibity breaking but long-term nice) project reunion stunts on winforms?

Can you please clarify the question?

**Comment by JensNordenbro** [comment]
1. ok
2. WinForms is based upon GDI which is not HW accelerated fully (since Vista days although improved with Win7 https://docs.microsoft.com/en-us/windows/win32/direct2d/comparing-direct2d-and-gdi ). 
Considering 
  + Few WinForms application developers interact with GDI directly and instead using GDI+ 
  + WinUI3 enables WIn32-interaction 
  + Major versions (even minor) of .NET has historically broken much thirdpart support (This issue etc ) 
  + Major versions of .NET are expected to break compatibility for the sake of performance / excellence  

..maybe it is time to layer WinForms on top of WinUI3 or perhaps layer GDI on top of Direct3D so that WinForms is ensured progression within Windows without being an afterthought. 

That was my reunion stunt :)

**Comment by rickbrew** [comment]
FYI, help may be on the way, #5368
