### ISSUE TITLE
Documentation for ListControl.SelectedValue is misleading.

### ISSUE THREAD

**Issue by LethiferousMoose** [dotnet/winforms#4327]
The documentation for `ListControl.SelectedValue` is misleading, it does not explicitly call out that a data manager is required for it to return a value:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listcontrol.selectedvalue?view=net-5.0

> An object containing the value of the member of the data source specified by the ValueMember property.

This makes it sound like all you need to do is have a `ValueMember` provided to the control, but if look at the code for `ListControl` you can see it needs both a `ValueMember` AND a `DataManager`:

```c#
get
{
    if (SelectedIndex != -1 && _dataManager != null)
    {
        object currentItem = _dataManager[SelectedIndex];
        return FilterItemOnProperty(currentItem, _valueMember.BindingField);
    }

    return null;
}
```

Although the docs do say "data source" that is rather vague and open to interpretation, if something is required for a feature to work, it should be called out.

**Comment by weltkante** [comment]
The `_dataManager` is a private variable and an implementation detail of the list control, which should not appear in the documentation. I don't know what that `DataManager` is you are talking about, I cannot see any such property.

> Although the docs do say "data source" that is rather vague and open to interpretation, if something is required for a feature to work, it should be called out.

I don't follow your argument, data sources are a basic concept in WinForms and the `DataSource` property used for it is even the exact same term as the concept. Sure, you can be more explicit and use the camel-case property name instead of referring to the concept, but thats a real minor difference and I don't agree with it "being rather vague and open to interpretation".

**Comment by LethiferousMoose** [comment]
`ListControl` does not require the `DataSource` to be set. And if do you set it, according to the documentation for `DataSource`:
> When the DataSource property is set, the items collection cannot be modified.

So if you wanted to be able to add/delete from a `ListBox` or a `Combobox` on the fly, in memory, you cannot use `DataSource` and thus also `SelectedValue` always returns `null`. When I read this from `SelectedValue` in VS:

>Gets or sets the value of the member property specified by the ValueMember property.

That to me sounds like, if my `ListControl` contains items of type `X`, and `X` has a property called "A", I should be able to say `listBox.ValueMember = "A"` and the be able to call `SelectedValue` and have the property value of that object returned to be.

Now if you look at the docs for `ValueMember` these explicitly link to `DataSource`:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listcontrol.valuemember?view=net-5.0

Now if you're like me and you take the documentation in the designer to be accurate:
> Gets or sets the path of the property to use as the actual value for the items in the ListControl.

Doesn't sound like you need a `DataSource`, after all `DisplayMember` didn't need one, so why look at the docs site. So if you have `DisplayMember` and `ValueMember` set, and then `SelectedValue` does not work, it feels like something is broken in `SelectedValue` and the docs on that property don't make it immediately clear.

**Comment by weltkante** [comment]
> > When the DataSource property is set, the items collection cannot be modified.
>
> So if you wanted to be able to add/delete from a ListBox or a Combobox on the fly, in memory [...]

Actually you can, you modify the `DataSource`. What the documentation is saying is, if you specify a DataSource then _this_ is the collection that controls the items, and the Items collection of the control becomes readonly reflection of the DataSource. So no, you cannot edit the items collection, you have to edit the data source, since not all data sources are editable there is no general-purpose way to edit it through the items collection.

> Now if you're like me and you take the documentation in the designer to be accurate

It is accurate, it says you need a data source, 

> I personally thought:
>
> > An object containing the value of the member of the data source specified by the ValueMember property.
>
> Meant the an object in the Items collection.
