### ISSUE TITLE
Can't set size of the form

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#4330]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Cant-set-size-of-the-form/1278773)._

---
[severity:It's more difficult to complete my work]
Can't set size of the form.
Windows forms app.

Before form2. Show() command - it's OK - Size setted.

But just after step through form2. Show() - Width is setting up to 132.

( Maximize box = false;
Minimize box = false;
Border style = none; )

What can do for set Width of form2 to e.g. 50 value ?

Thanks.

Screenshot from VS - attached.

---
#### Feedback Bot on 12/7/2020, 04:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RussKie** [comment]
It is unclear how the form is designed, and what the expectations are. We need a sample app to triage.

**Comment by Jenna-Zheng** [comment]
**.NET Core Version:**
Core SDK 5.0.100

**Have you experienced this same bug with .NET Framework?:**
Yes

**Problem description:**
The Width does not work when the Width of the form is set to less than 132, the form is rectangle now.

**Expected behavior:**
The form should be square.

**Minimal repro:**
Create a core winforms project.
Add a form for project named Form2.
Add the below code for Form1 class.

**Comment by Mikhail-Semenenko** [comment]
Hello,

This code - doesn't work as expect.

frm2 object not resized to Size(50,50);

But if we set the Size just after frm2.Show(), - we will have expected size 50x50.

Why is it ?  Is this right solution?


And, by the way - BringToFront method  doesn't make sense because frm2 - it is Top level control.  

```
    public partial class Form1 : Form
    {

        Form2 frm2 = new Form2();

        public Form1()
        {
            InitializeComponent();
           
            frm2.BackColor = Color.Red;
            frm2.FormBorderStyle = FormBorderStyle.None;
            frm2.Size = new Size(50, 50);
            frm2.Location = new Point(15, 0);
            frm2.Show();

            //frm2.Size = new Size(50, 50);
        }
    |}
```

**Comment by merriemcgaw** [comment]
I'm interested to know the use case here? We'd be happy to evaluate a pull request about the issue if you would care to submit. Otherwise, I don't see this as a top priority bug. It's likely a requirement in the system that when you first create a top level form there is a minimum size. Once the form has been shown, then the restriction lifts.

**Comment by weltkante** [comment]
The use case is custom popups, tooltips etc. which people like to implement by using `FormBorderStyle.None` since it almost gets you there. Unfortunately little quirks like this require more low level overrides (and knowledge) to fully mimick Win32 behavior of popups/tooltips.

The technical reason for the observed behavior is that in order to create a popup window you need to set the `WS_POPUP` [window style](https://docs.microsoft.com/en-us/windows/win32/winmsg/window-styles), not doing this will cause the Win32 `CreateWindow` API to apply the minimum window size setting (`SystemInformation.MinWindowTrackSize`) which has the observed dimensions.

I'm not entirely sure what the design of `FormBorderStyle.None` is, depending on how you define it this can be classified as a bug in WinForms forgetting to set the `WS_POPUP` style.

There are at least two workarounds:
- override `CreateParams` and set `WS_POPUP` on your form to indicate to Win32 that you are creating a custom popup window

```csharp
protected override CreateParams CreateParams
{
    get
    {

        var cp = base.CreateParams;
        cp.Style |= unchecked((int)0x80000000); // WS_POPUP
        return cp;
    }
}
```

- set the form size in the `Load` event handler, which runs before displaying the form so it does not flicker, but after Win32 `CreateWindow` so the quirky constraint no longer applies

```csharp
public Form1()
{
    TopMost = true;
    FormBorderStyle = FormBorderStyle.None;
    BackColor = Color.Red;

    Load += delegate
    {
        Size = new Size(50, 50);
        Location = new Point(200, 200);
    };
}
```

**Comment by Mikhail-Semenenko** [comment]
The use case is quick access side-panel of tools.

Form Location is changing from -40 to 0 due pointing by mouse over 50x1050 side area.
I takes 4 step by 10 px on timer event.

_In my case - yes, it's not top priority bug._

_But just wanted to know it's a bug or a feature..._

I 've spent a lot of time trying to solve this issue, so I want to know:

"Changing a Size of Control is always must be after calling Show() ?  
Or this is solution for Forms only ?
Or, yet, setting the Size after Show() - this is workaround ?"

**Comment by weltkante** [comment]
> But just wanted to know it's a bug or a feature...

Its a quirk, some strange behavior for very specific settings. Like I said above, depending on how you argue, you can argue it being a bug, or you can argue it being outside of the design space WinForms provides.

> Changing a Size of Control is always must be after calling Show() ?

No, this only happens to forms, and only for `FormBorderStyle.None`. Other forms are _by design_ not allowed to become smaller (the system ensures there is enough space for the nonclient area).

> Or this is solution for Forms only ?

This problem, and thus this workaround, only applies to forms. Child controls are not affected by `MinWindowTrackSize` constraints, and in fact you are not allowed to set `WM_POPUP` on child controls.

> Or, yet, setting the Size after Show() - this is workaround ?

Yes this workaround would work too, but note that setting the size after `Show` does flicker. You need to set the size in the `Load` event if you want to avoid flicker, because that is one of the few events invoked between `Show` but before displaying the form.

**Comment by Mikhail-Semenenko** [comment]
It seems that this issue need to be closed, for now.

@weltkante  thank you for detailed explanations.

And thanks you all  guys for participation.

**Comment by RussKie** [comment]
Thank you @weltkante!

> ```cs
> public Form1()
> {
>     TopMost = true;
>     FormBorderStyle = FormBorderStyle.None;
>     BackColor = Color.Red;
> 
>     Load += delegate
>     {
>         Size = new Size(50, 50);
>         Location = new Point(200, 200);
>     };
> }
> ```

I suggest avoiding the event and use an override:
```cs
        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);

            Size = new Size(50, 50);
            Location = new Point(200, 200);
        }
```
