### ISSUE TITLE
Support DevExpress to release their WinForms component suite 

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/winforms#4502]
Alledgely, due to missing functionality in Visual Studio Windows Forms designer, DevExpress are blocked to release their components as stable; they only exists as ctp for now. 
**This hinders adoption of NET5 for many companies that rely on DevExpress component suite.** 

Please help them with what they need to enable many companies to move their applications from netfw to NET5! 

https://community.devexpress.com/blogs/ctodx/archive/2020/11/11/design-time-support-for-devexpress-winforms-controls-for-net-5.aspx

Please consult "Now the Bad News – Known Issues" where the following is desribed (among other info) 

![image](https://user-images.githubusercontent.com/9577365/105980866-af289c80-6095-11eb-99e5-b7ab9b6e3e12.png)

**Comment by kirsan31** [comment]
Oh, this is а sad news :( I was hoping that the biggest problem for user controls is the lack of documentation ...

**Comment by merriemcgaw** [comment]
Thanks for bringing this to our attention. We are actively working with DevExpress and our other partners to make sure everything is addressed and we have a full end to end experience. Here is a bit more details of what's going on under the covers:

Moving to .NET Core has required us as a team to rearchitect the designer. While we're not starting from scratch, there's a lot to do. Many, if not most, UserControls will work just fine with small tweaks. More complex ones, especially those requiring both design-time code and runtime code will need to make changes in the controls to work. We're finalizing the SDK for interacting with Visual Studio in your design-time code. Once that's done we will be offering the SDK and documentation so that all developers can work with it. We are directly engaged with the major 3rd party control developers to help them make the changes they need. 

The architectural change we're working on is to separate Framework code in the WinForms designer from Visual Studio and move it over to a dedicated .NET Core/.NET 5+ server process. We're rearchitecting because the power of Windows Forms is the WYSIWYG designer, and we know our developers want to use the new Core/.NET Windows Forms runtime improvements. 

For example, if a developer create a .NET app and wants to utilize the new ListView or TextBox improvements, we want to show those in the designer. Because VS (devenv.exe) is a .NET Framework process it knows nothing about the new properties of the .NET Core/.NET types. That's why we have to create a communication pipe between your runtime code and insert the associated .NET visual process into the window hierarchy of VS. The major challenge here is that the control's design time code needs to be separated from the control itself,  so that design time code runs in VS, while at the same time the design surface process runs under the .NET runtime.

A blog post with more details, and the documentation are coming soon.

**Comment by blackboxlogic** [comment]
A blog post with more details... coming soon.

If and when, please link to it from here.
