### ISSUE TITLE
Support IDragSourceHelper/IDragTargetHelper?

### ISSUE THREAD

**Issue by wjk** [dotnet/winforms#457]
These two interfaces are used to support enhanced drag-and-drop support, including (most importantly for me) the ability to specify a custom image to be displayed under the cursor during the drag. While this can be done in C# today by using COM interop, you have to roll your own `IDataObject` implementation to do so, as the default Windows Forms one does not support setting arbitrary COM-based private formats into the data object, per Windows requirements. Would it be possible to update the Windows Forms `DataObject` class to enable this? (It would be even better if there would be higher-level code added to obviate the need to do custom COM interop to use thesee features, but I do not know what the API design for that would look like.) Thanks!

**Comment by weltkante** [comment]
Its not as simple as just implementing those two interfaces. As noted in the [IDropTargetHelper](https://docs.microsoft.com/en-us/windows/desktop/api/shobjidl_core/nn-shobjidl_core-idroptargethelper) documentation this requires support for `SetData` , which is not implemented in WinForms/WPF implementation of IDataObject (they only implement SetData on the .NET code path, not on the COM interface).

**Comment by merriemcgaw** [comment]
This isn't on our current roadmap, which is focusing on parity with .NET Framework. But it's certainly something we should consider in a future release.

**Comment by dreddy-work** [comment]
We have similar proposal for drag events showing underlying image here: https://github.com/dotnet/winforms/pull/6576.

**Comment by willibrandon** [comment]
Hi @wjk - I [added support for drag images and drop descriptions](https://github.com/dotnet/winforms/pull/6576), available since .NET 7 RC1. A sample program [can be found here](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.cs).

The drag image and drop description will be displayed if [`DragEventArgs.DragImageType`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.drageventargs.dropimagetype?view=windowsdesktop-7.0) is set to a value greater than `DropImageType.Invalid`. The drag image bitmap can be specified using the [`Control.DoDragDrop(Object, DragDropEffects, Bitmap, Point, Boolean)`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.dodragdrop?view=windowsdesktop-7.0#system-windows-forms-control-dodragdrop(system-object-system-windows-forms-dragdropeffects-system-drawing-bitmap-system-drawing-point-system-boolean)) method or by setting [`GiveFeedbackEventArgs.DragImage`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.givefeedbackeventargs.dragimage?view=windowsdesktop-7.0) property during the [`Control.GiveFeedback`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.givefeedback?view=windowsdesktop-7.0) event.

Please let me know if you get a chance to test it and if so, any feedback is appreciated. Thanks.

**Comment by wjk** [comment]
@willibrandon Cool beans! Thanks for letting me know!
