### ISSUE TITLE
TabControl control has transparent tab color by default

### ISSUE THREAD

**Issue by PavelAgurov** [dotnet/winforms#4601]
Hi,

When I put TabControl to the form I have transparent color of all tabs.
It’s not usefule - I have to change it to the “Control” color or something like this.
Can you set some color for tab pages by default?

BR,
Pavel

**Comment by RussKie** [comment]
Can you please elaborate? Screenshots and a repro will help better understand your issue.

This how it looks:
![image](https://user-images.githubusercontent.com/4403806/109228577-23ca3480-7816-11eb-9a6a-8c5dd60af576.png)

**Comment by PavelAgurov** [comment]
Background color of each page is Transparent. In WinForms it was SystemColor.Control.

**Comment by RussKie** [comment]
I don't believe there were any changes with the regards to `TabPage` background colours.

.NET 6.0:
https://github.com/dotnet/winforms/blob/f19545231fb36e430b74612ce303e781317636b0/src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs#L91-L105
.NET Framework 4.7.2:
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/TabPage.cs,127


.NET 6.0:
https://github.com/dotnet/winforms/blob/f19545231fb36e430b74612ce303e781317636b0/src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs#L486-L497
.NET Framework 4.7.2:
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/TabPage.cs,703

Please provide more information.

**Comment by weltkante** [comment]
The tab control is themed, it should not have relations to user specified colors at all (unless theming is disabled), since its being drawn by the theming engine. On some versions of Windows that includes a gradient background which is not possible to represent with a background color; frames are also drawing images.

If there's a regression you should probably try to describe what regressed. If this is a feature request, I don't think there's an easy way to make the theming incorporate custom colors.
