### ISSUE TITLE
A proposal to rework bolded dates collections to HashSet in MonthCalendar

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#4647]
I propose to change type of `_arrayOfDates`, `_annualArrayOfDates`, `_monthlyArrayOfDates` collections from `List` to `HashSet` in `MonthCalendar` to improve performance and clean up the code.
This change allows to make the implementation more logical and avoid extra checks of containing items. 

**User impact**
- Due to `HashSet` can't store duplicates of items, our collections will store only unique dates. So, if a user set some array with duplicate items to `BoldedDates` property, `HashSet` remove duplicates, and `getter` of `BoldedDates` property will return lesser collection to the user. This returned collection will be different from the initial user array.
But it looks logical to me, because we shouldn't store and show duplicate dates. **But we need to discuss any cases when we must store duplicate dates.**

**Will this feature affect UI controls?**
- No

**Is your feature request related to a problem? Please describe.**
- No

**Describe the solution you'd like and alternatives you've considered**
- Change type of `_arrayOfDates`, `_annualArrayOfDates`, `_monthlyArrayOfDates` collections from `List` to `HashSet` in `MonthCalendar`
- Rework related properties

**Comment by kirsan31** [comment]
Yes, it was the first that come in mind when I was looking at the code.
But possibility to add any number if equal ittems - stopped me from further thots :-(

**Comment by vladimir-krestov** [comment]
Yes, this is a continuation of our discussion in PR #4317. This proposal is not my original idea.
Here we need to decide if can we exclude duplicate dates from bolded dates collections. If so, we will use HashSet.

We need to consider any use cases that can ntervene this idea.

**Comment by kirsan31** [comment]
`_arrayOfDates` can be populate with duplicates only through [`BoldedDates`](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L258) because [`AddBoldedDate`](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L991) **not allowing them**. Duplicate dates in `_arrayOfDates` do not affect control in any way besides as [`RemoveBoldedDate` ](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L1560) will remove them one by one in each call. And the date will be bold until the last one is deleted. This is the only difference with `HashSet` that will remove bold on first call.

And I can't think of a practical useful use case for removing bold date in multiple passes instead of one :thinking:

**Comment by RussKie** [comment]
The proposal looks sensible to me 👍 

> 1. `_arrayOfDates` can be populate with duplicates only through [`BoldedDates`](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L258) because [`AddBoldedDate`](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L991) **not allowing them**.

This is probably something to look at, and close the gap.

**Comment by vladimir-krestov** [comment]
@Tanya-Solyanik, I would propose to close this Issue to reduce Backlog. If a customer have the issues, he/she will create a duplicate Issue. So if you agree, please close this.

**Comment by elachlan** [comment]
This issue is still open and should be closed based on the discussions here.

Here is a good summary of `HashSet<T>` vs `List<T>`: https://stackoverflow.com/questions/150750/hashset-vs-list-performance

Any other optimizations I can think of around these collections would be a breaking behaviour change. eg, using DateOnly or removing the use of the collections in favour of only using the bitmasks.

**Comment by elachlan** [comment]
@merriemcgaw this should probably be closed.

**Comment by merriemcgaw** [comment]
Thank you @elachlan for helping us clean up old issues, it's much appreciated!!
