### ISSUE TITLE
Enable double buffering by default for all forms and controls

### ISSUE THREAD

**Issue by ekolis** [dotnet/winforms#4654]
**Is your feature request related to a problem? Please describe.**

If I make an app and forget to turn on double buffering in my forms and controls, rendering can be laggy, especially if I handle the Paint event to do GDI rendering.

**Describe the solution you'd like and alternatives you've considered**

The DoubleBuffered property should default to true instead of false on all forms and controls.

There might be some downside to this but I'm not aware of it.

**Will this feature affect UI controls?**

Yes, this will impact UI controls.
There should be no change to the designer; I'm pretty sure it's smart enough to deal with changes to default values of properties already.
There should be no impact on accessibility.
There is no need for localization.

**Comment by weltkante** [comment]
I assume you just mean custom Forms and UserControls? I doubt the native controls wrapped by WinForms would like it if someone turned on double buffering behind their back.

> There should be no change to the designer; I'm pretty sure it's smart enough to deal with changes to default values of properties already.

The designer is definitely not going to handle changing default values well. If the user was explicitly setting it to `false` in the designer then it wouldn't have been serialized and "migrating" the project to .NET 6 (by opening it in Visual Studio) would discard the previous value and pick up the new default value..

Besides designer issues (which you can tolerate if you say thats what you want) you have another problem, name that it will make .NET Core 3 and .NET Core 5 applications run incorrectly on the .NET 6 runtime (if they are sensitive to this property changing behind their back). This may be more of an issue, though WinForms hasn't taken backward compatibility very literally in the past so may be willing to break it again.

---

To judge whether the benefits of this change outweight the compatibility issues it produces you might want to present some example for your claim of rendering being "laggy". In my experience WinForms works just fine if you code properly.

Note that if you do GDI rendering instead of WinForms `Graphics` (GDI+) rendering you are already off the standard guidance and can be expected to know what you are doing. If that involves turning on double buffering thats on you, WinForms should provide good defaults for GDI+ rendering because that is what is happening for the majority of users.

**Comment by merriemcgaw** [comment]
The team has discussed this and we're happy to make this property public, but we won't want to change the default. We'd also want to make sure there's a note on the documentation that it may not work in certain scenarios. We also may want to hide this from the PropertyGrid in VS, and mark this as an Advanced property.

**Comment by RussKie** [comment]
We can't change the defaults as it will be a breaking behavioural change. Besides double buffering only works if `UserPaint` and `AllPaintingInWmPaint` styles are enabled.

Secondly, I don't think we _can_ change the access modifier level - it will be a [binary breaking change](https://docs.microsoft.com/dotnet/standard/library-guidance/breaking-changes#binary-breaking-change).

I created a simple app in which a subclassed a `ListView`:
```cs
    public class MyListView : ListView
    {
        protected override bool DoubleBuffered
        {
            get => base.DoubleBuffered;
            set => base.DoubleBuffered = value;
        }
    }
```

Making `DoubleBuffered` property public irrecoverably breaks the app:
```
Application: SimpleWinForms.exe
CoreCLR Version: 6.0.21.10512
.NET Version: 6.0.0-preview.2.21105.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException: Derived method 'get_DoubleBuffered' in type 'SimpleWinForms.MyListView' from assembly 'SimpleWinForms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' cannot reduce access.
   at SimpleWinForms.Form1..ctor()
   at SimpleWinForms.Program.Main() in C:\Development\!Repro\4310-SimpleWinForms\SimpleWinForms\Program.cs:line 36
```

To avoid breaking all existing customers we'll need to introduce a new property, let's call it `EnableDoubleBuffer`.
Adding this property, whilst facilitating the requested functionality, will introduce a number of issues such as (but not limited to):
- API discoverability, and
- API coherency and ambiguity - i.e. "_When do I need to use `DoubleBuffered`, `SetStyle(ControlStyles.OptimizedDoubleBuffer, true)` or `EnableDoubleBuffer`?_".

Also a number of our controls that we build on top of Win32 Native Controls (e.g. from comctl32.dll) have `DoubleBuffered` properties decorated as `EditorBrowsable(EditorBrowsableState.Never)` to hide those from statement completion. We would need to do the same for the new property, which creates additional work with arguably little-to-no value-add.

With all of the above I can't see us advancing this proposal further.
