### ISSUE TITLE
Unable to cast object of type ‘System.IO.MemoryStream’ to type ‘System.Drawing.Color’ in .NET Core app

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#473]
* .NET Core Version:  .NET Core 3.0 Preview 3 3.0.100.10342 from Release branch
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
Unable to cast object of type ‘System.IO.MemoryStream’ to type ‘System.Drawing.Color’ in .NET Core app.

**Actual behavior:** 
An exception pops up, and the type isn't changed successfully.
![netcoreapp](https://user-images.githubusercontent.com/18568603/53230246-3bb7cc80-36c1-11e9-8a28-ef97b0d6968b.png)

**Expected behavior:**
No exception and the code execute successfully.
![frameworkapp](https://user-images.githubusercontent.com/18568603/53230274-45d9cb00-36c1-11e9-91a2-78abd6d24107.png)

**Minimal repro:**
1.	Launch VS and create a default.NET Core app.
2.	Add the following code to Form1.cs & Form1.designer.cs, then run the app(Or you can run the attached app directly).
[NETCoreApp.zip](https://github.com/dotnet/winforms/files/2893083/NETCoreApp.zip)
[FrameworkApp.zip](https://github.com/dotnet/winforms/files/2893085/FrameworkApp.zip)
   Form1.cs
        private void Form1_Load(object sender, EventArgs e)
        {
            //Set the format to "CustomFormat", then try to cast object of type 'System.IO.MemoryStream' to type 'System.Drawing.Color'
            Color c = Color.Black;
            Clipboard.SetData("CustomFormat", Color.Red);
            Object result = Clipboard.GetData("CustomFormat");
            c = (Color)result; // set the breakpoint at here

            //Set the format to DataFormats.StringFormat, then try to cast object of type 'System.String' to type 'System.Drawing.Color'
            //Color c = Color.Black;
            //Clipboard.SetData(DataFormats.StringFormat, Color.Red);
            //object result = Clipboard.GetData(DataFormats.StringFormat);
            //c = (Color)result;  // set the breakpoint at here

            //Set the format to "CustomFormat", then try to cast object of type 'System.IO.MemoryStream' to type 'System.String'
            //String s;
            //Clipboard.SetData("CustomFormat", "abc");
            //object result = Clipboard.GetData("CustomFormat");
            //s = (string)result;  // set the breakpoint at here
}
	
	Form1.Designer.cs
	private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.ResumeLayout(false);
        }

**Comment by weltkante** [comment]
There was a recent bugfix for issue #415 / PR #416 so this might already be fixed in master if it has the same root cause.

**Comment by zsd4yr** [comment]
@weltkante this issue was found when testing the bits in the release/3.0 branch which was snapped from master yesterday. So it should have the change you’re referencing.

**Comment by zsd4yr** [comment]
@joeErickson does this look like a regression from your work on the clipboard?

**Comment by zsd4yr** [comment]
@Vino-Wang What other types were placed on clipboard besides "Color"?

**Comment by zsd4yr** [comment]
@dreddy-work do you think we are missing converters?

**Comment by JoeErickson** [comment]
@zsd4yr @weltkante @Vino-Wang I just verified that the following test works with #415 and fails without it:
```
        [WinFormsFact]
        private void DataObject_Clipboard()
        {
            var color = System.Drawing.Color.Red;
            Clipboard.SetData("CustomFormat", color);
            var o = Clipboard.GetData("CustomFormat");
            Assert.Equal(color, o);
        }
```
I also forked dotnet/winforms master and verified the fix is there.

**Comment by JoeErickson** [comment]
@zsd4yr @dreddy-work 

It should be possible to put any serializable .NET object on the clipboard with a custom format.

The clipboard does not use converters - at least not for the case I fixed. It uses .NET serialization and writes a GUID ahead of the serialized object so that it can recognize that a clipboard memory handle is a serialized .NET object. Before #415, the stream was positioned at the end so the stream.Read was a noop - and therefore the GetData code was looking at uninitialized global memory and of course not seeing the GUID and therefore just returning the clipboard data as a MemoryStream wrapping the contents of unitionialized global memory (MemoryStream is the default type returned for any custom format without the leading GUID mentioned above).

**Comment by zsd4yr** [comment]
@JoeErickson I can confirm also that #415 is in the Release/3.0 branch, which _should_ be the one that was tested. Going to talk to some folks offline, and make sure I am right in that assumption

**Comment by zsd4yr** [comment]
@safern

**Comment by zsd4yr** [comment]
After talking to the folks that own System.Drawing in CoreFX, ensuring that I sent the testing team the right bits (yes, we did), I am confident that this is either 1) a long standing issue, or 2) a recent one related to @dreddy-work's work here #397

It is strange to me @JoeErickson that the issue is passing in local tests but fails once we join up with the rest of the SDK. There must be some type collisions / poor resolution, and perhaps we own that.

**Comment by Vino-Wang** [comment]
This issue is verified now, so close it.
