### ISSUE TITLE
Location 0, 0 not working on windows 10

### ISSUE THREAD

**Issue by thanhhn253** [dotnet/winforms#4776]
Steps:
- Create new windows form app
- Set StartPosition = Manual
- Set Location = 0, 0
- Run the app
- The app does not display at 0, 0

Please fix!

**Comment by thanhhn253** [comment]
And also if you set Height = Screen.FromHandle(Handle).WorkingArea.Height; it will leave some space at the bottom

**Comment by RussKie** [comment]
Please provide a sample app and screenshots.

**Comment by thanhhn253** [comment]
Sample app: [https://github.com/thanhhn253/test/raw/master/issues_4776.zip](url)
Screenshot:
![image](https://user-images.githubusercontent.com/31772380/114364836-0376ef00-9ba4-11eb-9e7d-b3279dd2152c.png)
![image](https://user-images.githubusercontent.com/31772380/114364900-18538280-9ba4-11eb-9120-4bb05d21e377.png)
![image](https://user-images.githubusercontent.com/31772380/114364943-23a6ae00-9ba4-11eb-96d3-b3aa142bf1cb.png)

**Comment by mcsilver** [comment]
Hi, what's the status of this one for WinForms and .NET Framework 4.7.2, please? I'm noticing the same thing.

**Comment by dreddy-work** [comment]
This is something that may need to address with Operating System. Other native tools show this window is actually located at 0,0 that make me think drawing of the window is off here. @mcsilver , did you try with a native (MFC) application?

![image](https://user-images.githubusercontent.com/36968667/185691624-3ec1c05d-982b-4357-9995-044f37365e61.png)

@Olina-Zhang  can you check this with native app?

**Comment by mcsilver** [comment]
Hi @Olina-Zhang, this may be a problem of understanding more than a problem with the software. In your screenshot, I see that the window's position shows in WinSpy++ as (0,0) but its location on the screen does not appear to be against the left edge of the screen, in my opinion, whereas its top is. Why would its left edge not be touching the edge of the screen when its location is (0,0) whereas its top edge is?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang can you check this with native app?

@dreddy-work MFC native dialog- application has the same testing result:
![image](https://user-images.githubusercontent.com/26474449/185866008-d0e512ef-c9f8-408c-9041-4467471f54ee.png)

**Comment by RussKie** [comment]
If an MFC app is exhibiting this behaviour, then this is likely a Windows level bug.

**Comment by mcsilver** [comment]
Crazy! Okay, thanks.

**Comment by dreddy-work** [comment]
Opened an [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/41027378) in Windows repo and will be tracking the issue there. @mcsilver , to track the progress publicly, you may want to open a feedback ticket for Windows operating system via one of the channels defined [here](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)

**Comment by mcsilver** [comment]
That's great, @dreddy-work. I took your suggestion.

**Comment by RussKie** [comment]
Out of curiosity, does a WPF app exhibit the same?

**Comment by Olina-Zhang** [comment]
> Out of curiosity, does a WPF app exhibit the same?

Yes, it is same.
![image](https://user-images.githubusercontent.com/26474449/186052852-068adb9a-baf3-479e-acd1-7729c864644a.png)

**Comment by dreddy-work** [comment]
Response from OS team for reference:

 
This behavior is by design (oddly enough).  In Windows 8 (or 8.1?) the design was changed so that window borders would have thin (1px at 96 DPI) borders.  

Literally switching to 1px of non-client area on the edges wouldn't work out because grabbing the edges with the mouse would be too hard.  So, the amount of non-client space on the edges was left as 8px wide, but 7px of that space is now transparent.  The programmatic edge of the window is now in a different position than the _visible_ edge of the window.

That is case on the sides and bottom of the window, but wasn't necessary on the top edge.

Apps can query the amount of this transparent space with DwmGetWindowAttribute + DWMWA_EXTENDED_FRAME_BOUNDS.  But note that that API is NOT DPI virtualized, and will return raw physical pixels regardless of the DPI awareness mode of the caller.  That means that it will work fine for per-monitor-aware apps, but will return confusing answers to unaware or system-aware apps.

You can indirectly see this behavior with winspy.  The red selection overlay thing is the positioned around the true window bounds (aka GetWindowRect), but you can see on the sides and bottom that the visible border is inset quite a bit from that.

You will also notice that the mouse cursor changes to the resize cursor outside the windows border.

Image
![image](https://user-images.githubusercontent.com/36968667/186744524-ee7d722e-9212-45e3-aaef-30defa961c5a.png)


Image
![image](https://user-images.githubusercontent.com/36968667/186744537-79ac3cc7-440d-4532-bf1d-b4d7b88cbe3b.png)


@mcsilver and @thanhhn253 as FYI.

**Comment by mcsilver** [comment]
Hi Devendar,

 

I wondered if it was something like that. In fact, I have often been frustrated by the lack of border width when attempting to resize from the top.

 

A question though: After I manually drag a window’s left edge to the left edge of the screen, it seems that the cursor still has several pixels within which it switches to the resizing state. In other words, it doesn’t appear to be a problem for Windows to: 1) position a window against the left edge when it is programmatically set to (0,0), and 2) give the top border the same 8px width, allowing the user to position the cursor more easily for resizing from the top. Am I missing something, or could these changes be implemented without ill effect?

 

Kind regards,

Craig

**Comment by dreddy-work** [comment]
>Am I missing something, or could these changes be implemented without ill effect?

This is the windows decision based on feedback they received. Windows team/feedback channel might be the best place to chat further on this.

**Comment by thanhhn253** [comment]
So now we need to set Location: (-7, 0) right?
Is it always 7px or it depend on the monitor resolution?
Can you provide C# code to get the transparent space width?

Sorry for the late response!

**Comment by RussKie** [comment]
As per the Windows team response posted [above](https://github.com/dotnet/winforms/issues/4776#issuecomment-1227637666):

> _Apps can query the amount of this transparent space with DwmGetWindowAttribute + DWMWA_EXTENDED_FRAME_BOUNDS. But note that that API is NOT DPI virtualized, and will return raw physical pixels regardless of the DPI awareness mode of the caller. That means that it will work fine for per-monitor-aware apps, but will return confusing answers to unaware or system-aware apps._

Windows Forms SDK will not be providing API for this.

**Comment by mcsilver** [comment]
Fair enough.
