### ISSUE TITLE
ListView.HideSelection "DefaultValue" is wrong

### ISSUE THREAD

**Issue by trivalik** [dotnet/winforms#4984]
* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**

`ListView.HideSelection` DefaultValue is "True", but the internal flags are not supposed to show this. This lead to that Designer work makes it impossible to assign True.

**Expected behavior:**
If "DefaultValue" is correct, VS Designer will work as expected.

**Minimal repro:**
1. Create a Form
2. add ListView
3. try to set `HideSelection` property to true
4. Designer will not serialize `HideSelection`, this lead to not working, developer is then wondering why

fix already provided in PR https://github.com/dotnet/winforms/pull/4968

**Comment by weltkante** [comment]
(Summarizing the discussion on the PR)

As noted in the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.hideselection?view=net-5.0#property-value) the historical default value is `true` so the metadata was correct for Desktop Framework up to 4.7.2

In 4.8 they changed the default to be dynamic and depend on a runtime switch. In .NET Core the runtime switches were removed, making this no longer dynamic.

I suspect that switching this to a dynamic default in 4.8 broke the designer, and .NET Core inherited the broken metadata.

Fixing this requires considering what possible states exist in already-designed code, and what effect a change in `[DefaultValue]` would have on it, since any changes need to be compatible with already existing code.

The alternative to changing `[DefaultValue]` is to introduce `ShouldSerializeHideSelection` + `ResetHideSelection` method pair, which arguably should have been done in Desktop Framework 4.8 already if the designer really was broken at that point.

**Comment by dreddy-work** [comment]
In .NET 4.8 we tried to make application more accessible and overlooked the design time scenario. It would align to change `[DefaultValue]` to match with runtime default 'false'.  `ShouldSerialize**` may help as a work around if we wanted help migrating customers but we did not receive many reports yet. For now, we can take this as-is for .NET 6.0.

**Comment by trivalik** [comment]
merged https://github.com/dotnet/winforms/pull/4968

**Comment by Zheng-Li01** [comment]
Verified the issue with latest 6.0.100-preview.7.21320.4 that the issue has been fixed, the Designer will serialize HideSelection property when setting it as True. see below GIF.
![Issue4984](https://user-images.githubusercontent.com/38325459/122731055-7d66db00-d2ad-11eb-994f-df6d854f999c.gif),
