### ISSUE TITLE
Some methods force creation AccessibleObject of a control

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#5018]
* .NET Core Version: 6.0 preview 6

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
- We use `AccessibilityObject` property inside some methods of controls to raise some UIA events
For example - `MonthCalendar.OnGotFocus()`:
```cs
protected override void OnGotFocus(EventArgs e)
{
    base.OnGotFocus(e);
    
    ((MonthCalendarAccessibleObject)AccessibilityObject).FocusedCell?.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
}
```

This property forces creation of the control's accessible object even it is not necessay (no an accessibility tool is running).

**Proposal**: create `IsAccessibilityObjectCreated` and use it where possible (like `IsHandleCreated`)

**Expected behavior:**
- A control shouldn't create its accessible object if it is not necessary

**Minimal repro:**
- Run the internal "WinformsControlsTest" app in the project in the debug mode
- Don't run any accessibility tools (eg. Narrator or Inspect)
- Add a break point to MonthCalendar.OnGotFocus method
- Open "Calendar" form and focus on the calendar
- Go to the code and see, that if the accessible object of the calendar is created

**Comment by Tanya-Solyanik** [comment]
Please also investigate if this method could be used: [UiaClientsAreListening](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/nf-uiautomationcoreapi-uiaclientsarelistening)

**Comment by vladimir-krestov** [comment]
@Tanya-Solyanik, I talked with Guy about UiaClientsAreListening. It doesn't work for us.

**Comment by vladimir-krestov** [comment]
@SergeySmirnov-Akvelon has resolved this issue by #5232. So closed this.

**Comment by Tanya-Solyanik** [comment]
@vladimir-krestov - as far as I understand UiaClientsAreListening works exactly the same as the IsAccessiblityObjectCreate property does. We don't know that an accessibility client is listening, but we know that some UIA client has reasons to create AccessibleObject.

**Comment by Amy-Li03** [comment]
Verified this issue on latest build .NET 6.0.100-rc.1.21417.19, we can see the "IsAccessibilityObjectCreated" property in debug mode when Triggering the GotFocus event of monthCalendar.
![image](https://user-images.githubusercontent.com/62929087/130044500-b5e0073e-a6f6-4a85-919a-b7daa5c9dba4.png)

**Comment by Amy-Li03** [comment]
Verified this issue with .NET 6.0 RC2 latest build: 6.0.10-rc.2.21429.3, the test result same as above.

Explanation from Sergei:

_I think it's more of a technical task. For example, we have a combobox and when choosing an option, we send an event for the narrator in this case we forcefully create an accessibility object even if there is no active external accessibility tool. 
By introducing this flag, we tried to avoid a similar situation.I think as a test, you can try to work with the combobox, without using the external accessibility tool and see that this flag is false
But again, this is more of a technical task in order to show what this flag is for and how we can use it in the future. Therefore, there may be cases when this protection may not work._
