### ISSUE TITLE
Logical issue in RichTextBox.UpdateOleCallback

### ISSUE THREAD

**Issue by kant2002** [dotnet/winforms#5066]
In following lines I think lying logical issue if `punk` does not support `IRichEditOleCallback`.

https://github.com/dotnet/winforms/blob/c76a4a49db18b4b88ed62170ffcb36f5f4718e50/src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs#L3239-L3247

This lead to double release of pUnknown/issues. Honestly I discover that in NativeAOT scenario because I do not implement support for that interface, but probably would be nice to fill the hole.

**Comment by RussKie** [comment]
How can we test the hypothesis?

**Comment by kant2002** [comment]
I think if we create derived class where override `override object CreateRichEditOleCallback() => new object();` the issue will appear in regular .Net

**Comment by kant2002** [comment]
Following code
```
public Form1()
{
    InitializeComponent();
    this.Controls.Add(new CustomOleCallback());
}

class CustomOleCallback : RichTextBox
{
    protected override object CreateRichEditOleCallback()
    {
        return new object();
    }
}
```

produce following exception
```
This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.Marshal.Release(System.IntPtr) in Marshal.CoreCLR.cs
    System.Windows.Forms.RichTextBox.UpdateOleCallback() in RichTextBox.cs
    System.Windows.Forms.RichTextBox.OnHandleCreated(System.EventArgs) in RichTextBox.cs
    System.Windows.Forms.Control.WmCreate(ref System.Windows.Forms.Message) in Control.cs
    System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message) in Control.cs
    System.Windows.Forms.TextBoxBase.WndProc(ref System.Windows.Forms.Message) in TextBoxBase.cs
    System.Windows.Forms.RichTextBox.WndProc(ref System.Windows.Forms.Message) in RichTextBox.cs
    System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message) in Control.ControlNativeWindow.cs
    System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message) in Control.ControlNativeWindow.cs
    System.Windows.Forms.NativeWindow.Callback(System.IntPtr, Interop.User32.WM, System.IntPtr, System.IntPtr) in NativeWindow.cs

```

**Comment by weltkante** [comment]
> This lead to double release of pUnknown/issues

can you detail this a bit more? the only thing I see is that it doesn't check for IntPtr.Zero and Marshal.Release will probably throw when passed zero (or just ignore it) - but I can't identify the refcounting bug you seem to have spotted?

Throwing the exception due to releaing IntPtr.Zero is fine, looking at the method I see no resource leaks, of course it will be unintuitive for the caller to diagnose what went wrong so an explicit check against IntPtr.Zero (or failure of QueryInterface) is ok, but I don't think it fixes any bugs.

> I discover that in NativeAOT scenario because I do not implement support for that interface

WinForms assumes the .NET runtime is working, breaking WinForms by breaking the runtime is no good way to test things. I don't think there is any issue unless you can point out the refcounting leak in exceptional paths which I'm not seeing.

**Comment by kant2002** [comment]
I think you are right. that's not belong here.
