### ISSUE TITLE
Incorrect dimensions of collapsible ListViewGroup

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#5087]
* .NET Core Version: .NET 5.0+

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

A collapsible listview group has incorrect dimensions, i.e. it taller than necessary. 
![image](https://user-images.githubusercontent.com/4403806/121810086-bea22e00-cca2-11eb-8774-1c3af1f8ead9.png)

The issue is caused by incorrect settings of flags, and assuming that `Subtitle` is always set:
https://github.com/dotnet/winforms/blob/b53ac8bf1d21598068af5e850fb363594948240b/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L5742-L5755

The same incorrect assumptions are made about `TaskLink` and `Footer` properties.
Additionally these properties aren't decorated with default values, resulting in these properties being serialized
![image](https://user-images.githubusercontent.com/4403806/121810222-49832880-cca3-11eb-8bcc-9b2a817f4396.png)

The main issue is that there is no easy workaround, because it impossible to set `null` to either of the properties (the getter will always return a non-null).

**Expected behavior:**

The extended properties must not be set, if they don't contain values.

**Comment by Zheng-Li01** [comment]
Verified the issue with latest 6.0.100-preview.7.21320.4 that the issue has been fixed, no code generated for Subtitle/TaskLink/Footer properties when not setting. see below GIF.
![Issue5087](https://user-images.githubusercontent.com/38325459/122730781-32e55e80-d2ad-11eb-9c83-5d5a8ec9693d.gif)

**Comment by Olina-Zhang** [comment]
Verified this issue with the latest .Net SDK 6.0.100-preview.6.21322.9 build, this issue is fixed, no code generated about Subtitle/TaskLink/Footer properties when they are not set. And in runtime, the dimensions of collapsible listViewGroup is changed.
Now:
![image](https://user-images.githubusercontent.com/26474449/123062395-0f521d80-d43f-11eb-8e73-c7e7bb1f6be6.png)
Before:
![image](https://user-images.githubusercontent.com/26474449/123062437-19741c00-d43f-11eb-9a77-ea67f5553434.png)

**Comment by John-Qiao** [comment]
Verified this issue with the .NET SDK 5.0.9, this issue is fixed, no code generated about Subtitle/TaskLink/Footer properties when they are not set. And in runtime, the dimensions of collapsible listViewGroup is changed.
![TestResult-5087](https://user-images.githubusercontent.com/45864985/126270560-b6ddca50-7ac7-4c10-bb2c-a50b258a5b20.png)
