### ISSUE TITLE
[Multi-Monitor] The checkbox icon of toolStripMenuItem is not scaled well when DPIs differ

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#5106]
* .NET Core Version: 
.NET SDK 6.0.100-preview.6.21313.2 + private binaries build from main branch in dotnet/winforms repo [Private dlls.zip](https://github.com/dotnet/winforms/files/6654393/Private.dlls.zip)

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The checkbox icon of toolStripMenuItem is not scaled well.
![Move-300-to-100](https://user-images.githubusercontent.com/45864985/122028131-50727e00-cdfe-11eb-823e-6b09d4a23331.png)

**Expected behavior:**

The checkbox icon of toolStripMenuItem should be scaled well.
![300](https://user-images.githubusercontent.com/45864985/122028139-52d4d800-cdfe-11eb-81dd-112fe3c9a499.png)

**Minimal repro:**

1. Set the primary screen as 300% DPI, and second screenshot as 100% DPI.
2. Open and run the [TestApp6.zip](https://github.com/dotnet/winforms/files/6654442/TestApp6.zip) on the 300% primary screen.
3. Move form to 100% DPI second screen, and click **Tools** option in form, then observe the checkbox icon before **Customize**.

**More info:**

1. Just repro in PerMonitorV2 mode with Form's AutoScaleMode: Font/DPI.
2. Cannot repro in SystemAware mode, since this issue is in secondary screen.
3. Also repro in without privates.

**Comment by Mandi-Man** [comment]
Verified with 17.3.0 Preview 3.0 [32612.38.main], this issue is not reproduce.
When moving the form to the second screen at 100% DPI and clicking on a tool option in the form, the checkbox icon of toolStripMenuItem can be scaled nicely.
Please see below gif:
![issue5106](https://user-images.githubusercontent.com/104553917/173762887-975322eb-2ed2-4c45-ad74-5907655eadc6.gif)
