### ISSUE TITLE
WinForms project templates use latest C# language idioms

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/winforms#5171]
In .NET 6, the included C# project templates will use the latest language idioms.

See the [parent Epic](https://github.com/dotnet/templating/issues/3359) for details.

@OliaG

**Comment by RussKie** [comment]
Related:
- https://github.com/dotnet/winforms/issues/5071
- https://github.com/dotnet/winforms/issues/5074

**Comment by DamianEdwards** [comment]
@RussKie just making sure you're aware of the SDK feature being implemented to support implicit/default global usings. There's [a PR going on right now](https://github.com/dotnet/sdk/pull/18459) to enable this and then the WindowsDesktop SDK should utilize this feature too.

**Comment by vlada-shubina** [comment]
Just a hint since this repo is also using `--langVersion`: in project common templates we discovered issues to due to new features are only working in certain frameworks / language versions, so we are considering to conditionally enable features based on language version set by user (if set).
Draft PR on this is here: https://github.com/dotnet/templating/pull/3454.

**Comment by DamianEdwards** [comment]
The compiler with support for this is now in SDK version 6.0.100-preview.7.21364.4

**Comment by RussKie** [comment]
@vlada-shubina could you guide me through the changes we need to make in [our templates](https://github.com/dotnet/winforms/tree/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates)? Do we need to copy the changes from https://github.com/dotnet/templating/pull/3454?

**Comment by vlada-shubina** [comment]
> @vlada-shubina Vlada Shubina FTE could you guide me through the changes we need to make in [our templates](https://github.com/dotnet/winforms/tree/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates)? Do we need to copy the changes from [dotnet/templating#3454](https://github.com/dotnet/templating/pull/3454)?

Since the templates allow the user to pick up the language version (and also framework in your case) you need to consider it when making the change, as if the user picks up lower language version or lower framework the template based on latest C# features may fail on build. 

Generally for each feature you introduce to your templates you need to do the following conditions:
```
#ifdef (<framework supports the feature> &&<language version supports the feature>)
<updated code for the feature>
#else
<old code>
#endif
```
In case of console/classlib it was quite straightforward, as the content is very simple; but it might be more complicated with more code in the template..

I would recommend the following approach:
- define regex match generator for each lang version conditions needed (see `csharpNorLater` symbol in my PR)
- define computed symbol for each feature in use (see `csharpFeature_ImplicitUsings` for example in my PR)
  - note in your case conditions might be different in case template supports more frameworks - for console template we only support net6.0 so conditions just rely on langVersion, for classlib we additionally support `netstandard2.0` and `netstandard2.1`, so the conditions exclude not supported frameworks
- use conditions in your code to enable / disable features (see cs and csproj files in my PR).
 
You can follow the way we did for console/classlib but direct copy-paste won't work - you need to adapt it for your template content.

I would also recommend to run the tests on all possible combinations of templates/frameworks/language versions to see if the template can be instantiated and at least built successfully, and assert if file content is as expected.

**Comment by vlada-shubina** [comment]
Additional thought: if your template code file content is too difficult to manage with inline conditions, you may consider doing different files and pick up the correct file to use using `sources` based on condition. 
You already use this approach in some templates to pick up correct csproj file: https://github.com/dotnet/winforms/blob/e0c821b17863458611e4e056c16eb1ad65f9ce9a/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json#L82-L103

**Comment by RussKie** [comment]
@vlada-shubina thank you!

**Comment by RussKie** [comment]
Nullability was enabled in our templates by @jmarolf in https://github.com/dotnet/winforms/pull/4922
