### ISSUE TITLE
Repository organisation

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#519]
It is a question/discussion more than anything.

I find the physical organisation (left) of the repo somewhat confusing as it has quite different layout to the logical organisation (right):

![image](https://user-images.githubusercontent.com/4403806/53677251-f7e84700-3d00-11e9-990d-78a5653e2f7e.png)

The downside of this differences is a higher cognitive load and reduced discoverability of elements in the repo, as well as very confusing namespace organisation for the tests.

Few random examples:

* `BitmapEditorTests` lives under "winforms\src\System.Windows.Forms.Design.Editors\tests\UnitTests". 
Not withstanding that it is actually a suite of tests for `MockBitmapEditor` (that resides in "winforms\src\System.Windows.Forms.Design.Editors\tests\UnitTests\Mocks"), one would reasonably expect to find `BitmapEditor` in "winforms\src\System.Windows.Forms.Design.Editors\src". 
However the actual `BitmapEditor` class is found under "winforms\src\System.Windows.Forms.Design.Editors\src\System\Drawing\Design" and the its namespace is `System.Drawing.Design` and not `System.Windows.Forms.Design.Editors`.
https://github.com/dotnet/winforms/blob/f25dc3d526b121ab9adbff3b5779c856a07afa78/src/System.Windows.Forms.Design.Editors/tests/UnitTests/BitmapEditorTests.cs#L8-L30

* There is `ButtonTests` that live under "winforms\src\System.Windows.Forms\tests\UnitTests" and the SUT is located under "winforms\src\System.Windows.Forms\src\System\Windows\Forms"
https://github.com/dotnet/winforms/blob/3ce29ac28e6cf25dbb3538543c98376f1d7a0da9/src/System.Windows.Forms/tests/UnitTests/ButtonTests.cs#L9-L21
The namespace match, all good.
Then there is `ColumnStyleTests` that lives under "winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms" yet the SUT is found in "winforms\src\System.Windows.Forms\src\System\Windows\Forms" (the SUT is also defined in `TableLayoutSettings.cs`, which further increases the confusion).

What is a reason for modelling the repo in its current state?
Why tests for classes defined in same namespaces are placed in very different physical locations?
Should/could the physical organisation be aligned with the logical organisation?

**Comment by merriemcgaw** [comment]
Hi @RussKie , we discussed many of your questions when we created this repo and decided that it would make more sense. The top level folder structure is aligned with what other .NET Core repos are doing. When we did the initial port from .NET Framework we had to match that subfolder structure to optimize for ongoing porting work that may (did/does) still occur. But the tests were generally new and we decided that it made sense for them all to go under tests. We thought that the solution structure more reflected how users are going to develop on their machines (mostly that the dev worries about the src folder).  

This is totally something we could potentially revisit in .NET Core 3.1 or later if this generates too much confusion and we get additional feedback from other contributors. For now we're focusing on getting the repo to parity functionally with .NET Framework.

**Comment by zsd4yr** [comment]
The current *actual* folder structure is a combination of:
1. typical .NET Core top-level structure
1. our personal design to accommodate reference and tests projects new to our .NET Core skew; and
1. hold-over structure from .NET FX in order to make duel check-ins between .NET Core 3.0 and .NET FX 4.8 more one-to-one; easier

To clarify Merrie's comment a little with images

# This style comes from what other .NET Core repos do

### [root](https://github.com/dotnet/winforms) directory:
![image](https://user-images.githubusercontent.com/10677481/53832481-46812580-3f3b-11e9-977a-899b8543bf0d.png)

### top-level [src](https://github.com/dotnet/winforms/tree/master/src) directory:
![image](https://user-images.githubusercontent.com/10677481/53832504-513bba80-3f3b-11e9-8b92-8c7f79ee1105.png)

# this style is to accommodate the addition of separate tests and reference projects in .NET Core; this is our own machinations

* note: once #175 is in, I think that we could more closely reconsider changing this structure as the ref subdirectory would no longer exist

### [src\System.Windows.Forms](https://github.com/dotnet/winforms/tree/master/src/System.Windows.Forms) (binary) directory:
![image](https://user-images.githubusercontent.com/10677481/53832555-729ca680-3f3b-11e9-9115-b0e5b45c20a6.png)

### [src\System.Windows.Forms\tests](https://github.com/dotnet/winforms/tree/master/src/System.Windows.Forms/tests) lower-level directory:
![image](https://user-images.githubusercontent.com/10677481/53832677-a4ae0880-3f3b-11e9-9469-f7b361d78827.png)

### [src\System.Windows.Forms\ref](https://github.com/dotnet/winforms/tree/master/src/System.Windows.Forms/ref) lower-level directory:
![image](https://user-images.githubusercontent.com/10677481/53832991-66fdaf80-3f3c-11e9-9e7b-3eb2e035dbba.png)

# And this style is a holdover from classic framework (.NET FX)

* this is also something that we can reconsider but not until we are largely contributing only to .NET Core. The ongoing benefits of the similarities of this structure to the .NET FX structure are overwhelming for the time being.

### [src\System.Windows.Forms\src](https://github.com/dotnet/winforms/tree/master/src/System.Windows.Forms/src) lower-level directory:
![image](https://user-images.githubusercontent.com/10677481/53832655-98c24680-3f3b-11e9-8e67-60f514eecab8.png)

When we created the solution folder structure, we had more liberties. So we redesigned in order to help developers focus on src for all the binaries. I think that it is more likely that we would redesign this to be more identical to the actual, then to change the actual. However, we would need to hear from multiple contributors that they would prefer to develop in the a new (hypothetically) proposed structure as we made the current schema with developer-ease in mind.

**Comment by RussKie** [comment]
Thank you for the clarifications.
Please let me know, if you wish me to help with the restructure.
