### ISSUE TITLE
When vertically writing "MS P Gothic" font, etc., the character position is moved to the right depending on the font size.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#5191]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-vertically-writing-MS-P-Gothic-fo/1466584)._

---
[severity:It's more difficult to complete my work]
The characters drawn when the font size is 16 or less are in a strange position.
At size 17, it is located in the center of the column, but at size 16, the position of 'I' is especially close to the right.
Before DrawString
e.Graphics.TextRenderingHint = TextRenderingHint.AntiAlias;
to center the column even at size 16.
Isn't this a problem when drawing using bitmaps in fonts?

The image left is size 16 and the right is size 17. At size 16, the position of 'I' is clearly to the right.
! [Capture. PNG](https://aka.ms/dc/image?name=Bddecd4ac90b6468c827f8082d0d4f47c637606237066894308_%E3%82%AD%E3%83%A3%E3%83%97%E3%83%81%E3%83%A3.PNG&tid=ddecd4ac90b6468c827f8082d0d4f47c637606237066894308)

```
protected override void OnPaint(PaintEventArgs e) {
	string fontname = "MS P Gothic";
	using (Brush brush = new SolidBrush(Color.Black))
	using (Font font1 = new Font(fontname, 16))
	using (Font font2 = new Font(fontname, 17)) {
		string text = "AI A"; FullWidth
		StringFormat sf = new StringFormat(StringFormat.GenericTypographic);
		sf. FormatFlags |= StringFormatFlags.DirectionVertical;
		e.Graphics.DrawString(text, font1, Brushes.Black, 5, 10, sf);
		e.Graphics.DrawString(text, font2, Brushes.Black, 25, 10, sf);
	}
}
```

environment
Windows 10 Pro x64 21H1 (Japanese)
Display scale 100%
VisualStudio2019 Version 16.10.1
.NET framework 4.7.2
C#/WindowsForm

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by John-Qiao** [comment]
* .NET Core Version: 
.NET SDK 6.0.100-preview.7.21351.6

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**

When the font size is 16(or smaller), the position of characters is moved to the right, especially the 'I' character, it's clearly to the right.
![Actual](https://user-images.githubusercontent.com/45864985/124237574-3a78f300-db4a-11eb-9fee-d05d1be3515b.png)

**Expected behavior:**

The position of characters should be located in the center of column, like it works when font size is 17 or bigger.

**Minimal repro:**

1. Open the attached [TestApp.zip](https://github.com/dotnet/winforms/files/6752867/TestApp.zip) project in VS and run it.
2. Observe the position of 'ＳＰＡＩ'.

**More info:**

This is not the regression issue, it occurs in both .NET Framework and .NET Core.

**Comment by RussKie** [comment]
@John-Qiao can you check how it behaves in an MFC?

**Comment by John-Qiao** [comment]
@RussKie We created a C++ Windows Desktop project to test this scenario, the issue can be reproduced in it too.

[WindowsProject1.txt](https://github.com/dotnet/winforms/files/6775730/WindowsProject1.txt)

![TestResult-C++](https://user-images.githubusercontent.com/45864985/124727900-b9eb3580-df41-11eb-96b8-14dcb6bc39ad.png)

**Comment by RussKie** [comment]
This is how Windows draws the text, we have no control over it. The feedback needs to be submitted via the Windows Hub.
