### ISSUE TITLE
API Proposal: Add Descendants property for Control

### ISSUE THREAD

**Issue by OJacot-Descombes** [dotnet/winforms#5195]
# Motivation

Often it is necessary to not only iterate the immediate child controls through the `Controls` property but also the nested ones.

Google returns 5’540 results for "site:stackoverflow.com iterate nested controls winforms".

# Proposal

Add a `Descendants` property to `Control` iterating child controls recursively.

## Note
Since `Form` derives from `Control`, the property would be available on the form level as well.
``` c#
/// <summary>
///  Returns a collection of descendant child controls for this form or control
/// </summary>
[Browsable(false)]
[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
public IEnumerable<Control> Descendants
```

# Example
``` c#
foreach (var tb in Descendants.OfType<TextBox>()) {
    tb.Text = "";
}
```

**Comment by weltkante** [comment]
I'll add a note that operating on descendant controls of composite controls you didn't build yourself is generally bad practice, as you don't know what side effects any changes to these controls will have.

If the `Descendants` property somehow would only traverse the layer of controls you placed in the designer (including controls placed on panels and other containers) this would be much more useful since it avoids digging into random 3rd party controls

**Comment by OJacot-Descombes** [comment]
@weltkante. What is the behaviour of the `Controls` property? Does it apply the restriction you are suggesting? If, yes, it would be easy implement `Descendants` recursively base on the `Controls` property.

**Comment by weltkante** [comment]
No, the information required to implement a designer-centric enumeration does not currently exist and would need to be created. I'm just throwing this into the discussion because I often found blindly iterating through and operating on the control tree of a third party control breaks them, somtimes in subtile ways.

Its fine for simple applications that only use the win32 wrappers or simple self-drawing controls but whenever you come across some control that has a fully managed implementation and uses composition it ends up as a mess.

I don't want to prevent people doing it, obviously they already can write an extension method to that effect, but I want to make the discussion consider whether there are ways to make this approach compose better instead of exposing the naive approach that invites bad practice.

**Comment by OJacot-Descombes** [comment]
@weltkante, I do net see a simple reliable way to implement this. Users will end up having to apply a white/blacklist as before to `Descendants`, I fear.

A clean solution would be to mark such third-party controls with an attribute (either on the top level or only the "forbidden" child controls). But of course, control makers would have to join the game. But even then, there are situations were simply inspecting these controls would create no harm and be useful.

Since the situation is not any different to using the `Controls` collection directly, I think that we should implement `Descendants` by simply iterating the `Controls` collection recursively. This is what most users will expect from this new property. A behavior deviating  from the behavior of  `Controls` would be confusing.

**Comment by merriemcgaw** [comment]
We thank you for your suggestion, however it does not meet our bar. This is a convenience feature and can be implemented as an extension method using whichever technique you need (breadth-first or depth-first).
