### ISSUE TITLE
When is expected a stable version of WinForm core Designer ?

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/winforms#5219]
When is expected a stable version of WinForm core Designer?

.NET 5 Designer was not updated for while.

**Comment by merriemcgaw** [comment]
We've been working hard under the hood to improve our Core designer and bring it up to parity. We are getting close, and 16.10 saw a lot of performance improvements especially with interacting directly with controls on the form, and adding the MenuStrip, ToolStrip and StatusStrip in-situ editors so you can now manage  your menus the way you always have.

When will we be done? I don't have a solid timeline for you. Although, aside from a couple of features, including Accessibility support, Tab Order Overlay and some data binding scenarios you should find most of what is  used on a daily basis. I encourage everyone to install the 16.10 Visual Studio and start playing with the designer. We will be able to fully stabilize and remove the "preview" checkbox only if we've gotten feedback from customers. As we uncover new scenarios that are needed, or old ones that we still need to bring back, your feedback through the VS feedback tool is critical to us so we can prioritize them.

I know it's been a long journey, but we're getting to the finish line. Converting to a 2 process solution, where VS in the .NET Framework can interact with your .NET 5/6 app displaying in the designer has required us to rearchitect the entire way a developer interacts within the designer. As we've done that work we've been working through a system largely stable since VS2005. It's been an exciting journey and we are glad to have everyone on it with us.
