### ISSUE TITLE
ClickOnce user.config update does not work on .Net Core runtime

### ISSUE THREAD

**Issue by lGSMl** [dotnet/winforms#5258]
### Description

We have recently moved our clickonce app on .net core 3.1, as .net 5 SDK now supports publishing clickonce apps.

After moving to core we faced an issue that user.config is not preserved anymore between application updates.

According to [this clickonce documentation](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-and-application-settings?view=vs-2019#version-upgrades) - user.config in the new version should be merged with an existing one. That was the case with 4.8, but it does not work on core.

### Configuration

Core 3.1, win10-x64

### Regression?

Regression from framework 4.8

### Other information

After some debugging I was able to figure out that on core runtime there is a snippet missing in comparison to 4.8:

[How path to data folder is resolved in core
](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs#L34)
[How path to data folder is resolved in 4.8
](https://referencesource.microsoft.com/#System.Configuration/System/Configuration/ClientConfigPaths.cs,447b3a83c09259bb)

So this part is missing on core:

```
if (this.IsClickOnceDeployed(AppDomain.CurrentDomain)) {
            string dataPath = AppDomain.CurrentDomain.GetData(ClickOnceDataDirectory) as string;
            string versionSuffix = Validate(_productVersion, false);

            // NOTE: No roaming config for clickonce - not supported.
            if (Path.IsPathRooted(dataPath)) {
                _localConfigDirectory = CombineIfValid(dataPath, versionSuffix);
                _localConfigFilename  = CombineIfValid(_localConfigDirectory, UserConfigFilename);
            }

        }
```
That leads to creation of new data folder on every app update via clickonce, and, presumably, causes issue with clickonce user.config update.

**Comment by dreddy-work** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1357963

**Comment by dreddy-work** [comment]
Some ClickOnce features are not available in .NET (Core). There is no way for user’s app to access various runtime ClickOnce properties, i.e. in ApplicationDeployment object, since it does not exist anymore.

Customers app is writing the config file to a location outside of ClickOnce isolated storage, in a path determined, and generated by the application. My(Nikolam) suggestion would be to explore options to modify that functionality, i.e. use a path that does not depend on app install location in ClickOnce store. That would solve the existing issue, by avoiding constant recreation of user config file whenever new version gets deployed.

**Comment by dreddy-work** [comment]
We have a tracking Azdo bug and this is not a winforms issue but clickonce. So, closing it here.
