### ISSUE TITLE
Anchor: "Bottom, Left" Bug

### ISSUE THREAD

**Issue by kelicto** [dotnet/winforms#5414]
* .NET Core Version: Not test.

* Have you experienced this same bug with .NET Framework?: Yes.

**Problem description:** The label 'ErrorMessage' - 'Anchor' must set default value 'Top, Left'. Otherwise, the label's position is below of derived form.

**Expected behavior:**
![image](https://user-images.githubusercontent.com/23723575/128987645-32f3e9fa-a4da-4447-b682-18545f1871da.png)
![image](https://user-images.githubusercontent.com/23723575/128988507-e795fabc-b6de-4b15-b5d3-de0ca37a3569.png)

**Minimal repro:**
https://github.com/kelicto/PositionBugByAnchorProperty

**Comment by RussKie** [comment]
Please fill in the template correctly and provide a sample app. Otherwise this will be closed.

**Comment by kelicto** [comment]
Ok.

**Comment by kelicto** [comment]
To fix it, I create a new form and copy controls to do. Winform app needs a lot of improvement. Experience is very bad!

**Comment by kelicto** [comment]
After setting the location, it will automatically restore it back.

**Comment by kelicto** [comment]
My project have lots of forms, new form and copy controls to solve is very stupid! But, I have not any way to fix it!

**Comment by kelicto** [comment]
Very bad designer!

**Comment by kelicto** [comment]
And button-bug haven't any way to fix.

**Comment by kelicto** [comment]
I want to hurl.

**Comment by dreddy-work** [comment]
@kelicto , you are asking to change the default behavior that has been there since .NET framework and people might have taken dependency on that default behavior.

**Comment by kelicto** [comment]
But, I think it should be a bug.

**Comment by RussKie** [comment]
I tried your sample, and everything appears to be working as expected:
![5414](https://user-images.githubusercontent.com/4403806/129659430-221128e5-8e16-43e3-b5b6-1ee04e5c178d.gif)


Could you please help us understand what you see as a problem?

**Comment by kelicto** [comment]
Oh, I'm sorry. I don't reference other dll. I submit some code. And the label should not appear on form. I'm not sure if it's because you do other operations.

**Comment by kelicto** [comment]
No! It's a base form. You should test FeedbackForm.

**Comment by RussKie** [comment]
In your derived control you sent the location of the label which is outside the client rectangle:
![image](https://user-images.githubusercontent.com/4403806/130007126-6b5122f1-ff1a-47fb-93d6-fb258fa34c1e.png)

Everything else works correctly.

**Comment by kelicto** [comment]
I don't think so.
![image](https://user-images.githubusercontent.com/23723575/130026332-49870797-130a-4f05-86b4-836c67a357a1.png)

**Comment by kelicto** [comment]
@RussKie Please open the issue, does not appear to have been resolved.

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/130283266-f0a280c5-4975-4dc2-89c6-4a9948ff22df.png)
Shit!

**Comment by kelicto** [comment]
![Animation](https://user-images.githubusercontent.com/23723575/130310283-d35eb85b-6e31-4123-a8f9-eaa200e425a2.gif)

**Comment by weltkante** [comment]
As far as I'm aware this bug triggers when you have inherited forms with docked panels and the (designer) size of the base form is different from the (designer) size of the subclass form. When designing the subclass form something "goes wrong" and it will misinterpret locations. Thats how you end up with offscreen locations of labels and such. In some scenarios its even repeatable and it will shift the controls every time you open/edit/save the subclass form, quite annoying.

We have encountered this scenario quite often in our codebase, my workaround to remove this behavior is not using docked panels and instead either make them docked at runtime via code, or update their position/size at runtime via code. (Note that the base class form _will be executed_ by the subclass form designer, so you have some flexibility in behavior.)

Its possible to work around these issues and have the designer work properly, but its nontrivial and requires trial-and-error. I don't have a recipe that always works, except the general guideline that you should start by turning of docking on the affected panels until things stop breaking, and then gradually explore how you can get the desired layout behavior via code instead of using the designer.

Given this issue was created against the Desktop Framework designer, I don't believe it will be updated anymore at this point. Maybe the .NET Core designer will eventually be better at handling subclass forms.

In this sense, I think it would be valuable for the WinForms team to reproduce and understand the broken behavior, so they can test it against the new designer and track subclass form layout issues.

**Comment by kelicto** [comment]
> As far as I'm aware this bug triggers when you have inherited forms with docked panels and the (designer) size of the base form is different from the (designer) size of the subclass form. When designing the subclass form something "goes wrong" and it will misinterpret locations. Thats how you end up with offscreen locations of labels and such. In some scenarios its even repeatable and it will shift the controls every time you open/edit/save the subclass form, quite annoying when controls are "wandering off" this way.
> 
> We have encountered this scenario quite often in our codebase, my workaround to remove this behavior usually is using undocked panels in the base class form and instead either make them docked at runtime via code, or update their position/size at runtime via code. (Note that the base class form _will be executed_ by the subclass form designer, so you have some flexibility in behavior of the code you write.)
> 
> Its possible to work around these issues and have the designer work properly, but its nontrivial and requires trial-and-error. I don't have a recipe that always works, except the general guideline that you should start by turning off docking on the affected panels _in the base class_ until things stop breaking, and then gradually explore how you can get the desired layout behavior via code instead of using the designer. Since the subclass form designer will execute your baseclass form code it can be made working if you do it right.
> 
> Given this issue was created against the Desktop Framework designer, I don't believe it will be updated anymore at this point. Maybe the .NET Core designer will eventually be better at handling subclass forms.
> 
> In this sense, I think it would be valuable for the WinForms team to reproduce and understand the broken behavior, so they can test it against the new designer and track subclass form layout issues in the designer.

Thank you, I make sure that you and your team know this phenomenon is also very important!

**Comment by weltkante** [comment]
> I make sure that you and your team know this phenomenon

I'm not a member of the WinForms team, github issues are open for public and I just commented because this looks like an issue I've already had seen previously.

> The value Must be not Bottom.

The issue is triggered by multiple things coming together (bottom anchored child controls, docked or anchored parent container controls, form inheritance of different designer sizes), you can remove any of the conditions to avoid triggering the bug. Try removing the docking from the panel in the base class and you'll see it'll suddenly work (after resetting the location of the label in the designer). Of course when then resizing the form the panel won't keep up anymore.

By adjusting the container panel instead of the child controls you only have to work around the problems at one location instead of adjusting each child control manually in code. If there's only one child control it does of course not matter.

**Comment by kelicto** [comment]
I want to auto position. So, I have to do that.
