### ISSUE TITLE
update .Net 6 Preview 7 gives Unable to find an entry point named 'SetWindowTheme' in DLL 'user32'.

### ISSUE THREAD

**Issue by 199621616** [dotnet/winforms#5622]
### Description
SDK: 6.0.100-preview 7.21379.14
.Net runtimes : .NETCore.App 6.0.0-preview7.21377.19   WindowsDesktop.App 6.0.0-preview.7.21378.9
      

### Regression?

System.EntryPointNotFoundException
  HResult=0x80131523
  Message=Unable to find an entry point named 'SetWindowTheme' in DLL 'user32'.
  Source=DevComponents.DotNetBar2
  StackTrace:
   在 DevComponents.DotNetBar.Controls.ComboBoxEx.SetWindowTheme(IntPtr hWnd, String pszSubAppName, String pszSubIdList)
   在 DevComponents.DotNetBar.Controls.ComboBoxEx.ᑩ(IntPtr ࣻ)
   在 DevComponents.DotNetBar.Controls.ComboBoxEx.OnHandleCreated(EventArgs e)
   在 System.Windows.Forms.Control.WmCreate(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ComboBox.WndProc(Message& m)
   在 DevComponents.DotNetBar.Controls.ComboBoxEx.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

**Comment by danmoseley** [comment]
Transferring to winforms. Not clear where issue lies, but probably the best place to start.

**Comment by dreddy-work** [comment]
@199621616, it should be from UxTheme. It seems you are trying to migrate your custom control. What was its original target framework? Were you explicitly trying to import this API from `user32.dll` ?

**Comment by jespersh** [comment]
The component has a condition where if `Environment.Version.Major > 5` or `Environment.Version.Major == 5 && Environment.Version.Minor >= 1` then it calls into the user32.dll version of `SetWindowTheme`, which it starts doing I assume for .NET 6.0. This happens if you use their `ComboBoxEx`.

If you're unable to raise the dormant developers of devcomponents (last update was 3 years ago), then either stick with .NET5 or use a tool that allows you to edit the dll.

**Comment by dreddy-work** [comment]
@huoyaoyuan ,  in this case i believe you need to follow-up with the owners of that dll to update the explicit import here. Closing the issue from winforms side.
