### ISSUE TITLE
.NET 5.0, WinForms: Changing ShowInTaskbar will let CheckedListBox-items disappear.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#6093]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-50-WinForms:-Changing-ShowInTaskb/1567672)._

---
[severity:I'm unable to use this version]
I create a new WinForms project with .NET 5.0, either with C# or VB.NET.
I add a CheckedListBox to the form and add some items via the designer.
With a Button-Click I change ```ShowInTaskbar``` for the form to ```False```.
The items in the CheckedListBox are not visible anymore, even if I force a redraw of the form.
With a .NET-framework 4.x project, everything works fine (all items are shown).

before changing ShowInTaskbar
![before.png](https://aka.ms/dc/image?name=Bd80d52b3128f494385016b19c6a3dc4c637712220026147469_before.png&tid=d80d52b3128f494385016b19c6a3dc4c637712220026147469)

after changing ShowInTaskbar
![after.png](https://aka.ms/dc/image?name=B699f10c266d747fe8a323be280a114d4637712220423736244_after.png&tid=699f10c266d747fe8a323be280a114d4637712220423736244)

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by VinoWang01** [comment]
* .NET Core Version: .NET Core 7.0.100-alpha.1.21531.1


* Have you experienced this same bug with .NET Framework?: No


**Problem description:**
The CheckedListBox's items are disappearing when set the Form's ShowInTaskBar property to false in run time.
![ShowInTaskBar](https://user-images.githubusercontent.com/90816462/139641850-0842c556-bcdd-424b-bb71-2baf87b4c041.gif)

**More info:**
1. This is a regression issue, it can't reproduce when targeting .NET Core 3.1, can reproduce when targeting .NET 5.0, 6.0, 7.0.
2. This issue can't reproduce when setting the ShowInTaskBar property in designer.



**Expected behavior:**
The CheckedListBox's items shouldn't disappear.
![ShowInTaskBar_3 1](https://user-images.githubusercontent.com/90816462/139640974-32a1aad5-9e94-45ec-8f78-cfa303ab9b87.gif)



**Minimal repro:**
1. Download and extract the attached project. [ShowInTaskbarIssue.zip](https://github.com/dotnet/winforms/files/7451646/ShowInTaskbarIssue.zip)
2. Run it and click the button in the form.
3. Observe the items in the checkListBox control.
Or
1. Create a .NET Core Winforms app with a CheckedListBox and a button added.
2. Add some items to CheckedListBox control.
3. Double click the button to add following code: 
     private void button1_Click(object sender, EventArgs e)
        {
            this.ShowInTaskbar = false;
        }
4. Run the project and click the button to see the items in the CheckedListBox.

**Comment by RussKie** [comment]
This appears to be a regression introduced in .NET 5.0 timeframe, and it affects `ListBox` and `CheckedListBox` controls.
The `ListBox` control is rendered as readonly with the incorrect background, though it remains enabled and usable. The `CheckedListBox` control loses its state completely.

![image](https://user-images.githubusercontent.com/4403806/139774029-1f175a1d-f3db-46cc-84c6-9da7faea3b23.png)
On the left `ListBox` and `CheckedListBox` controls, on the right `ListView` controls.

After a long and nasty git bisect I established that we regressed in https://github.com/dotnet/winforms/pull/2262, however I haven't performed any root cause analysis.
/cc: @chenxinyanc

**Comment by Amy-Li03** [comment]
Verified this issue on .NET 7.0.0-alpha.1.21566.13 build, issue was fixed.
![Fixed](https://user-images.githubusercontent.com/62929087/142143149-035c157c-f4e8-498e-9ac8-dd2f60b81ecf.gif)

**Comment by Olina-Zhang** [comment]
Verified this issue in .Net 6.0.101-servicing.21568.17 build, it is fixed with the same above result on .Net 7.0.

**Comment by VinoWang01** [comment]
Verified this issue in .Net 5.0.210 build, the checkedListBox-items will not disappear when changing the Form's ShowInTaskBar property.
