### ISSUE TITLE
Menu bar for maximized hosted MDI window not being exposed through UIA as expected

### ISSUE THREAD

**Issue by ArtemTatarinov** [dotnet/winforms#6231]
* .NET Core Version: 3.0, 3.1, 5.0, 6.0, 7.0
* Have you experienced this same bug with .NET Framework?: The issue is reproduced at 4.8; 4.7.2 has all the buttons, but their order is reversed.

**Problem description:**
When the child MDI window is maximized, the Accessibility Insights tool (or the Inspect) doesn't show all the `ControlBox` buttons from the menu strip.
![image](https://user-images.githubusercontent.com/87859299/143433185-0b58c322-ec0e-4254-b201-685d51ac2382.png) (no `Restore` and `Close` buttons)
![image](https://user-images.githubusercontent.com/87859299/143436323-edb1e85c-685a-4a4b-8939-53b7aab9581b.png) (no `Restore` and `Close` buttons)
![image](https://user-images.githubusercontent.com/87859299/143436195-0fd7f503-e8b9-46a6-9602-8049ba430a84.png) (no `Minimize` and `Restore` buttons if the MenuStrip has no items)

**Expected behavior:**
To have all the `ControlBox` buttons at UIA tools in the same order they are at the menu bar: `Minimize`, `Restore`, `Close`.

**Minimal repro:**
1. Run the attached test app.
2. Point the Accessibility Insights or the Inspect tool at the app, and examine the `My Test` menu bar of the child MDI window.

[WinFormsApp1_Core.zip](https://github.com/dotnet/winforms/files/7602737/WinFormsApp1_Core.zip)

**Comment by Lydia-Shi** [comment]
Verifies this issue with latest .NET 7.0.100-alpha.1.22060.5, this issue is fixed. Accessibility Insights and Inspect shows all the ControlBox buttons from the menu strip.
![image](https://user-images.githubusercontent.com/54019172/148902785-6ab53270-9608-478c-bbeb-85c8c5af7add.png)
![image](https://user-images.githubusercontent.com/54019172/148902456-bda79783-98ef-44cf-aebb-d57c20d34713.png)
