### ISSUE TITLE
VS2019 Crashes when adding reference

### ISSUE THREAD

**Issue by Notplayingallday383** [dotnet/winforms#6243]
Hello, I am trying to add a dll file to my C# Project and whenever I do vs just freezes then crashes. Does anyone know how to fix this issue without uninstalling VS?

**Comment by Notplayingallday383** [comment]
This doesn't happen with .Net Components because I tried it and it didn't crash

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.

Please post the link to the VS Feedback issue here, so that our team can track it.
