### ISSUE TITLE
The accessibility rectangle is drawn incorrectly for a dynamically added ListViewGroup.

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6306]
.NET Core Version: 
- 7.0.0-alpha.1.21576.4

Have you experienced this same bug with .NET Framework?: 
- No (from .NET Core 6.0)

**Repro steps:**
1. Create a `Form` with a `ListView` and a `Button`.
2. Add an event for a `Button` to add multiple `ListViewGroups` with `ListViewItems`.
3. Run the application
4. Add `ListViewGroups` using the `Button`
5. Get accessibility rectangle for `ListViewGroup` (using `Inspect`)

**Actual behavior:**
The rectangle for the `ListViewGroup` is displayed incorrectly.
![image](https://user-images.githubusercontent.com/23376742/145034311-3a51a6e5-899a-49f0-8997-4f72c76e1986.png)

**Expected behavior:**
The rectangle for the `ListViewGroup` should be displayed correctly.
![image](https://user-images.githubusercontent.com/23376742/145034658-f212aaf3-f2dd-4efb-8ee2-ac19d0b15d57.png)

**Comment by jbhensley** [comment]
I think the immediate problem can be fixed by replacing:

https://github.com/dotnet/winforms/blob/9eb2879946d89cd4eb201fab3ade9f192e2911e2/src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs#L169-L180

with

``` C#
private int GetNativeGroupId()
{
	if (User32.SendMessageW(_owningListView, (User32.WM)LVM.HASGROUP, _owningGroup.ID) == 0)
	{
		return -1;
	}

	return _owningGroup.ID;
}
```

But I'm seeing other places where positional index is being used in place of `ListViewGroup.ID` like this:

https://github.com/dotnet/winforms/blob/9eb2879946d89cd4eb201fab3ade9f192e2911e2/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs#L273

I'm wondering why `ListViewGroup.ID` is not being used instead, given that is the unique identifier that ties the managed group to the native one.

The problem at large is that the default group, which consumes a positional index, may or may not be inserted into the native control. If `ListView.IsHandledCreated` then a call to `ListView.Groups.Add` will result in the default group being added to the native control if not already present. However, if you instantiate a new `ListView`, add a bunch of groups to it, and then add it to a form (so that it's handle had not been created before groups were added) then it will not contain the default group. Any subsequent group added would then insert the default group. Here's how it breaks down if you insert three groups:

- `ListView.IsHandledCreated == false`

| Index | LVGROUP.iGroupId | LVGROUP.pszHeader |
| ----- | ----- | ----- |
| 0 | 0 | Group 1 |
| 1 | 1 | Group 2 |
| 2 | 2 | Group 3 |

- `ListView.IsHandledCreated == true`

| Index | LVGROUP.iGroupId | LVGROUP.pszHeader |
| ----- | ----- | ----- |
| 0 | 1 | Default |
| 1 | 0 | Group 1 |
| 2 | 2 | Group 2 |
| 3 | 3 | Group 3 |

And this is why the current implementation of `GetNativeGroupId` doesn't work. The `CurrentIndex` property that it uses attempts to correct for the default group, but only does so by checking that we need a default group, not that the group has actually been added to the native control.

Am I missing something about why indexes are being used instead of `ListViewGroup.ID`?

**Comment by Amy-Li03** [comment]
Verified this issue on .NET SDK 7.0.100-preview.3.22179.4 build, issue was fixed, now the rectangle for the ListViewGroup is displayed correctly.
![image](https://user-images.githubusercontent.com/62929087/161928664-4ac74a30-7acb-4dc1-9eb3-ec8df37ea9c1.png)
