### ISSUE TITLE
vs 2022 Win forms app on windows 11

### ISSUE THREAD

**Issue by khaledafifi** [dotnet/winforms#6483]
the designer doesn't open and says "Loading designer ..... " 
vs 2022 - build: 17.0.4
app: WinForms
framework: .net 6

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.

Please post the link to the VS Feedback issue here, so that our team can track it.
