### ISSUE TITLE
The border color of the pressed  popup CheckBox/RadioButton has low contrast

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6560]
Porting from Framework.

.NET Core Version: 
- 7.0.0-preview.2.22075.9

Have you experienced this same bug with .NET Framework?: 
- Yes

**Repro steps:**
1. Create a `Form` with a `Checkbox` or `RadioButton`
2. Set the following setting (`Appearance = Appearance.Button`)
3. Run the app
4. Pressed button

**Actual behavior:**
The color contrast of the button border is less than 3:1:
![image](https://user-images.githubusercontent.com/23376742/151359434-56561c80-9c40-4b9a-a629-5b3b2510f49d.png)

**Expected behavior:**
Luminosity contrast ratio of the button border is greater than 3:1.

**Comment by Ashley-Li** [comment]
Verified with .NET SDK 7.0.100-preview.3.22153.11 build, after step4, pressed button, the color of the button border is blue instead of gray, but I see that your fix in this PR:[6562 ](https://github.com/dotnet/winforms/pull/6562)does not match my result, am I doing something wrong?
![image](https://user-images.githubusercontent.com/56664234/156732792-5c0c9b3c-eafc-4c40-9287-075618134ce7.png)

**Comment by MelonWang1** [comment]
Verified with .NET SDK 7.0.100-preview.4.22201.11 build, this issue is fixed.
![Screenshot 2022-04-01 231916](https://user-images.githubusercontent.com/94418985/161372910-53b3fd69-db18-4e60-8474-7ce61a7ea777.png)

**Comment by MelonWang1** [comment]
Verified this issue with .NET SDK 7.0.100-preview.3.22179.4 build, this issue was fixed.
