### ISSUE TITLE
C# Winforms .Net 5: Load() of base UC is called before Ctor of derived UC is finished

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/winforms#6565]
.NET 5.0.13
VS 2019: v.16.11.9
both x86 and x64

Have you experienced this same bug with .NET Framework?: 
NO

I first seeked for advice on my problem on stackoverflow (https://stackoverflow.com/questions/70882286/, contains some kind of history and other details), but I think it also belongs here, because this is where the relevant developers are active.

We have migrated our projects from .Net Framework 4.8 to .Net 5.
Now we see a very strange issue: If the display language of our application is set to something different than English, we get an Exception during the application start.
The exception is raised in a UserControl with 3 levels of inheritance:
- base, lets call it UCImageObject
- first derived UCImageObjectStandard : UCImageObject
- second derived UCImgObjStd_Circle : UCImageObjectStandard

UCImageObjectStandard contains another UC ("UCTolerance") with `AutoScaleMode=DPI` and some Labels with `AutoSize=true`.
If the language remains English, the label's text is not changed, because the english-coded texts on the labels are identical with the english texts from our language database. Therefore, the label's size also stays the same. And then there is no need to scale them:
(I stepped through the .Net 5.0.13 source code to find out)
`System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)`
line 10131: `if (includedSpecified != BoundsSpecified.None)` is false, if the label's text and size are not changed.

IF the language is set to anything but english, the label's text and size are changed, and the `ScaleControl()` (line 10133) is executed. The problem is, that finally a handle of `UCImageObject` is created and its `Load` event is raised (see stack frame 82 in the following stacktrace), although the constructors of `UCImageObjectStandard` has not been finished (stack frame 41).
The `Load()` event method of `UCImageObject` then calls a virtual `Init()` method, which is overridden in `UCImageObjectStandard`. The `UCImageObjectStandard.Init()` is then executed before the `UCImageObjectStandard..ctor` has finished, which of course is wrong, and in our case this causes the exception.

The strange thing is, that this has worked well for years in .Net Framework 4.8. But it seems that changes have been made in .Net Core or .Net 5.
I think I have recently read a probably related issue about the early creation (or late? or in wrong order?) of a Winforms UC handle, but I cannot find it anymore.

**Can anybody tell me what has changed?**
**It's wrong to call an overridden method in the ctor of classes that use inheritance. But should we also avoid calling an overridden method in the Load event?**

Stacktrace (frame numbers added by me):
82   at SMCore.UIWF.UCImageObject.UCImageObject_Load(Object i_sender, EventArgs i_eventArgs)
81   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
80   at System.Windows.Forms.UserControl.OnCreateControl()
79   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
78   at System.Windows.Forms.Control.CreateControl()
77   at System.Windows.Forms.Control.WmShowWindow(Message& m)
76   at System.Windows.Forms.Control.WndProc(Message& m)
75   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
74   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
73   at System.Windows.Forms.UserControl.WndProc(Message& m)
72   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
71   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
70   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
69   at Interop.User32.CreateWindowExW(WS_EX dwExStyle, Char* lpClassName, String lpWindowName, WS dwStyle, Int32 X, Int32 Y, Int32 nWidth, Int32 nHeight, IntPtr hWndParent, IntPtr hMenu, IntPtr hInst, Object lpParam)
68   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
67   at System.Windows.Forms.Control.CreateHandle()
66   at System.Windows.Forms.Control.get_Handle()
65   at System.Windows.Forms.Control.get_ShowKeyboardCues()
64   at System.Windows.Forms.ControlPaint.CreateTextFormatFlags(Control control, ContentAlignment textAlign, Boolean showEllipsis, Boolean useMnemonic)
63   at System.Windows.Forms.Label.CreateTextFormatFlags(Size constrainingSize)
62   at System.Windows.Forms.Label.GetPreferredSizeCore(Size proposedConstraints)
61   at System.Windows.Forms.Control.GetPreferredSize(Size proposedSize)
60   at System.Windows.Forms.Label.GetPreferredSize(Size proposedSize)
59   at System.Windows.Forms.Control.get_PreferredSize()
58   at System.Windows.Forms.Label.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
57   at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
56   at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
55   at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
54   at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
53   at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
52   at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
51   at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
50   at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
49   at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
48   at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
47   at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
46   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)
45   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
44   at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
43   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
42   at SMCore.UIWF.UCImageObjectStandard.InitializeComponent()
41   at SMCore.UIWF.UCImageObjectStandard..ctor()
40   at SMCore.UIWF.UCImgObjStd_Circle..ctor()
29   at SMCore.UIWF.UCImageObject.Create(EnumType i_type, UCImageObject& io_ucImageObject)
28   at SMCore.UIWF.UCImageObject.ShowData(UCImageObject& io_ucImageObject, CImageObject i_imageObject)
27   at DI.UIWF.UCJobCreatorSettings.ucImageObjectList_SelectionChanged(Object i_oSender, EventArgs i_oEventArgs)
26   at SMCore.UIWF.UCImageObjectList.OnSelectionChanged(Int32 i_imageObjectID)
25   at SMCore.UIWF.UCImageObjectList.dgvImageObjects_SelectionChanged(Object i_sender, EventArgs i_eventArgs)
24   at SMCore.UIWF.UCImageObjectList.ShowData(CImageObjectList i_imageObjectList)
23   at DI.UIWF.UCJobCreatorSettings.Init(CImageObjectList i_oImageObjectList, IList`1 i_listoImageAcquisitionDeviceInfo)
22   at DI_JobEditor.UIWF.frmMain.Init_UI_Settings()
21   at DI_JobEditor.UIWF.frmMain.frmMain_Load(Object i_oSender, EventArgs i_oEventArgs)
20   at System.Windows.Forms.Form.OnLoad(EventArgs e)
19   at System.Windows.Forms.Form.OnCreateControl()
18   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
17   at System.Windows.Forms.Control.CreateControl()
16   at System.Windows.Forms.Control.WmShowWindow(Message& m)
15   at System.Windows.Forms.Control.WndProc(Message& m)
14   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
13   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
12   at System.Windows.Forms.Form.WmShowWindow(Message& m)
11   at System.Windows.Forms.Form.WndProc(Message& m)
10   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
09   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
08   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
07   at Interop.User32.ShowWindow(IntPtr hWnd, SW nCmdShow)
06   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
05   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
04   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
03   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
02   at System.Windows.Forms.Application.Run(Form mainForm)
01   at DI_JobEditor.UIWF.Program.Main(String[] args)

**Minimal repro:**
not ready yet.

**Comment by RussKie** [comment]
Please provide a standalone repro for us to investigate.
________________________________
From: TobiasKnauss ***@***.***>
Sent: Friday, 28 January 2022 8:55 AM
To: dotnet/winforms ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/winforms] C# Winforms .Net 5: Load() of base UC is called before Ctor of derived UC is executed (Issue #6565)


.NET 5.0.13
VS 2019: v.16.11.9
both x86 and x64

Have you experienced this same bug with .NET Framework?:
NO

I first seeked for advice on my problem on stackoverflow (https://stackoverflow.com/questions/70882286/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F70882286%2F&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7C35f6553ff30244de4e9208d9e1dfbf61%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637789173374213863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uVtsryqGdy%2BmrjhaHxLIn3y0lEj%2B7LAi5oistsFL5No%3D&reserved=0>, contains some kind of history and other details), but I think it also belongs here, because this is where the relevant developers are active.

We have migrated our projects from .Net Framework 4.8 to .Net 5.
Now we see a very strange issue: If the display language of our application is set to something different than English, we get an Exception during the application start.
The exception is raised in a UserControl with 3 levels of inheritance:

  *   base, lets call it UCImageObject
  *   first derived UCImageObjectStandard : UCImageObject
  *   second derived UCImgObjStd_Circle : UCImageObjectStandard

UCImageObjectStandard contains another UC ("UCTolerance") with AutoScaleMode=DPI and some Labels with AutoSize=true.
If the language remains English, the label's text is not changed, because the english-coded texts on the labels are identical with the english texts from our language database. Therefore, the label's size also stays the same. And then there is no need to scale them:
(I stepped through the .Net 5.0.13 source code to find out)
System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
line 10131: if (includedSpecified != BoundsSpecified.None) is false, if the label's text and size are not changed.

IF the language is set to anything but english, the label's text and size are changed, and the ScaleControl() (line 10133) is executed. The problem is, that finally a handle of UCImageObject is created and its Load event is raised (see stack frame 82 in the following stacktrace), although the constructors of UCImageObjectStandard has not been finished (stack frame 41).
The Load() event method of UCImageObject then calls a virtual Init() method, which is overridden in UCImageObjectStandard. The UCImageObjectStandard.Init() is then executed before the UCImageObjectStandard..ctor has finished, which of course is wrong, and in our case this causes the exception.

The strange thing is, that this has worked well for years in .Net Framework 4.8. But it seems that changes have been made in .Net Core or .Net 5.
I think I have recently read a probably related issue about the early creation (or late? or in wrong order?) of a Winforms UC handle, but I cannot find it anymore.

Can anybody tell me what has changed?
It's wrong to call an overridden method in the ctor of classes that use inheritance. But should we also avoid calling an overridden method in the Load event?

Stacktrace (frame numbers added by me):
82 at SMCore.UIWF.UCImageObject.UCImageObject_Load(Object i_sender, EventArgs i_eventArgs)
81 at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
80 at System.Windows.Forms.UserControl.OnCreateControl()
79 at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
78 at System.Windows.Forms.Control.CreateControl()
77 at System.Windows.Forms.Control.WmShowWindow(Message& m)
76 at System.Windows.Forms.Control.WndProc(Message& m)
75 at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
74 at System.Windows.Forms.ContainerControl.WndProc(Message& m)
73 at System.Windows.Forms.UserControl.WndProc(Message& m)
72 at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
71 at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
70 at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
69 at Interop.User32.CreateWindowExW(WS_EX dwExStyle, Char* lpClassName, String lpWindowName, WS dwStyle, Int32 X, Int32 Y, Int32 nWidth, Int32 nHeight, IntPtr hWndParent, IntPtr hMenu, IntPtr hInst, Object lpParam)
68 at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
67 at System.Windows.Forms.Control.CreateHandle()
66 at System.Windows.Forms.Control.get_Handle()
65 at System.Windows.Forms.Control.get_ShowKeyboardCues()
64 at System.Windows.Forms.ControlPaint.CreateTextFormatFlags(Control control, ContentAlignment textAlign, Boolean showEllipsis, Boolean useMnemonic)
63 at System.Windows.Forms.Label.CreateTextFormatFlags(Size constrainingSize)
62 at System.Windows.Forms.Label.GetPreferredSizeCore(Size proposedConstraints)
61 at System.Windows.Forms.Control.GetPreferredSize(Size proposedSize)
60 at System.Windows.Forms.Label.GetPreferredSize(Size proposedSize)
59 at System.Windows.Forms.Control.get_PreferredSize()
58 at System.Windows.Forms.Label.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
57 at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
56 at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
55 at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
54 at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
53 at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
52 at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
51 at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
50 at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
49 at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
48 at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl, Boolean updateWindowFontIfNeeded)
47 at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
46 at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)
45 at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
44 at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
43 at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
42 at SMCore.UIWF.UCImageObjectStandard.InitializeComponent()
41 at SMCore.UIWF.UCImageObjectStandard..ctor()
40 at SMCore.UIWF.UCImgObjStd_Circle..ctor()
29 at SMCore.UIWF.UCImageObject.Create(EnumType i_type, UCImageObject& io_ucImageObject)
28 at SMCore.UIWF.UCImageObject.ShowData(UCImageObject& io_ucImageObject, CImageObject i_imageObject)
27 at DI.UIWF.UCJobCreatorSettings.ucImageObjectList_SelectionChanged(Object i_oSender, EventArgs i_oEventArgs)
26 at SMCore.UIWF.UCImageObjectList.OnSelectionChanged(Int32 i_imageObjectID)
25 at SMCore.UIWF.UCImageObjectList.dgvImageObjects_SelectionChanged(Object i_sender, EventArgs i_eventArgs)
24 at SMCore.UIWF.UCImageObjectList.ShowData(CImageObjectList i_imageObjectList)
23 at DI.UIWF.UCJobCreatorSettings.Init(CImageObjectList i_oImageObjectList, IList`1 i_listoImageAcquisitionDeviceInfo)
22 at DI_JobEditor.UIWF.frmMain.Init_UI_Settings()
21 at DI_JobEditor.UIWF.frmMain.frmMain_Load(Object i_oSender, EventArgs i_oEventArgs)
20 at System.Windows.Forms.Form.OnLoad(EventArgs e)
19 at System.Windows.Forms.Form.OnCreateControl()
18 at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
17 at System.Windows.Forms.Control.CreateControl()
16 at System.Windows.Forms.Control.WmShowWindow(Message& m)
15 at System.Windows.Forms.Control.WndProc(Message& m)
14 at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
13 at System.Windows.Forms.ContainerControl.WndProc(Message& m)
12 at System.Windows.Forms.Form.WmShowWindow(Message& m)
11 at System.Windows.Forms.Form.WndProc(Message& m)
10 at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
09 at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
08 at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
07 at Interop.User32.ShowWindow(IntPtr hWnd, SW nCmdShow)
06 at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
05 at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
04 at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
03 at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
02 at System.Windows.Forms.Application.Run(Form mainForm)
01 at DI_JobEditor.UIWF.Program.Main(String[] args)

Minimal repro:
not ready yet.

**Comment by TobiasKnauss** [comment]
@RussKie I will try to create one. Hopefully it won't become too big. 
If already possible please answer my 2nd question: are virtual/overridden methods in Load() wrong?
From your request for a repro solution I think no, so it seems to be a bug?

**Comment by dreddy-work** [comment]
We did few changes around how the handles created to improve performance. Earlier, accessing control handle would create Handle if not created by then, this behavior changed in core to improve perf and predict the order of handle creation more precisely.  @TobiasKnauss , did you compare call stack between 4.8 and 5.0 here?

**Comment by TobiasKnauss** [comment]
I am almost ready to provide a repro solution. I was able to strip about 99.9% of the unnecessary code away.

@dreddy-work: No, I did not, because the problem does not appear in .Net 4.8, so I never got to the point where I have a similar call stack.
And all tries to step through the .net 4.8 soruce code of Winforms classes failed: I could step into "normal" classes like string or StringBuilder, but not into Winforms classes. Seems to be a well-known problem; I have found reports on stackoverflow about that, e.g. https://stackoverflow.com/a/51070532.

**Comment by TobiasKnauss** [comment]
I have now removed 99.999% of the original code: [di-software.zip](https://github.com/dotnet/winforms/files/7962713/di-software.zip)

- Run "dotnet restore", then execute. It will work as expected.

- Add one space in `UCTolerance.Designer.cs` in line 42 at the end of the string:
`this.lblLowerTolerance_long.Text = "Lower Tolerance ";`
The execution will fail in `UCImgObjStd_Circle.cs` in line 36, which is marked with `// ERROR HERE`, because the ctor of this class has not been finished yet.

**Comment by dreddy-work** [comment]
@Olina-Zhang , can you try this repro on latest bits (both 7.0and also on 6.0) and see if we can repro it locally?

**Comment by Philip-Wang01** [comment]
@dreddy-work We verified this issue in .NET 5.0, 6.0 and 7.0, this issue only repro on 5.0, not repro on 6.0 and 7.0, please see following video：

.NET 5.0:
![5 0](https://user-images.githubusercontent.com/86937911/152942015-9fd50e88-eff6-4c9f-8b20-44e4cc3c62ea.gif)

.NET7.0:
![70](https://user-images.githubusercontent.com/86937911/152942047-4881e4fb-e03f-4336-b38b-cfeaf3ba9544.gif)

**Comment by TobiasKnauss** [comment]
@Philip-Wang01 thanks for your effort!
Can you say whether it is a bug in .NET 5? If so, will there be a fix for it?

**Comment by dreddy-work** [comment]
> @Philip-Wang01 thanks for your effort! Can you say whether it is a bug in .NET 5? If so, will there be a fix for it?

.NET 5.0 does not have long term support and our servicing bar there doesn't allow bug fixes without considerable business justification. .NET 6.0 has long term support. Can you update your app to .NET 6.0 and see if you still face this issue?  Please feel free to reopen this issue if you still see the issue with .NET6.0.

**Comment by TobiasKnauss** [comment]
@Philip-Wang01 okay, I understand. Thank you all for your support. Unfortunately, .NET 6 requires updating VS from 2019 to 2022, which we need to buy. Using .NET 6 is on our plan, but not short-term.
Our workaround is setting `AutoScaleMode=None` because we don't use it anyway. We will use .NET 6 in the future for different reasons, and the bugfix for this issue is one of it, to avoid that this problems will arise again.
