### ISSUE TITLE
Windows Automation RaiseAutomationPropertyChangedEvent throws System.NotSupportedException

### ISSUE THREAD

**Issue by gc-maximloverov** [dotnet/winforms#6965]
### .NET version

6.0

### Did it work in .NET Framework?

No

### Issue description

Windows Automation RaiseAutomationPropertyChangedEvent method for BoundingRectangleProperty throws System.NotSupportedException 'Type 'System.Windows.Rect' cannot be marshalled to a Variant. Type library is not registered.'.
No exception is thrown if the AutomationPropertyChangedEvent values are null.

### Steps to reproduce

1. Run attached app:
[UiaNotSupportedException6.zip](https://github.com/dotnet/winforms/files/8416069/UiaNotSupportedException6.zip)
2. Press button "button1"
3. Observe thrown System.NotSupportedException

**Comment by dreddy-work** [comment]
Thanks @gc-maximloverov for reporting this. @vladimir-krestov , can you take a look at this scenario and see what we can do?

**Comment by dmitrii-drobotov** [comment]
@gc-maximloverov It looks like `RaiseAutomationPropertyChangedEvent` calls Win32 API function [UiaRaiseAutomationPropertyChangedEvent ](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/nf-uiautomationcoreapi-uiaraiseautomationpropertychangedevent), which accepts `oldValue` and `newValue` as VARIANTs. Variants are intended to hold primitive types rather than custom types like `System.Windows.Rect`, hence the exception. I don't see if there is something we can do on the Winforms side to resolve it.

However, I did find the unmarshalling [function](https://github.com/dotnet/wpf/blob/59dbc29569d5cf693061580b9998ad3689aa71fa/src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/Schema.cs#L151) which converts `object` to `Rect` for setting the  `BoundingRectangleProperty`. It uses `double[]` containing `left, top, width, height` values of `Rect`. I assume that following way of creating event args should work without exceptions:
```
new AutomationPropertyChangedEventArgs(AutomationElement.BoundingRectangleProperty,
    new double[] { oldRect.X, oldRect.Y, oldRect.Width, oldRect.Height },
    new double[] { newRect.X, newRect.Y, newRect.Width, newRect.Height })
```

**Comment by gc-maximloverov** [comment]
@dmitrii-drobotov it works, thanks!
