### ISSUE TITLE
Timed out while connecting to named pipe: DesignToolsServer.9e32d169-ddf5-4473-a4af-3f8d634b3fdc

### ISSUE THREAD

**Issue by FTricoire** [dotnet/winforms#6990]
### Environment

Microsoft Visual Studio Community 2022
Version 17.1.3
VisualStudio.17.Release/17.1.3+32328.378
Microsoft .NET Framework
Version 4.8.04084

Version installée : Community

ASP.NET and Web Tools 2019   17.1.358.51495
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.1.358.51495
Pour plus d'informations, visitez https://www.asp.net/

Azure Functions and Web Jobs Tools   17.1.358.51495
Azure Functions and Web Jobs Tools

CleanBinAndObjCommand Extension   1.2.58
CleanBinAndObjCommand Visual Studio Extension Detailed Info

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Débogage de .NET Core avec WSL   1.0
Débogage de .NET Core avec WSL

Extensions des outils de conteneur Visual Studio   1.0
Affichez, gérez et diagnostiquez les conteneurs dans Visual Studio.

Gestionnaire de bibliothèques Microsoft   2.1.161+abc97ecc7d.RR
Installez facilement des bibliothèques côté client dans n'importe quel projet web

Gestionnaire de package NuGet   6.1.0
Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, visitez https://docs.nuget.org/

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Outils Azure App Service v3.0.0   17.1.358.51495
Outils Azure App Service v3.0.0

Outils C#   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Composants C# utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Outils TypeScript   17.0.1229.2001
Outils TypeScript pour Microsoft Visual Studio

Outils Visual Basic   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Composants Visual Basic utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Package hôte de l'adaptateur de débogage de Visual Studio Code   1.0
Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio

Razor (ASP.NET Core)   17.0.0.2206201+62a2c1d6162f828801565a7ca26d9d48b810a05b
Fournit des services de langage pour ASP.NET Core Razor.

ResX Resource Manager   ResXManager
Manage localization of all ResX-based resources in one place. Shows all resources of a solution and lets you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   17.0.62203.25080
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
Développement assisté par intelligence artificielle pour Visual Studio.

Visual Studio Tools pour Conteneurs   1.0
Visual Studio Tools pour Conteneurs

Visual Studio Tools pour Docker   1.2
Développez, exécutez et validez vos applications ASP.NET Core dans l'environnement cible. Appuyez sur F5 pour exécuter votre application directement dans un conteneur avec débogage ou sur CTRL+F5 pour modifier et actualiser votre application sans avoir à recréer le conteneur.

### .NET version

.NET 5.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

I've never experienced this problem on Visual Studio 2019, and it's only since few weeks that I have it on Visual Studio 2022.

### Issue description

I've seen the problem on issue #6492  and #6705 but the conclusion was that the timeout was set to 2 minutes and in 17.2 we will have the ability to increase it.

Does it mean that the design will take 10 minutes (for example) to load whereas on Visual Studio 2019 it was almost instant ?

### Steps to reproduce

I just have to open a Winform Design to have the issue.

**Comment by RussKie** [comment]
> Does it mean that the design will take 10 minutes (for example) to load whereas on Visual Studio 2019 it was almost instant ?

No, it doesn't work that way. Before we can help you with the issue, we'll need the designer diagnostics. Please refer to https://aka.ms/winforms/designer/troubleshooting.

I also encourage you to install the latest [VS Preview](https://docs.microsoft.com/visualstudio/releases/2022/release-notes-preview), which has an improved diagnostics.
________________________________
From: FTricoire ***@***.***>
Sent: Friday, 8 April 2022 11:32 PM
To: dotnet/winforms ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/winforms] Timed out while connecting to named pipe: DesignToolsServer.9e32d169-ddf5-4473-a4af-3f8d634b3fdc (Issue #6990)


Environment

Microsoft Visual Studio Community 2022
Version 17.1.3
VisualStudio.17.Release/17.1.3+32328.378
Microsoft .NET Framework
Version 4.8.04084

Version installée : Community

ASP.NET and Web Tools 2019 17.1.358.51495
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019 17.1.358.51495
Pour plus d'informations, visitez https://www.asp.net/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.asp.net%2F&data=05%7C01%7Cigor.velikorossov%40microsoft.com%7C3eabd3b017e3442e919408da19643cb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637850215557397105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yk1T%2FLUWhF3sskfkRdPuy%2BrfdS2M%2FglWyxbbbpGL5sg%3D&reserved=0>

Azure Functions and Web Jobs Tools 17.1.358.51495
Azure Functions and Web Jobs Tools

CleanBinAndObjCommand Extension 1.2.58
CleanBinAndObjCommand Visual Studio Extension Detailed Info

Common Azure Tools 1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Débogage de .NET Core avec WSL 1.0
Débogage de .NET Core avec WSL

Extensions des outils de conteneur Visual Studio 1.0
Affichez, gérez et diagnostiquez les conteneurs dans Visual Studio.

Gestionnaire de bibliothèques Microsoft 2.1.161+abc97ecc7d.RR
Installez facilement des bibliothèques côté client dans n'importe quel projet web

Gestionnaire de package NuGet 6.1.0
Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, visitez https://docs.nuget.org/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.nuget.org%2F&data=05%7C01%7Cigor.velikorossov%40microsoft.com%7C3eabd3b017e3442e919408da19643cb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637850215557397105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mYpHKa5CNRxw4XrnSSwl9dsowiHssQnY3aEa7FGIA%2Bs%3D&reserved=0>

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger 1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Outils Azure App Service v3.0.0 17.1.358.51495
Outils Azure App Service v3.0.0

Outils C# 4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Composants C# utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Outils TypeScript 17.0.1229.2001
Outils TypeScript pour Microsoft Visual Studio

Outils Visual Basic 4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Composants Visual Basic utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Package hôte de l'adaptateur de débogage de Visual Studio Code 1.0
Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio

Razor (ASP.NET Core) 17.0.0.2206201+62a2c1d6162f828801565a7ca26d9d48b810a05b
Fournit des services de langage pour ASP.NET Core Razor.

ResX Resource Manager ResXManager
Manage localization of all ResX-based resources in one place. Shows all resources of a solution and lets you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools 17.0.62203.25080
Microsoft SQL Server Data Tools

StylerPackage Extension 1.0
StylerPackage Visual Stuido Extension Detailed Info

Visual F# Tools 17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools

Visual Studio IntelliCode 2.2
Développement assisté par intelligence artificielle pour Visual Studio.

Visual Studio Tools pour Conteneurs 1.0
Visual Studio Tools pour Conteneurs

Visual Studio Tools pour Docker 1.2
Développez, exécutez et validez vos applications ASP.NET Core dans l'environnement cible. Appuyez sur F5 pour exécuter votre application directement dans un conteneur avec débogage ou sur CTRL+F5 pour modifier et actualiser votre application sans avoir à recréer le conteneur.

.NET version

.NET 5.0

Did this work in a previous version of Visual Studio and/or previous .NET release?

I've never experienced this problem on Visual Studio 2019, and it's only since few weeks that I have it on Visual Studio 2022.

Issue description

I've seen the problem on issue #6492<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fissues%2F6492&data=05%7C01%7Cigor.velikorossov%40microsoft.com%7C3eabd3b017e3442e919408da19643cb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637850215557397105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5Teeri4AnMFt%2BVG%2FiLtm3m2M9ADAFTwyENzoI%2FP5XT8%3D&reserved=0> and #6705<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fissues%2F6705&data=05%7C01%7Cigor.velikorossov%40microsoft.com%7C3eabd3b017e3442e919408da19643cb4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637850215557397105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oaFthwSDlNegF4nCEkvTPBWNPrYaoHFVEKIR0zLdzpo%3D&reserved=0> but the conclusion was that the timeout was set to 2 minutes and in 17.2 we will have the ability to increase it.

Does it mean that the design will take 10 minutes (for example) to load whereas on Visual Studio 2019 it was almost instant ?

Steps to reproduce

I just have to open a Winform Design to have the issue.

Diagnostics

No response

**Comment by FTricoire** [comment]
Sorry for the wait but I couldn't find the time to send the information needed, i'll do this soon.
