### ISSUE TITLE
Please DELETE THE ISSUE.

### ISSUE THREAD

**Issue by kelilive** [dotnet/winforms#7017]
### Environment

Visual Studio version: 17.1.2

### .NET version

ALL

### Did this work in a previous version of Visual Studio and/or previous .NET release?

No

### Issue description

![image](https://user-images.githubusercontent.com/23723575/163394273-cfb3e519-d5d5-409a-a00d-e3a74b55e5b8.png)

My local region is `zh-CN` and OS is `en-US`. So at runtime, the corresponding resources should be automatically recognized after the multi-language setting. But the runtime is English content. In this regard, I traced the code and found that the patch  `resourceCulture =  CultureInfo.CurrentCulture`(**Not a good solution**) can be specified in Strings resources. But for the **Form.resx**, I can't do anything about it. I think there is a serious flaw, if not well explained.

### Steps to reproduce

Nothing

### Diagnostics

```text
Nothing
```

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/163398283-ee6418d9-c599-4ea5-8020-012626f2bd6b.png)

**Comment by kelicto** [comment]
zh-CN or zh-Hans resx are invalid.

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/163398715-5fc19595-5b45-40a5-80d3-0d33646391bc.png)

**Comment by kelicto** [comment]
Please fix these problems properly, thanks a lot. They are creating panic and make me hesitate whether this technology is already lacking to be put into maintenance and should be put into a more reliable and trustworthy UI framework.

**Comment by KlausLoeffelmann** [comment]
Hello kelicto,

thanks for reporting this issue.
I will take a look at this. 
I would need some assistance from you.

> I traced the code and found that the patch `resourceCulture = CultureInfo.CurrentCulture` (Not a good solution) can be specified in Strings resources.

I don't understand exactly what you are referring to. 
Can you be a bit more specific, and show the code you think of? 
That would be helpful to understand your problem.

Could you also add this line of code in your _Program.cs_ file, and report the printout from the Debug window back here?

```
            Debug.WriteLine($"\nCurrent Culture: {CultureInfo.CurrentCulture.DisplayName}/" +
                $"UI Culture: {CultureInfo.CurrentUICulture.DisplayName}\n");
```

Like this:

![image](https://user-images.githubusercontent.com/9663150/163469954-e5063204-0b61-467b-98cb-02a3cd574568.png)

And then take a look in the Debug output window, what it prints out:

![image](https://user-images.githubusercontent.com/9663150/163470096-c16f382a-4a72-4fdb-a44c-45c6a9fc7b5f.png)

Thank you!

**Comment by kelicto** [comment]
Add code: `CultureInfo.CurrentUICulture = new CultureInfo("zh-CN");` 
It can work well.

**Comment by kelicto** [comment]
Before that, I had made a similarly large number of attempts, and I may have been careless.

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/163501188-4d976863-9d22-45d8-86c6-8a9ec99de785.png)

This seems to be a painful problem, inheritance failure? The designer does not read multilingual resources well.

**Comment by kelicto** [comment]
This problem will be even more fatal, I will be using form inheritance a lot in different projects and if the designer does not display properly, it will cause a lot of disruption to my usage.

**Comment by kelicto** [comment]
Whether to keep only the text-related, if it has to be so designed. I personally still prefer to use `zh-Hans.resx` and add resources directly through the explorer instead of resetting values on the designer (automatically creating `zh-CN.resx`, which I prefer to have nothing to do with the country but with the language, is better to automatically adapt to zh-Hans after setting the region).

And isn't it more popular to use this approach?

![image](https://user-images.githubusercontent.com/23723575/163502623-93886fd1-1468-4fe8-9bd3-3562f80405b5.png)

**Comment by KlausLoeffelmann** [comment]
It's hard to understand it just from the screenshots.
A sample app with comments in it would be very helpful.

Thank you!

**Comment by kelicto** [comment]
Hmm. I will try to upload it sometime.

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/164125732-3def8be7-ba16-45db-8435-4a62324a6e75.png)

Weird language differentiation display.

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/164126345-cd6223e5-ae6c-4d8b-b66a-6dcad28e9e94.png)
Lots of confusion and unreliability.

**Comment by kelicto** [comment]
Multilingual resource access becomes unreliable across solutions.
[Bug Video.zip](https://github.com/dotnet/winforms/files/8528691/Bug.zip)

I have to give up on multilingual solutions for now, very disappointed.

**Comment by KlausLoeffelmann** [comment]
@Olina-Zhang, could you help me to understand exactly the problem here, maybe lead a conversation to clarify facts in Chinese (but translate to English in parallel), or try to repro the issues here? I have tried a few things with English, German and some German sub-languages, but I wasn't able to repro the actual problem. I may be missing something.

**Comment by Olina-Zhang** [comment]
@kelicto Here is my understanding about your issue, I listed following repro steps, could you please confirm if it is yours? @KlausLoeffelmann 

**Issue description**: Inherited form cannot get the parent form's local resource setting

**Repro steps:**
0. VS: ENU, OS: CHS
1. Create a Winforms .Net framework app
2. Add 2 buttons to form1 designer
3. Set form1's localizable to True, and set form1's language to Chinese(Simplified)
4. Set 2 buttons' Text property to Chinese string: "确定"， "取消"
5. Build and run application
6. Add a new item: form2, choose inherited this designed form1

**Result:** In form2, the 2 buttons are still displayed with English string, because the form2's localizable is false, it needs to edit form2 as form1 designed.
![image](https://user-images.githubusercontent.com/26474449/164586771-a601cdff-f0e4-405c-831f-e71543b92b57.png)

**Comment by KlausLoeffelmann** [comment]
So the culprit here is picking up localized Forms in inherited-Form scenarios.
I'll take a look.

**Comment by kelicto** [comment]
> Hmm. I will try to upload it sometime. [Demo.zip](https://github.com/dotnet/winforms/files/8517821/Demo.zip)
> 
> Refer to the video file below for the operation steps.

Please use the demo, maybe it's unnecessary to reduce the trouble. Of course, now that you have mentioned it, I'll answer your question directly.

**Comment by kelicto** [comment]
> **Result:** In form2, the 2 buttons are still displayed with English string, because the form2's localizable is false, it needs to edit form2 as form1 designed.

NO. The property `Lcalizable` of `form2` is true.

**Comment by kelicto** [comment]
Strangely enough, some projects also use resx multilingual solutions, but they work well, why is that? For example, we use the DevExpress UI library, and version 21.1 searches for zh-Hans resource package to localize it easily and normally, but version 17.1 uses zh-CHS resource, even if it is set `System.Globalization. CultureInfo("zh-CHS");` explicitly point to the language pack still does not help.

**Comment by kelicto** [comment]
> but version 17.1 uses zh-CHS resource, even if it is set `System.Globalization.CultureInfo("zh-CHS");` explicitly point to the language pack still does not help.

The language pack does not contain corresponding resources.

**Comment by kelilive** [comment]
I am very stable now without this problem, maybe the resource file is missing something, please delete this Issue thanks, not close it.

**Comment by kelilive** [comment]
Please delete it, thanks!

**Comment by kelilive** [comment]
Please delete this issue, thanks! I've deleted all my content, what's the point of keeping it?

**Comment by kelilive** [comment]
I hope it is deleted, why can not listen to it? I think I expressed myself very clearly.

**Comment by KlausLoeffelmann** [comment]
We don't delete issues. We close them. That's the way it works.
