### ISSUE TITLE
Second DataGridView with CalendarColumn does not display data in the cells

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#7181]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Second-DataGridView-with-CalendarColumn-/10043008)._

---
[severity:It's more difficult to complete my work]
Using the CalendarColumn from the "How to: Host Controls in Windows Forms DataGridView Cells" documentation example, I have modified the program to create a DataTable to use as a source for the datagridview.
I use AutogenerateColumns=true and the ColumnAdded event to replace the textboxcolumn with the CalendarColumn. 
This works correctly for this first DataGridView.
I then duplicated the code to create a second DataGridView and second DataTable.
This second grid also uses AutoGenerateColumns and the ColumnAdded event to replace the textboxcolumn with the CalendarColumn. 
However, this second grid does not display values in the columns even though the column contains the CalendarColumn as can be show by editting a grid cell.
BUT, if I reverse the creation of the grids, by creating the second grid first, and the first grid second, then the second grid contains data but the first grid does not. To me this verifies that the code is correct. (ie. reverse lines 226 and 227, Build_grid_1() and Build_Grid_2() )
What is wrong, am I missing something?
PS. I am developing an application that needs to use a custom column in two grids displayed on the same form.
This is my test case. 
I will upload my test program.

---
#### glynn.stuber on 5/16/2022, 02:23 PM: 

(private comment, text removed)
#### Feedback Bot on 5/16/2022, 04:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Cassie-Li01** [comment]
**Repro Steps:**
1. Open attached application
2. Build and Run it
3. Observe
[WinFormsApp4.zip](https://github.com/dotnet/winforms/files/8698910/WinFormsApp4.zip)

**Current Behavior**
Second DataGridView with CalendarColumn does not display data in the cells
![Error](https://user-images.githubusercontent.com/96758262/168564988-9b0391c7-7043-48ee-851d-49ccbc54bc5d.PNG)
![Repro](https://user-images.githubusercontent.com/96758262/168565004-5a086972-cb5e-454b-8d06-f7472c42ba66.gif)

**Expected Behavior**
Second DataGridView with CalendarColumn does display data in the cells

**More info:**
1. This issue also repro on .NET Framework 
2. Repro on .Net Core 3.1/5.0/6.0
3. VS 2019/2022 17.1.7 and 17.2

**Comment by glynn-stuber** [comment]
This is NOT the expected behaviour.
The second grid should show/display the current cell values the same as the first grid.
When the form is shown, the second grid is blank, and only shows the value in the editor when edit is invoked in a cell.
This is not Normal behaviour. The grid should always show the current cell values,

**Comment by dreddy-work** [comment]
Thanks for reporting this. As the behavior is the same on .NET Framework, we're unlikely to make a change to the behavior. We'll take a look when we're able and see if there is a way to accomplish what you're trying to do.

Alternatively, there are other more suited channels to seek information (such as [docs](https://docs.microsoft.com/)) and ask questions (such as [Discussions](https://github.com/dotnet/winforms/discussions), [Gitter](https://gitter.im/dotnet/corefx), [Discord](https://discord.com/channels/732297728826277939/799788915371278377), [StackOverflow](https://stackoverflow.com/), etc.).

Thank you for understanding.

**Comment by Tanya-Solyanik** [comment]
@glynn-stuber  - please try moving DataGridView initializations to form constructor from Form.Shown handler.

```
  public Form1()
    {
        this.StartPosition = FormStartPosition.CenterScreen;
        this.dataGridView1.Dock = DockStyle.Top;
        this.dataGridView2.Dock = DockStyle.Bottom;
        this.Controls.Add(this.dataGridView1);
        this.Controls.Add(this.dataGridView2);

        dataGridView2.Left = dataGridView1.Left;
        dataGridView2.Top = dataGridView1.Bottom + 5;
        this.Shown += new EventHandler(Form1_Load);
        this.Text = "DataGridView calendar column demo";

        Buid_Grid_1();   <<<<
        Buid_Grid_2();   <<<<
    }
```

**Comment by glynn-stuber** [comment]
Tanya, 
Thank you for your reply and advice. 
I tried this and it worked, although I don't understand why.

**Comment by RussKie** [comment]
This may be related to timing of events, such as handle creation.
