### ISSUE TITLE
TextBox TextPattern objects are leaking in memory

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#7248]
### .NET version

.NET 7.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

If to use TextPattern abilities, UIA creates and keeps several UiaTextRanges, that keep UiaTextProvider and TextBox. So #6886 is not enough for fixing #6885. 
![image](https://user-images.githubusercontent.com/49272759/171450183-4f8d13e8-fc9e-4b62-816f-9856e5277589.png)

### Steps to reproduce

- Create a .NET app
- Add a TextBox there
- Run the app and Narrator/Inspect/AI
- Check TextPattern work, get some text ranges
- Close the test form to dispose the control
- Check how many object are leaking for the TextBox using WinDbg or something like that

**Comment by elachlan** [comment]
@dmitrii-drobotov did this get fixed? #7329 has this as the last issue in the list.

**Comment by Tanya-Solyanik** [comment]
Leak size had been reduced considerably - https://github.com/dotnet/winforms/pull/7295#issuecomment-1632551043, thus closing.

**Comment by dmitrii-drobotov** [comment]
In case it gets picked up later, I'll share a direction where we were looking into in order to fix it.

There is a [`UiaTextRangeRelease`](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/nf-uiautomationcoreapi-uiatextrangerelease) function in UIAutomationCore.dll, but it's deprecated with a suggestion to use UIA COM interfaces instead. I assume the equivalent would be to call [`Release`](https://learn.microsoft.com/en-us/windows/win32/api/unknwn/nf-unknwn-iunknown-release) function from IUnknown interface, which [`IUIAutomationTextRange`](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nn-uiautomationclient-iuiautomationtextrange) implements. Example in C++ which I found also simply call Release on UIATextRange object: https://github.com/microsoft/Windows-classic-samples/blob/ac06e54a15e9a62443e400fffff190fb978ea586/Samples/UIAutomationDocumentClient/cpp/UiaDocumentClient.cpp#L142-L160

To implement it in WinForms we could store all UiaTextRange objects in UIA providers, and when provider gets released, we would call Release (as `System.Runtime.InteropServices.Marshal.Release` or `Marshal.ReleaseComObject`) on text ranges. But when I tried to implement it, there still was a memory leak. 

We also have related code in the integration tests:
https://github.com/dotnet/winforms/blob/466b88460fffe560d5f497ec5de3d6ab125beb48/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/RichTextBoxTests.cs#L205-L254 
But trying to implement it in a similar way also didn't fix the leak. Nevertheless, I still think this is a good direction to look into and could work if implemented correctly, in case we ever get back to this issue.
