### ISSUE TITLE
CreateComponentsCore(IDesignerHost host, IDictionary defaultValues) throws NRE if CreateComponentsCore(IDesignerHost host) returns null

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#727]

**Comment by weltkante** [comment]
Personally I don't like this kind of change. The semantic was probably intended that CreateComponentsCore(IDesignerHost) never returns null. Thats a pretty common expectation and starting to check that overridable methods do not return null when they aren't supposed to, checking that in every caller, in my opinion is making the code worse. If you start checking overrides you technically also have to expect that they could throw exceptions and all callers handle them correctly.

My preferred fix would be to mark the return values of such overridable methods as non-nullable once the language supports it. Don't know though if thats possible when considering backwards compatibility.

That aside, I also don't like "array is null or empty" semantics, especially in the light of upcoming non-nullable language support. I think its perfectly reasonable if methods expect collection/array return values to be never null. There is Array.Empty to avoid allocations.

(Of course thats all just my opinion, I just want to make sure these points have been considered.)

**Comment by hughbe** [comment]
Couple of things. 

> The semantic was probably intended that CreateComponentsCore(IDesignerHost) never returns null.

Probably, but there is evidence against this in the implementation of `Toolbox.CreateComponents`
```cs
/// <summary>
/// Creates objects from the type contained in this toolbox item.  If designerHost is non-null
/// this will also add them to the designer.
/// </summary>
public IComponent[] CreateComponents(IDesignerHost host)
{
    OnComponentsCreating(new ToolboxComponentsCreatingEventArgs(host));
    IComponent[] comps = CreateComponentsCore(host, new Hashtable());
    if (comps != null && comps.Length > 0)
    {
        OnComponentsCreated(new ToolboxComponentsCreatedEventArgs(comps));
    }
    return comps;
}
```

Note that we explicitly check for `null`.

> Thats a pretty common expectation and starting to check that overridable methods do not return null when they aren't supposed to, checking that in every caller, in my opinion is making the code worse.
> My preferred fix would be to mark the return values of such overridable methods as non-nullable once the language supports it. Don't know though if thats possible when considering backwards compatibility.

Sadly, this has been considered in the case of whether or not to mark `object.ToString` as nullable or not: https://github.com/dotnet/corefx/blob/663af00ced6ba81a3a7715e6347270306c1bad52/Documentation/api-guidelines/nullability.md#virtualabstract-methods-and-interfaces

Finally, I'm open to the assessment that we allow `CreateComponentsCore` to return null, but return an empty array in `CreateComponents` if `CreateComponentsCore` returns null.

**Comment by hughbe** [comment]
For reference, here's the current implementation of `CreateComponentsCore`:
```cs
protected virtual IComponent[] CreateComponentsCore(IDesignerHost host, IDictionary defaultValues)
{
    IComponent[] components = CreateComponentsCore(host);

    if (host != null)
    {
       for (int i = 0; i < components.Length; i++) // Blows up here if `CreateComponentsCore` returns `null`
        {
            if (host.GetDesigner(components[i]) is IComponentInitializer init)
            {
                bool removeComponent = true;

                try
                {
                    init.InitializeNewComponent(defaultValues);
                    removeComponent = false;

                }
                finally
                {
                    if (removeComponent)
                    {
                        for (int index = 0; index < components.Length; index++)
                        {
                            host.DestroyComponent(components[index]);
                        }
                    }
                }

            }
        }
    }

    return components;
}
```

**Comment by weltkante** [comment]
Since the old CreateComponentsCore was triggering NRE I would expect this to fall under the following clause under your linked page:

> For existing virtual APIs that have already documented a guarantee about a non-nullable return, it's expected that the return type will be annotated as non-nullable, and derived types must continue to respect that guarantee, albeit now with the compiler's assistance.

In other words, since returning null wouldn't have worked before it would be safe to annotate it as non-nullable. It's "documented" by not having worked for 10+ years, by making your suggested change you would remove the current exception, implicitly allowing null return values, and thus making it impossible to later switch to a non-nullable return value.

Since the call site you quoted checking for null was calling the overload which throws NRE it would not change anything, current (working) implementors could not have returned null.

However given your other callsite I acknowledge that annotating `CreateComponentsCore(IDesignerHost)` as non-nullable might not be the best choice. Since both overloads are virtual you can't apply the same argument for the `CreateComponentsCore(IDesignerHost, IDictionary)` overload because there its callsite already did the checking and implementors may have returned null. Making one overload non-nullable but the other overload nullable would probably not be good API design.
