### ISSUE TITLE
WinForms ComboBox SelectedIndexChanged event behaves inconsistently

### ISSUE THREAD

**Issue by tcostin** [dotnet/winforms#730]
If the SelectedIndex property is set programatically, the event does not fire unless {new value <> old value}. However, if the user accesses the drop-down and selects an item (via the GUI), the event always fires (even in the case where the new value is the same as the old value).

Looking at the reference source, this can be traced to the fact that WmReflectCommand always calls OnSelectedIndexChanged() when processing CBN_SELCHANGE, but the SelectedIndex property setter compares old and new values before doing anything.

It's not 100% clear that this is a bug (there is some sense in working the way it does), but it is definitely misleading and should be documented if this behavior is by design.

**Comment by weltkante** [comment]
It is important that changing SelectedIndex to the same value does not re-trigger SelectedIndexChanged if I'm setting SelectedIndex from within SelectedIndexChanged, otherwise you could start getting infinite loops in code that previously worked just fine.

Our codebase certainly has places where it relies on this implicit behavior, not only for SelectedIndex but a lot of other properties with change handlers.

**Comment by IanMarteens** [comment]
I've been redirected here by a similar problem: SelectedIndexChanged not firing.  However, in this case, the problem happens if you assign SelectedIndex in the constructor, when there is no window handle yet. After that point, the event never fires again. It only happens in .NET Core. The full Framework handles this case OK.

**Comment by weltkante** [comment]
If you have a scenario where .NET Core and Full Framework are different you should probably create a new issue, as this one is marked as discussion and your case is more like a regression and will probably be adressed more immediately.

**Comment by IanMarteens** [comment]
Thanks. I'll do it.

**Comment by JeremyKuhne** [comment]
Closing until we see documentation of where we differ from .NET Framework.
