### ISSUE TITLE
hwndThatLostFocus doesn't work as expected

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#7617]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/hwndThatLostFocus-doesnt-work-as-expect/10114981)._

---
[severity:It bothers me. A fix would be nice]
The exact issue I have posted on Stackoverflow. Here is the url:
https://stackoverflow.com/questions/73288493/cant-escape-from-toolstriptextbox-in-a-particular-case

---
#### Feedback Bot on 8/10/2022, 01:43 PM: 

(private comment, text removed)
#### Cassie Li [MSFT] on 8/11/2022, 02:47 PM: 

(private comment, text removed)
#### 泡泡 羊 on 8/17/2022, 09:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Cassie-Li01** [comment]
[Accessibility]Can't escape from textbox using keyboard ESC

**Repro Steps:**
1. Create a winforms 
2. Add a menustrip with a textbox
3. Add KeyDown event of datagridview.
`if (e.KeyCode == Keys.F3)
    toolStripTextBox1.Focus();`
4. Build and run, click the datagridview to focus on it.
5. Press F3 to change focus.
6. Press Esc on your keyboard.
or open attached project 
[testapp.zip](https://github.com/dotnet/winforms/files/9378548/testapp.zip)

Current Behavior: 
Can't escape from textbox, Cursor always in textbox.  
In order to show the focus clearly, I launched Narrator to record gif. Please check 
![Actual result](https://user-images.githubusercontent.com/96758262/185522456-fbd932a7-ef79-4701-98da-09e7c40a3955.gif)

Expected Behavior:
Can escape form textbox and will focus on datagridview

Below steps is work well, I recorded expected result follow below steps: 
1. Click the datagridview to focus on it.
2. Click the textbox to change focus.
3. Press Esc on your keyboard.
![expected result](https://user-images.githubusercontent.com/96758262/185522697-b75c336c-8d4b-42fc-9909-3bc829955002.gif)

**Comment by dreddy-work** [comment]
@Cassie-Li01 , if this repro in .NET framework as well, how did you generate gif for expected behavior?

**Comment by Cassie-Li01** [comment]
@dreddy-work 
Below steps work well, I recorded expected result follow below steps:

1. Click the datagridview to focus on it.
2. Click the textbox to change focus.
3. Press Esc on your keyboard.

**Comment by merriemcgaw** [comment]
Esc alone wouldn't necessarily revert focus to the previous control. Can the user tab back to the DataGridView? That would satisfy accessibility requirements. Changing the behavior here would introduce a lot of potential for regressions and we aren't hearing other users need to use the Esc key to move focus in any direction. In fact, I'd believe that the Accessibility experts would flag this as bad behavior. Please close the underlying feedback ticket as low priority. If we get additional feedback from others we can reconsider.
