### ISSUE TITLE
[Accessibility] LinkLabel's color contrast is less than 4.5:1 when clicking it

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7726]
### .NET version

8.0.100-alpha.1.22451.15

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

LinkLabel's color contrast is less than 4.5:1 when clicking it on Win10 and Win11 default themes and high contrast themes

**Win10 and Win11 default themes:**
![image](https://user-images.githubusercontent.com/26474449/188084965-a741753f-44c9-4889-bb9b-b9ef74b364a4.png)

**Win11 high contrast themes:**
![image](https://user-images.githubusercontent.com/26474449/188086428-e684797d-611d-4564-9d69-08191928760e.png)

**Win10 high contrast themes:**
![image](https://user-images.githubusercontent.com/26474449/188087758-eb8ed88a-6351-4988-95cd-053be7066970.png)

### Steps to reproduce

Sample application:
[WinFormsApp11.zip](https://github.com/dotnet/winforms/files/9476100/WinFormsApp11.zip)

**Comment by merriemcgaw** [comment]
There is an open issue in System.Drawing from to expose new System Colors. We should wait until these are exposed and then see if we can get the Visited Link color in order to use it instead of being something we improvise. We should track for .NET 8 but it's not a high priority.

**Comment by merriemcgaw** [comment]
@dmitrii-drobotov / @vladimir-krestov which System Color are we using for the LinkLabel control?

**Comment by dmitrii-drobotov** [comment]
@merriemcgaw In this issue it's actually not the *visited* link color (that one is violet and has good contrast ratio) but rather the *active* link color, i.e. the one that is visible when you click on a link but not release it yet. For that we are trying to get IE's "Anchor Color Hover" from the registry. But on my machine (Win 11) it was not found, so in that case we default to `System.Drawing.Color.Red` which is simple #FF0000. It's also doesn't depend on whether it's a HC theme or not, so it's always red.
On screenshots from the description AI shows a little different color I think due to subpixel rendering for small fonts. If I use a bigger font to make sure text has a solid color it shows #FF0000.
![image](https://user-images.githubusercontent.com/102954094/189147066-227bbfd8-8899-4154-b473-3f0fff69cb22.png)

**Comment by merriemcgaw** [comment]
Ahhh, that makes a lot of sense. I think that the priority of this is much lower if it is only _while_ the user is clicking on the link. If the Visited and not-yet-visited link colors are good, I think we can close this as won't fix. @Tanya-Solyanik do you agree?

**Comment by vladimir-krestov** [comment]
I think, we can close this issue until a user request, because not-visited and visited states are long and users see them long time. But in most common cases clicking on the link process is so fast, so users may not notice that the color has changed to red at all.
Moreover this one-second state of link doesn't block users, they see clear what they will click and what they already clicked, they won't try to read what they are clicking in the moment, it looks like just an indicator of changing, in my opinion.
We can change the color but we will change that users used to see.
Thoughts?

**Comment by dmitrii-drobotov** [comment]
I do have a little concern though, we adapt to HC theme colors when it comes to visited and not-visited links:
![image](https://user-images.githubusercontent.com/102954094/189658524-eba722df-bfbb-49c7-87e5-876ec2f0ceca.png)
![image](https://user-images.githubusercontent.com/102954094/189658619-0df25713-d140-4411-ab5e-e29b8f9e2881.png)
![image](https://user-images.githubusercontent.com/102954094/189658572-2f5fd041-0e40-4122-a030-b5eb58049c5b.png)

But the active color is always red. Users can also change link color in theme settings, and if they set it to red then active state will be unnoticeable. But I'm not sure if it's something worth changing since it indeed shows up only for a split second.

**Comment by merriemcgaw** [comment]
I agree, not worth changing at this point.
