### ISSUE TITLE
TabControl.TabPageCollection.RemoveAt(int) removes wrong item!

### ISSUE THREAD

**Issue by albahari** [dotnet/winforms#7837]
### .NET version

All .NET versions to .NET 6

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Same bug in all previous .NET versions & .NET Framework

### Issue description

This RemoveAt method in System.Windows.Forms.TabControl.TabPageCollection has a horrible bug that can cause it to remove the wrong page from the TabControl.

There's only one line of code in the method, so the bug is obvious:

`owner.Controls.RemoveAt(index);`

You can see that it's applying the index to the **Controls** collection rather than the **TabPages** collection. These two collections are not the same; they can sometimes get out of sync when the SelectedTab changes. You used to be able to work around the bug by setting the [AllowUpdateChildControlIndexForTabControls application switch](https://learn.microsoft.com/en-us/dotnet/core/compatibility/winforms#allowupdatechildcontrolindexfortabcontrols-compatibility-switch-not-supported) to false, but this switch is no longer supported.

You can fix the bug by changing that line of code to:

`owner.Controls.Remove(this[index]);`

### Steps to reproduce

I don't think this is needed - the bug is obvious from looking at the one line of code.

**Comment by RussKie** [comment]
Thank you for raising this. Would you like to send a PR with a fix?
________________________________
From: albahari ***@***.***>
Sent: Saturday, 24 September 2022 4:50 PM
To: dotnet/winforms ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/winforms] TabControl.TabPageCollection.RemoveAt(int) removes wrong item! (Issue #7837)


.NET version

All .NET versions to .NET 6

Did it work in .NET Framework?

No

Did it work in any of the earlier releases of .NET Core or .NET 5+?

Same bug in all previous .NET versions & .NET Framework

Issue description

This RemoveAt method in System.Windows.Forms.TabControl.TabPageCollection has a horrible bug that can cause it to remove the wrong page from the TabControl.

There's only one line of code in the method, so the bug is obvious:

owner.Controls.RemoveAt(index);

You can see that it's applying the index to the Controls collection rather than the TabPages collection. These two collections are not the same; they can sometimes get out of sync when the SelectedTab changes. You used to be able to work around the bug by setting the AllowUpdateChildControlIndexForTabControls application switch<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fcore%2Fcompatibility%2Fwinforms%23allowupdatechildcontrolindexfortabcontrols-compatibility-switch-not-supported&data=05%7C01%7Cigor.velikorossov%40microsoft.com%7C9fc6ecd076ce47c51ae108da9df9148b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637995990368677763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A54H6pRml1RhoZ%2FqxtsvfrMxwN1vm7a%2BXgrtTnae7Oo%3D&reserved=0> to false, but this switch is no longer supported.

You can fix the bug by changing that line of code to:

owner.Controls.Remove(this[index]);

Steps to reproduce

I don't think this is needed - the bug is obvious from looking at the one line of code.

**Comment by elachlan** [comment]
@albahari are you looking to submit a patch to fix this?

**Comment by albahari** [comment]
Here's the PR: https://github.com/dotnet/winforms/pull/7911
