### ISSUE TITLE
[Api Addition] Implement LinkLabel.Link.Equals

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#784]
Currently doing `new LinkLabel.Link(1, 2).Equals(new LinkLabel.Link(1, 2))` returns `false` which doesn't make sense!

**Comment by zsd4yr** [comment]
So equals is currently checking the references, and since these are two different objects, the result is false? 

What is the desired behavior?

What is the business case? Why would you want to compare these? There is already a private link comparer for the purposes of sorting links. 

Are you proposing that Linklabel.Link's be considered equivalent by satisfying *only* start and length? What about Enabled, Name, Owner, State, Visited, and LinkData?

**Comment by weltkante** [comment]
I agree with @zsd4yr , since LinkLabel.Link carries additional mutable state its best to keep reference equality and use explicit comparer objects when you have a particular requirement for comparison. Otherwise you risk that someone mixes up links in some collection and loses mutable state.

**Comment by dreddy-work** [comment]
Closing this issue as won't fix for above mentioned reasons.
