### ISSUE TITLE
In a special case of winform, the exception prompt cannot be thrown, and the program will automatically exit in about 4 seconds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#7858]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/winform在一个特殊情况下，异常提示无法抛出，并且程序在4秒左右会自动退出/10156622)._

---
\[severity:It’s more difficult to complete my work\]  
[20220924\_201014.mp4](https://aka.ms/dc/file?name=B1b12694a77f84006b1f351665f11271f637996184524298897_20220924_201014.mp4&tid=1b12694a77f84006b1f351665f11271f637996184524298897)

Translated by Bing: 1. Created a WinForm program
2. Create a new user control, add a button to the control (and add it to the main window when WinForm starts)
3. The function of the button is to start a thread
4. The thread method is to actively throw an error

When debugging in visual studio, it is normal for exceptions to be thrown.
But when we run the exe program directly, after about 4 seconds, the program exits directly without any abnormal prompt!

---
#### Feedback Bot on 9/26/2022, 10:39 AM: 

(private comment, text removed)
#### Amy Li [MSFT] on 9/26/2022, 05:42 PM: 

(private comment, text removed)
#### 叶少军 on 9/28/2022, 00:49 PM: 

(private comment, text removed)
#### 叶少军 on 9/28/2022, 01:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Amy-Li03** [comment]
### .NET version
.Net 8.0 SDK build: 8.0.100-alpha.1.22476.24

### Did it work in .NET Framework?
No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?
No, it's not a regression issue

### Steps to reproduce
1. Open attached sample app.
[SampleApp.zip](https://github.com/dotnet/winforms/files/9662439/SampleApp.zip)
2. Run the exe file directly

### Actual behavior
The program exits directly without any abnormal prompt.
![Core](https://user-images.githubusercontent.com/62929087/192713625-82cf083e-4656-4b2a-b184-1f594674e8d6.gif)

### Expected behavior
It is normal for exceptions to be thrown.
![image](https://user-images.githubusercontent.com/62929087/192713527-c96381f5-e2cc-4d7e-ae70-3908605e1280.png)

**Comment by RussKie** [comment]
This is by design. Exceptions thrown on a non-main thread will terminate the app unless marshalled back to the main thread and handled. Please refer to https://learn.microsoft.com/dotnet/api/system.appdomain.unhandledexception for more details.
