### ISSUE TITLE
vs2022 17.3.5  .net 4.8 c# mdi child form cannot show at centerparent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#7909]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/vs2022-1735--net-48-c-mdi-child-for/10158939)._

---
1. vs2022 enterprise 17.3.5  creat c# windowsformsapp（.net framework），use default setup ，framework4.8 

2. add a mdiparent form: MDIParent1 and a  new form :Form1

3. and menu item to call Form1

4. menuitem click code :

Form&nbsp;form1&nbsp;=&nbsp;new&nbsp;Form1();

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;form1.TopLevel&nbsp;=&nbsp;false;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;form1.Parent&nbsp;=&nbsp;this;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;form1.StartPosition=FormStartPosition.CenterScreen;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;form1.Show();

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return;

5. the child form can not be set at the center of the parent screen

---
#### yx Li on 9/28/2022, 09:18 AM: 

(private comment, text removed)
#### Feedback Bot on 9/28/2022, 11:11 AM: 

(private comment, text removed)
#### Merrie McGaw [MSFT] on 10/6/2022, 08:02 AM: 

(private comment, text removed)
#### Feedback Bot on 10/8/2022, 09:46 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Amy-Li03** [comment]
### .NET Core Version:
.NET SDK 8.0.100-alpha.1.22478.5
### Have you experienced this same bug with .NET Framework?:
Yes
### .NET Core Version:
This is not a regression issue, it also repro on .NET Core 3.1 & .NET 5.0, 6.0, 7.0.
## Actual behavior:
Child form cannot be set at the center of the parent screen.
![image](https://user-images.githubusercontent.com/62929087/194742441-3174072d-6457-4d50-8d6e-855b3c6f5313.png)

## Expected behavior:
Child form should be set at the center of the parent screen.

## Minimal repro:
1. Extract and open following test app: 
[TestApp (2).zip](https://github.com/dotnet/winforms/files/9740924/TestApp.2.zip)
2. Build and run this project
3. Click the menuitem of "CallForm1"

**Comment by kirsan31** [comment]
There is an error in repro app:
![image](https://user-images.githubusercontent.com/17767561/194774929-224609d8-a323-4680-80fd-4f89b760003b.png)

And as I understand author noticed it: https://developercommunity.visualstudio.com/t/vs2022-1735--net-48-c-mdi-child-for/10158939#T-N10158957

**Comment by merriemcgaw** [comment]
@Amy-Li03 - does @kirsan31's suggestion solve the problem? If so, let's go ahead and close this issue. Otherwise, it is something that has been around for a while and is not aligned with current priorities.

**Comment by Amy-Li03** [comment]
@merriemcgaw yes, @kirsan31's suggestion can solve this problem, I will close this issue.

**Comment by RussKie** [comment]
Thank you @kirsan31
