### ISSUE TITLE
[Accessibility] ArgumentOutOfRange exception is raised on selecting the last SubItem of ListViewItem in Details view if it has an image.

### ISSUE THREAD

**Issue by NikitaSemenovAkvelon** [dotnet/winforms#8025]
### .NET version

8.0.100-alpha.1.22512.5

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, reproduces only in .NET 8.

### Issue description

If select or just move cursor over the last `SubItem` of `ListViewItem` which has an image in `Details` view an `ArgumentOutOfRange` exception will be raised.
![Screenshot 2022-10-25 160736](https://user-images.githubusercontent.com/109065597/197772637-d8f65ae9-95c6-4e6e-b540-70c1eb26d0d0.png)
It is a regression bug from #7672

### Steps to reproduce

1. Create a new WinForms application.
2. Add ListView.
3. Set View to Details.
4. Add a new item with an image.
5. Select the last SubItem while some accessibility tool (e.g. AI) is working.

**Comment by MandiMan** [comment]
Verified with .NET SDK .NET 8.0.100-alpha.1.22552.10 build from main branch, this issue is fixed that if you select or just move the cursor to the last SubItem of a ListViewItem with an image in the detail view, no ArgumentOutOfRange exception is raised.
![issue8025](https://user-images.githubusercontent.com/108860782/199703882-bb0e7145-e0d0-419f-8f10-4eedda6c7270.png)
