### ISSUE TITLE
winforms databound usercontrol causes rowchanged event

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#8095]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/winforms-databound-usercontrol-causes-ro/10185137)._

---
[severity:It's more difficult to complete my work]
When a win forms usercontrol is data bound to a datatable. It causes the datarow to be modified EVEN when no data has been changed.
This is causing a big performance issue in my application.

I have created a test application which I have attached to demonstrate the problem.
I have tried many things but cannot resolve it. I don't know where the problem is.

Test 1 - Tests data binding with a standard textbox. It is bound to the source table. The DataTable has a RowChanged event handler to display the table change count and display the row versions with data. This does not cause any rowchanges.

Test 2 - Tests data binding with a User Control. Note: This user control is a dummy version used to demonstrate my problem. This si bound to the same data table as etst 1 and the same source column. This test causes each row to be modified, as show by the display of the DataRow values.

In both tests, the results are displayed in a textbox on the form.

Can you help.
How can I stop rows being changed when there is not data modified.

Thankyou in advance.
Glynn.

---
#### Feedback Bot on 10/31/2022, 11:33 AM: 

(private comment, text removed)
#### Melon Wang [MSFT] on 11/1/2022, 03:06 PM: 

(private comment, text removed)
#### glynn.stuber on 11/1/2022, 04:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MelonWang1** [comment]
**.NET Core Version:**
.NET SDK 8.0.100-alpha.1.22531.8

**Have you experienced this same bug with .NET Framework?:**
Yes

**More Info:**
This is not a regression issue, it also repro on .NET Core 3.1 & .NET 5.0, 6.0, 7.0.

**Actual behavior:**
This test causes each row to be modified, as show by the display of the change count values.
<img width="704" alt="Screenshot 2022-10-31 224530" src="https://user-images.githubusercontent.com/94418985/199373949-7dab9a19-2589-4bec-8268-9783ce7069a2.png">

**Expected behavior:**
This test does not cause any rowchanges, the change count should be 0.
<img width="701" alt="Screenshot 2022-10-31 224447" src="https://user-images.githubusercontent.com/94418985/199373962-45ad81d8-9716-4f6e-b64e-19615c4f218d.png">

**Minimal repro:**
1. Extract and open following test app: 
[WinFormsApp35.zip](https://github.com/dotnet/winforms/files/9915105/WinFormsApp35.zip)
2. Build and run this project
3. Click the "TextBox Binding Test" button
4. Observe the "Log Text " textbox
5. Click "User Control Binding Test" button
6. Observe the "Log Text " textbox

**Comment by KlausLoeffelmann** [comment]
Quick question:
Although you stated already, it's not a regression from .NET Framework, I'd rather ask twice than miss it, and make sure: Are you seeing the same behavior in .NET _Framework_ 4.7.2 or 4.8?

**Comment by MelonWang1** [comment]
This issue also reproduces on .NET Framework 4.7.2 and 4.8.
![472](https://user-images.githubusercontent.com/94418985/200458447-132834e2-8300-42bc-911e-1416c723df5f.gif)

**Comment by merriemcgaw** [comment]
Thank you for bringing this up! There may well be a customer that depends on this behavior, and changing it after all these years would be breaking for those customers migrating to .NET Core. At the moment, something this doesn't meet the bar for the team and there is a significant compatibility risk. @MelonWang1, can you close the underlying issue as low-pri.

**Comment by MelonWang1** [comment]
@merriemcgaw ok, thank you, I will close this ticket as low-pri.

**Comment by glynn-stuber** [comment]
This problem causes a severe performance impact on any application using a usercontrol bound to a database table column.

I have found a work-a-round.
The BUG is that dotnet ignores a binding failure and as a result flags each row as being modified - even though no data is actually changed.

The binding class constructor provides a hint. It states:
"When you create a binding to a control's property, the new Binding inspects the events exposed by the bound control and attaches to two particular events:
a) Control.Validating
b) An event named PropertyNameChanged (for example, Control.BackColorChanged)"

A usercontrol inherits a Control.Validating event, but of course does not have any property events unless they are explicitly coded.

**THE SOLUTION:**
Creating an event for the propertyChanged SOLVED the problem. It does even have to do anything, but of cause makes sense for it to be raised whenever the property changes.

**THE BUG:**
Bindings are created even when the property event does not exist. No Warning is given. No information provided. Just the incorrect and undesired effect of flagging every row as changed!.

**Comment by merriemcgaw** [comment]
I'm so happy you found a workaround!
