### ISSUE TITLE
Cannot write or load binary serialized resources to/from satellite assemblies using .NET7

### ISSUE THREAD

**Issue by ericcdub** [dotnet/winforms#8159]
### .NET version

7.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

6.0 and previous

### Issue description

I'm migrating a class library from .NET 6 to 7. The library extracts localisable resources from our customers' .NET assemblies including but not limited to strings, the sizes/positions of forms and controls, and images. The library also writes the localised resources into satellite assemblies. However, after migrating to .NET 7, I am unable to run .NET6 or .NET7  applications with localised satellite assemblies, as the runtime throws an exception stating: "'Cannot read resources that depend on serialization.'"  The types causing this error are the non-primitive UI types in assemblies such as System.Drawing.Size, which we write to satellite assemblies using BinaryFormatter to serialize the instances to byte arrays and passing those to ResourceWriter.AddResourceData.

I'm aware BinaryFormatter is obsolete, and will be removed altogether from .NET9, but I can't find information anywhere on alternative methods to store these resources in satellite assemblies. I've read some people using NewtonSoft.JSON or similar to serialize instances in non-localization contexts, but this doesn't work in ours because any localised app will need to be modified to also deserialize using JSON.

### Steps to reproduce

Create a sample .NET 7 WinForms project "A" with a form and a button and/or textbox on it.
Set the culture and UI of of the app's main thread to "de" in Main() in Program.cs:

`CultureInfo ci = new CultureInfo("de");
Thread.CurrentThread.CurrentCulture = ci;
Thread.CurrentThread.CurrentUICulture = ci;`

Set the form's localisable property to true, and compile the project.

Create another NET 7 project "B", and in it write code to use ResourceReader to enumerate the resources in the assembly you just compiled from project "A", and using ResourceWriter, write those resources out to a single .resources file. We don't need to actually translate the resources to create the assemblies, and the code above will  cause  project "A" to use search for German satellite assemblies at runtime, we just need to create assemblies that adhere to the satellite assembly naming and location conventions.

As project "A" just contains a form with child UI controls, we will write out a single .resources file for that form to a subfolder of the output folder where "A"'s compiled assembly was written. That subfolder should be named after a language such as "de" and the .resources file should have a name similar to "A.Form1.de.resources"

Use al.exe to build a satellite assembly DLL from the .resources file you've created:

al.exe /nologo /t:lib /embed:"outputfolder\de\A.Form1.de.resources" /culture:de /out:"outputfolder\de\A.resources.dll" /comp:"A" /title:"A" /fileversion:"1.0.0.0" /prod:"A" /productv:"1.0.0" /v:"1.0.0.0"

Finally, run "A"'s executable - It will throw an exception while trying to load the localised resources

**Comment by RussKie** [comment]
Please provide a complete sample, thank you.
________________________________
From: Eric Chubb ***@***.***>
Sent: Friday, 11 November 2022 1:54 AM
To: dotnet/winforms ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/winforms] Cannot load binary serialized resources written using .NET7 (Issue #8159)


.NET version

7.0

Did it work in .NET Framework?

Yes

Did it work in any of the earlier releases of .NET Core or .NET 5+?

6.0 and previous

Issue description

I'm migrating a class library from .NET 6 to 7. The library extracts localisable resources from our customers' .NET assemblies including but not limited to strings, the sizes/positions of forms and controls, and images. The library also writes the localised resources into satellite assemblies. However, after migrating to .NET 7, I am unable to run .NET6 or .NET7 applications with localised satellite assemblies, as the runtime throws an exception stating: "'Cannot read resources that depend on serialization.'" The types causing this error are the non-primitive UI types in assemblies such as System.Drawing.Size, which we write to satellite assemblies using BinaryFormatter to serialize the instances to byte arrays and passing those to ResourceWriter.AddResourceData.

I'm aware BinaryFormatter is obsolete, and will be removed altogether from .NET9, but I can't find information anywhere on alternative methods to store these resources in satellite assemblies. I've read some people using NewtonSoft.JSON or similar to serialize instances in non-localization contexts, but this doesn't work in ours because any localised app will need to be modified to also deserialize using JSON.

Steps to reproduce

Create a sample .NET 7 WinForms project A with a form and a button and/or textbox on it.
Set the culture and UI of of the app's main thread to "de":

CultureInfo ci = new CultureInfo("de"); Thread.CurrentThread.CurrentCulture = ci; Thread.CurrentThread.CurrentUICulture = ci;

Set the form's localisable property to true, and compile the project.

Create another NET 7 project B, using ResourceReader to enumerate the resources in the assembly you just compiled, and using ResourceWriter, write those resources out to a satellite assembly. We don't need to actually translate the resources to reproduce this issue. Because we force the culture of project A to German, the runtime will look for a german satellite assembly regardless of the actual content of those assemblies.

As project A just contains a form with child UI controls, we will write out a .resources file to a subfolder of the output folder where A's compiled assembly was written. That subfolder should be named after a language such as "de" and the .resources file should have a name similar to "A.Form1.de.resources"

Use al.exe to build a satellite assembly DLL from the .resources file you've created:

al.exe /nologo /t:lib /embed:"\de\WinFormsApp1.Form1.de.resources" /culture:de /out:"\de\A.resources.dll" /comp:"A" /title:"A" /fileversion:"1.0.0.0" /prod:"A" /productv:"1.0.0" /v:"1.0.0.0"

Finally, run A's executable - It will throw an exception while trying to load the localised resources

**Comment by ericcdub** [comment]
> Please provide a complete sample, thank you.

Sure. 

Unzip SerializationRepro and WinFormsApp1. Compile both.

Usage: SerializationRepro.exe <full path to assembly> <language code>
Example: SerializationRepro.exe C:\WinFormsApp1\bin\Debug\net7.0-windows\WinFormsApp1.dll de

[SerializationRepro.zip](https://github.com/dotnet/winforms/files/9989786/SerializationRepro.zip)
[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/9989787/WinFormsApp1.zip)
