### ISSUE TITLE
[Multi-Monitor][PerMonitorV2] Font Dialog control is not scaled well on secondary screen

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#8265]
### .NET version

8.0.100-alpha.1.22567.28

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it also repro on .NET 6.0 & 7.0.

### Issue description

Font dialog control is not scaled well in secondary screen under PermonitorV2 mode.

### Steps to reproduce

1. Launch VS instance on 300% primary monitor.
2. Create a winforms .net core project.
3. Drag and drop a button, Font Dialog control.
4. Double click button control and add below code:
	fontDialog1.ShowDialog();
5. Build and run, click button control.
6. Move to 100% secondary monitor.

Or:
1. Extract and open [fontdialog.zip](https://github.com/dotnet/winforms/files/10073219/fontdialog.zip) on 300% primary screen.
2. Build and run it, click button control.
3. Move to 100% secondary monitor.

**Actual result:**
FontDialog control is not scaled well.
Move form 300 primary screen to 100 secondary screen:
![100ci](https://user-images.githubusercontent.com/94418985/203485374-ddb29298-9831-49d4-9601-47ca1c7f7fdf.png)
Move form 100 primary screen to 300 secondary screen:
![font-300ci](https://user-images.githubusercontent.com/94418985/203485393-de0ad6b6-1e69-4270-8fdb-24d3719c3767.png)
**Expected result:**
FontDialog control should scaled well.
Move form 300 primary screen to 100 secondary screen:
![100ci-fontdialog-normal](https://user-images.githubusercontent.com/94418985/203485424-b29fa687-6b9a-47b1-b80a-c9bd8c379f79.png)
Move form 100 primary screen to 300 secondary screen:
![300ci-fontdialog-normal](https://user-images.githubusercontent.com/94418985/203485445-fc408bba-a0db-487e-bc23-9bdf162ffa34.png)

**More Info:**
1. This issue also repro on moved VS from 100% primary to 300% secondary.
2. This issue also repro on .NET7.0, .NET6.0. 
3. This issue not repro on framework project.
4. This issue doesn't repro on SystemAware and DpiUnware mode.

**Comment by dreddy-work** [comment]
FontDialog derived from CommonDialog derived from Component. Component does not have infrastructure to support PermonV2 mode. Looking if we could refresh in some way so that native windows handle this. We could make common dialog and their inherited components to always Open in SystemAware when application is running in PermonV2 mode if we can't get it working.

**Comment by dreddy-work** [comment]
This is an issue with Native Common dialog.  A bug is raised against Windows to track the fix. Meanwhile, We could make this dialog creation as SystemAware, just like classic Notepad does.

https://microsoft.visualstudio.com/OS/_workitems/edit/42835582

**Comment by MandiMan** [comment]
Verified with .NET SDK 8.0.100-alpha.1.23061.8 build from main branch, this issue is fixed that Font dialog control is scaled well in secondary screen under PermonitorV2 mode.
Move form 300 primary screen to 100 secondary screen:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/108860782/212004142-a88ab4c2-21c6-4e91-9cc3-f401fb85723e.png)
Move form 100 primary screen to 300 secondary screen:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/108860782/212004391-67db6f7d-5004-4e98-86c5-b518c69289c2.png)
