### ISSUE TITLE
Remove dead Remoting and AppDomain goo

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/winforms#839]
.NET Core does not support Remoting, nor does it support secondary AppDomains. Therefore we should remove all code related to those things.

**Comment by weltkante** [comment]
Related to ComponentManager issue #247 which was (wrongly) closed and moved to corefx.

You probably cannot remove the ComponentManager completely since Office relies on it to communicate modal forms. Refactoring it is also dangerous without having proper tests in place. Therefore I'd suggest to reopen that issue and ideally bring in someone from the Office team to confirm it either can be removed or create proper tests.

Just mentioning this here again so it doesn't get broken, coreclr now can host COM objects and thus allows programming of Office Addins. Showing WinForms UI should continue to interop with Office.
