### ISSUE TITLE
ReportViewer component for Windows Forms in .net core

### ISSUE THREAD

**Issue by mserioli** [dotnet/winforms#8407]
### Is your feature request related to a problem? Please describe

Migrate Windows Forms applications that use SSRS ReportViewer from .net framework.

You are releasing SSRS 2022 (16.x) while .net core is not at pace, not including support for it anymore. Is there still any other valid alternative to preview/export reports? 

### Describe the solution you'd like and alternatives you've considered

Add ReportViewer component for Windows Forms (WPF, etc)

### Will this feature affect UI controls?

Integration with Visual studio Designer greatly appreciated

**Comment by elachlan** [comment]
I'd say this would make sense as a nuget package provided by microsoft, probably by the same team that does the designer.

There looks to be one already written by a third party: https://github.com/lkosson/reportviewercore

I have not verified the package on its functionality or security.

**Comment by mserioli** [comment]
The package you reported works great.

A better thing anyway would be having one supported by Microsoft

**Comment by merriemcgaw** [comment]
Thank you for reporting this issue. We are looking into working with our partner teams, like SSRS to help them migrate their components to .NET, but it is honestly slow going with many teams having priorities other than WinForms 🤷🏻‍♀️. We'll continue to forward these requests to our partners so that they know how many people are interested in .NET versions of their components.

Since you've found a workaround, and this issue isn't really something that would reside in this WinForms repo, I'm going to close this issue. But I do want to assure you that we are working with internal partners to try to bring some of these tools into the modern era.

**Comment by mserioli** [comment]
Is there any way I can track/get feedback from the ssrs team support on
this?

Thanks and regards
