### ISSUE TITLE
JAWS for Windows reports each item of the horizontal menu bar as having a submenu

### ISSUE THREAD

**Issue by v-elnovikova** [dotnet/winforms#8433]
### .NET version

.NET 7.0.1

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

Related to #7770.

When navigating through MenuStrip top level items, JAWS announces each as "<item name>, sub menu".

![JAWS](https://user-images.githubusercontent.com/113603457/209844932-dcd2e5c5-ff15-437a-ae25-455e69b4bc40.png)

> Menu bar
> File sub menu
> To navigate press Left or Right Arrow.
> f
> Edit sub menu
> e
> Tools sub menu
> t
> menu
> Customize
> To move through items press up or down arrow.
> c
> Options sub menu
> o
> Settings...

### Steps to reproduce

Sample app: [WinFormsApp1.zip](https://github.com/dotnet/winforms/files/10315328/WinFormsApp1.zip)

Build and run the above WinFormsApp1 application.
Run JAWS.
Press Alt key to focus on the first menu item.
Press right key several times to observe other items.
JAWS announces each as "<item name>, sub menu".

**Comment by Ashley-Li** [comment]
Verified with .NET SDK 8.0.100-alpha.1.23061.8 build from main branch, this issue is fixed. When browsing MenuStrip top-level items, JAWS announces each items as the desired outcome, please watch the video and listen to its results.

https://user-images.githubusercontent.com/56664234/212021245-6ca89304-2ac0-4563-aa79-e4c1e58f1e47.mp4
