### ISSUE TITLE
Automation case about ErrorProvider failed with "Cannot access a disposed object"

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#8513]
### .NET version

8.0.100-alpha.1.23068.16

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro in previous versions

### Issue description

![image](https://user-images.githubusercontent.com/26474449/213655624-c6592448-98f2-413e-8f63-c82f811b9c79.png), related causing PR: https://github.com/dotnet/winforms/pull/8486
_System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed object.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.Icon.get_Handle()
   at System.Drawing.Icon.get_Size()
   at System.Windows.Forms.ErrorProvider.IconRegion.get_Size()
   at System.Windows.Forms.ErrorProvider.ErrorWindow.Update(Boolean timerCaused)
   at System.Windows.Forms.ErrorProvider.ErrorWindow.Add(ControlItem item)
   at System.Windows.Forms.ErrorProvider.ControlItem.AddToWindow()
   at System.Windows.Forms.ErrorProvider.ControlItem.set_Error(String value)
   at System.Windows.Forms.ErrorProvider.SetError(Control control, String value)
   at XErrorProvider.set_RightToLeft(TParams p, Boolean rtl) in C:\Users\xxx\Desktop\XErrorProvider_P1\XErrorProvider_P1\XErrorProvider.cs:line 455
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)_

### Steps to reproduce

It reproduces steadily in our automation case about errorProvider, but we cannot repro manually in TextBox and ErrorProvider, then errorProvider.setError

**Comment by elachlan** [comment]
@Olina-Zhang How recent did the test failures start?

I think it might be caused by #8486, could your team A/B test that change and see if it caused the failure?

**Comment by dreddy-work** [comment]
> I think it might be caused by #8486,

Possible. @Olina-Zhang ping me once you confirm and i will look into it for Preview 1.

**Comment by elachlan** [comment]
It's confirmed in issue description. I'm looking into it now.

**Comment by elachlan** [comment]
The exception is caused because the size of an icon relies on there being a handle. But for whatever reason, the icon doesn't have a handle.

https://github.com/dotnet/runtime/blob/3d616586d7aa9b49226e28f353a9b20ce0b6e6b8/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.cs#L219

Handle is initialized via the method `Initialize`.
https://github.com/dotnet/runtime/blob/3d616586d7aa9b49226e28f353a9b20ce0b6e6b8/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.cs#L458

I can't see why this is happening.

The only strange this I see is that the icon gets created twice.
```CSharp
// Error provider uses small Icon.
int width = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CXSMICON);
int height = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CYSMICON);
using var defaultIcon = new Icon(typeof(ErrorProvider), "Error");

t_defaultIcon = new Icon(defaultIcon, width, height);
```

Could it not be this?
```csharp
int width = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CXSMICON);
int height = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CYSMICON);
t_defaultIcon = new Icon(typeof(ErrorProvider).Module.Assembly.GetManifestResourceStream(typeof(ErrorProvider), "Error")!, width, height);
```

Otherwise we can ask runtime to add a constructor overload to specify that the icon is a small icon.

**Comment by dreddy-work** [comment]
they both should have been same but dispose is destroying handle. Will have to adjust code in a way we do not leak memory while creating this resized Icons.

**Comment by elachlan** [comment]
@ericstj runtime has you as the code owner of `System.Drawing`. Could you please have a look at our usage of the `Icon` ctor here?

We create an icon like this because we want the size to be `SM_CXSMICON` (small icon) and not the default size `SM_CXICON`.

```csharp
// Error provider uses small Icon.
int width = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CXSMICON);
int height = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CYSMICON);
using var defaultIcon = new Icon(typeof(ErrorProvider), "Error");

t_defaultIcon = new Icon(defaultIcon, width, height);
```

Would this call for a new overload constructor to `Icon` with the following signature? `public Icon(Type type, string resource, Size size)` or would it be better to have an enum specifying the sizes of default and small?

**Comment by elachlan** [comment]
Possibly related: https://github.com/dotnet/runtime/issues/80261

**Comment by merriemcgaw** [comment]
@Olina-Zhang are you running at 100% on the test case?

**Comment by elachlan** [comment]
@merriemcgaw this issue is more about how the icon constructor operates when passed an existing icon. It uses the icons handle, our code basically creates an icon, passes it to a new icon (reusing the handle), then disposes the old icon causing the handle to be disposed.

At least that is my understanding. I think the best solution is an API change to the icon constructors to allow specifying either standard or small icon size. Probably via an enum.

Can the Winforms team help me with that API change on runtime?

**Comment by dreddy-work** [comment]
@elachlan, thanks for conducting the initial investigation. I'm currently exploring options to resolve the issue for Preview 1 without changes to Icon object, due to the regression that's present. Changes to the Icon (System.Drawing) object, whether it be an API change or any functional changes, would require collaboration with other teams and may take some time. Let's track that as a separate item and aim to address it in Preview 2 or 3.

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang are you running at 100% on the test case?

Yes, it still reproduces.

**Comment by elachlan** [comment]
> ```cs
> int width = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CXSMICON);
> int height = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CYSMICON);
> t_defaultIcon = new Icon(typeof(ErrorProvider).Module.Assembly.GetManifestResourceStream(typeof(ErrorProvider), "Error")!, width, height);
> ```

In that case I suggest the following, maybe adjusted to check for null on the stream, but up to you.
```csharp
int width = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CXSMICON);
int height = PInvoke.GetSystemMetrics(SYSTEM_METRICS_INDEX.SM_CYSMICON);
t_defaultIcon = new Icon(typeof(ErrorProvider).Module.Assembly.GetManifestResourceStream(typeof(ErrorProvider), "Error")!, width, height);
```

**Comment by dreddy-work** [comment]
@Olina-Zhang , can you share the repro project to me and steps to build it locally? I wanted to test the changes locally.

**Comment by Olina-Zhang** [comment]
Put that case in https://microsoft-my.sharepoint.com/personal/v-olzhan_microsoft_com/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fv%2Dolzhan%5Fmicrosoft%5Fcom%2FDocuments%2FCase&view=0

**Comment by dreddy-work** [comment]
Hello @Olina-Zhang - I tried to repro with sample you share but i do not see issue repro with latest WinForms binaries from main branch. Did you repro it with latest? @elachlan did you try repro this locally?

**Comment by elachlan** [comment]
I did try. But didn't get an error. I thought it was possibly a bit rarer.

**Comment by dreddy-work** [comment]
> I did try. But didn't get an error. I thought it was possibly a bit rarer.

Oh okay. Let's see if we get a consistent repro here before pushing fix.

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang - I tried to repro with sample you share but i do not see issue repro with latest WinForms binaries from main branch. Did you repro it with latest?

I still repro it using the latest binaries built from Winforms main branch.
![image](https://user-images.githubusercontent.com/26474449/217404264-7bede28d-bcff-4de2-9c98-7e774fc505cf.png)

**Comment by dreddy-work** [comment]
I see app was statically referencing winforms binaries. I uploaded same but referencing .NET 8.0 SDK. Did you try my solution from above share?

**Comment by dreddy-work** [comment]
@Olina-Zhang , if you are able to repro with the app I uploaded above, can you share DPI info on the machine you are running?

**Comment by Olina-Zhang** [comment]
I tried to use your uploaded, also repro. My VM is set 100%DPI by default.

**Comment by dreddy-work** [comment]
> I tried to use your uploaded, also repro. My VM is set 100%DPI by default.

strange. I will try on 100% machine.

**Comment by dreddy-work** [comment]
@merriemcgaw, this is a specific case of resetting the error icon after it has been set to a custom icon. Preview 1 is complete and secured. I am confident in leaving it to Preview 2 and directing customers to this solution in the event they encounter this problem. Please let me know if you feel otherwise.

**Comment by MandiMan** [comment]
Verified on latest .NET 8.0.100-preview.2.23116.17 build, issue is fixed. Automation case about ErrorProvider can be run successfully.
Screenshot as below:
![image](https://user-images.githubusercontent.com/108860782/219532847-4e02fd98-e171-49f1-a4bc-c756c4b1c389.png)

**Comment by MelonWang1** [comment]
Verified this on .NET 8.0 Preview 2.0 TP build: 8.0.100-preview.2.23151.8, issue was fixed. Automation case about ErrorProvider can be run successfully.
