### ISSUE TITLE
Cannot resize controls in runtime and has an exception when moving controls

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#8515]
### .NET version

8.0.100-alpha.1.23068.16

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

work in .Net 6.0, and reproduced from .Net 7.0

### Issue description

In Winforms repo, there has a [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app, cannot resize controls in .Net 7.0 & 8.0 and has an exception when moving controls in .Net 8.0.
![8 0Issue](https://user-images.githubusercontent.com/26474449/213832129-deedfb87-c995-49a4-8ae3-a9c281581b56.gif)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
![image](https://user-images.githubusercontent.com/2433737/214164790-c9e42355-a002-41f5-b43d-87a5a8c36386.png)
@merriemcgaw this exception is probably caused by the arraylist replacements. #8357

**Comment by dreddy-work** [comment]
@elachlan , are you looking into this?

**Comment by elachlan** [comment]
I hadn't been because a lack of a stack trace and because I believe it's a designer issue.

**Comment by MandiMan** [comment]
Verified with .NET 8.0.100-preview.2.23101.9 build from main branch, this issue is fixed. In Winforms repo, the [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app could resize controls and without exception when moving controls in .Net 8.0. Gif as below:
![issue8515](https://user-images.githubusercontent.com/108860782/216250167-59a5eb5c-1e0c-487c-8234-4c5d20e004e7.gif)

**Comment by John-Qiao** [comment]
Verified with .NET 8 Preview 1 TP build: .NET 8.0.100-preview.1.23108.10, issue was fixed in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) project. The result as same as above.
