### ISSUE TITLE
Visual Studio 17.5 and 17.5.1 issues with 3rd party Controls

### ISSUE THREAD

**Issue by MLyons10** [dotnet/winforms#8780]
### Environment

17.5 and 17.5.1

### .NET version

All

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes.  17.4.5 and previous (going back to Visual Studio 2010 or earlier) all worked without issue.

### Issue description

This is also submitted under Feedback here: https://developercommunity.visualstudio.com/t/Adding-control-libraries-is-not-working/10294562?port=1025&fsid=aba7d08f-0769-43a2-befb-fd6cf5e7cffb&ref=native&refTime=1678485051219&refUserId=842923cd-f358-4b57-af26-82dbd0a8431d&viewtype=all

But does not seem to be going anywhere.  There are significant resources attached however, including a demo project, control dlls, and video showing the issue.

Effectively, this worked without any issue in prior versions of Visual Studio.

Visual Studio 17.5 seemingly introduced a change in how references were handled, where it automatically attempts to add a reference when a control is dragged onto a form.  If the reference is already added however, the control cannot be added and generates an error that the reference is already added to the project.  This then makes the software unuseable as you must delete the reference between each and every new control that you add to the form and the form designer then cannot display the form if the reference is removed...

Can this please be corrected?  It is a serious issue.

### Steps to reproduce

Open a form in the designer.

Drag a 3rd party control to the form. This then adds a reference to the dll to the project.

Try to add another control from the same 3rd party control library to the form.  This now generates an error that the control library was already added as a reference and refuses to allow you to add the control to the form.

Delete the reference to the control library.

Drag a 3rd party control to the form.  This works and again adds a reference to the dll to the project.

Try to add another control from the same 3rd party control library to the form.  This now again generates an error that the control library was already added as a reference and refuses again to allow you to add the control to the form.

### Diagnostics

```text
I believe this is caused by a change in the way Visual Studio 17.5 and 17.5.1 attempt to add references automatically when you add a control to a form / project.  If the reference is already added, Visual Studio should not then attempt to add it again and should not generate an error or refuse to allow you to add the control.
```

**Comment by elachlan** [comment]
@Olina-Zhang I imagine your team will need to test this?

@merriemcgaw does the issue have enough information? I imagine a designer issue will need to be created.

**Comment by merriemcgaw** [comment]
Thanks @elachlan - it looks like we've been working with the customer since the ticket was filed and are having trouble with the licensing of the component to get it installed to debug the issue.

@MLyons10 - I have a couple of questions:

1. Does this occur with other control vendor's controls? (I will be testing that but wondered if you had already)
2. Is this a .NET project or a .NET Framework project? What version are you targeting?
3. If this is Framework
4 Is this a classic .NET Framework vbproj/csproj or the newer SDK Style projects? That would help me to route the issue.
5. Did you notice it happen in any of the 17.5 Preview releases? Does it still occur in a 17.6 Preview?

I am not aware of the WinForms designers (either .NET Framework or .NET) making changes in how we do the references in a recent release. I'll dig around and see what we can find. I'm also going to keep an eye on that internal ticket and keep it moving. Thank you for all the attachments and suggestions. I wondered when you told @Cassie-Li01 to "proceed through without the serial number for a trial edition" whether you intended her to add username and company and leave serial number blank? I see her attempt to proceed through the setup wizard without any content and it won't move forward.

A couple of things I will do: I'll have @Cassie-Li01 or myself test out other control vendors trial products to see if this is individual control provider or everyone. I'll dig around through our recent fixes in the system and see if anything could have caused the problems you describe, and if something changed around us in VS (say the ToolBox service) I will do my best to route the issue to the appropriate team.

**Comment by merriemcgaw** [comment]
@MLyons10 I was able to find the software vendor's website where there is a separate installer for the trial version. I installed it and tried on the latest 17.5.1 and was able to use as many controls on the form (.NET Framework) as I wanted with no trouble at all. This appears to be an issue specific to your machine, though I know it's totally frustrating nonetheless. Have you tried resetting the ToolBox? Repairing the install of both Visual Studio and the Control suite? Perhaps uninstalling the control suite and reinstalling it? 

Unfortunately since I'm unable to reproduce the error you're experiencing it does make it more difficult to troubleshoot for you. Try my suggestions above and we'll look through the diagnostic data in VS to see if we can find the root cause of the problem.

**Comment by Tanya-Solyanik** [comment]
@MLyons10  - I have the VS 17.6 preview3 and I could not repro this bug on your project or on another external reference dll.
1. I downloaded your repro application
2. Added the DevComponents.DotNetBar2 binary to the toolbox - Alt+T ;X to open "Choose toolbox items" dialog; ensure the .NET Components tab is active; "Browse" to "bin\debug\" folder under your application folder, and clicked OK, that added your dll to the toolbox
3. Drag controls from the toolbox onto the form
4. works as expected

@Cassie-Li01 - could you try too? I used a VM.

**Comment by Cassie-Li01** [comment]
Hi @Tanya-Solyanik 
I have tried in 17.5.1 follow your steps. no error show after dragging controls to Form, please check gif is as below:
 
![no error](https://user-images.githubusercontent.com/96758262/224637841-1d9dedc5-c323-41d9-b1c7-4eeb59d2d402.gif)

**Comment by Shyam-Gupta** [comment]
I couldn't repro the issue either.

**Comment by MLyons10** [comment]
Thank you everyone for your comments.  I have previously cleared my toolbox, uninstalled custom controls, reinstalled custom controls, created new projects, tried working on existing projects, cleaning solutions, etc.

I am completely uninstalling and reinstalling Visual Studio now and will post back tomorrow with an update on whether that resolved the issue.

I was not using preview builds, so I'm not sure if the issue existed in preview builds.  I simply updated from 17.4.5 to 17.5 and then to 17.5.1 just as I've updated from every previous version.  I did also test this with other 3rd party control libraries and I am getting the error while using others as well, including a custom control library I've made myself.

The Visual Studio install process takes a while, so once I have everything reinstalled I will post back with an update tomorrow.  Thank you all for your help thus far.

**Comment by MLyons10** [comment]
I apologize for the delay in getting back with an update on this.

I uninstalled everything (Visual Studio, all of my addons, etc.) and then reinstalled everything.  This worked, and I was able to use Visual Studio again.

Then, 17.5.2 came out today, so I wanted to install that update first and test again.  This delayed my response as I basically was installing Visual Studio for a second time today...

I'm happy to report though that after the update to 17.5.2, everything still worked, so it looks like there was something maybe that went wrong during the update to 17.5?  But regardless, I'm happy to be able to use Visual Studio again.

I wanted to thank everyone for all of your help with this and for taking the time to look into this.

And I would like to thank @Cassie-Li01  personally for spending so much time on this with me as well.

Thanks again everyone and I hope everyone has a nice rest of their day.  I guess this can be closed.
