### ISSUE TITLE
System.Windows.Forms should reduce the number of types that use SerializableAttribute

### ISSUE THREAD

**Issue by ericstj** [dotnet/winforms#889]
Not all types that were Serializable in desktop need to be serializable in .NETCore.  Maintaining SerializableAttribute on types means those types need to be tested for Version to Version serialization and potentially framework-to-framework serialization.  This makes it harder to evolve those types and can be costly to maintain.

We've started looking at types that require Serializable for resource scenarios.  Those must be in.

There are likley some types that the designer needs to be serializable, but those may or may not require binary serialization.  As much as you can you should try to avoid depending on binary serialization for internal only scenarios since it increases the maintainence cost of the public types.

Of the remaining types you need to audit their serialization scenarios and look at usage data.  Previously @ViktorHofer worked on this.  I believe they got some help from @marklio to analyze usage by looking at types marked as serializable and the sorts of fields they might contain.  You might be able to convince them to rerun this analysis and include WinForms assemblies.

Once you decide which ones to remove you can just remove the attribute and test.

**Comment by weltkante** [comment]
Another use case to keep in mind besides designer resources is DataObject (e.g. via clipboard or drag'n'drop). Binary serialization is used here to serialize types which don't have fixed semantic, making types not serializable means this will break clipboard/drag'n'drop between .NET Core and Desktop Framework.

**Comment by danmosemsft** [comment]
You'll want to do this before shipping 3.0, to minimize the amount of new code written that expects the types to be serializable.

**Comment by merriemcgaw** [comment]
@dreddy-work can you take a look at this?

**Comment by dreddy-work** [comment]
Changes regarding this are ready for validation. @zsd4yr , please update this when you get chance to share privates for testing.

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik can you take a look at the remaining to-dos so we can document the remaining serializable types?

**Comment by Tanya-Solyanik** [comment]
If serializableattribute decorates an enum or struct, remove it.
If serializableattribute decorate a class, seeif it participates in any of known serialization scenarios:
1. Exceptions are serializable because they are exchanged between frameworks(https://github.com/dotnet/corefx/issues/23520)
2. ToolboxItems are serialized to files and clipboard
3. binary serialization is used in resx serialization
4. Clipboard in the Classic Framework accepts any formats, however in Core it works only with known well defined formats to mitigate security risk

List of known types that are used in resources (resx) serialization:

|     type name                            |                                                      |
| ---------------------------------------- | ---------------------------------------------------- |
|System.Windows.Forms.TableLayoutSettings  |  __class__                                           | 
|System.Windows.Forms.ImageListStreamer    |               "                                      | 
|System.Windows.Forms.TreeNode             |               "                                      | 
|System.Windows.Forms.AnchorStyles         | *enum*, is serializable with no additional attributes|
|System.Windows.Forms.ImeMode              |               "                                      |
|System.Windows.Forms.DockStyle            |               "                                      |  
|System.Windows.Forms.AutoSizeMode         |               "                                      | 
|System.Windows.Forms.FormStartPosition    |               "                                      | 
|System.Windows.Forms.RightToLeft          |               "                                      | 
|System.Windows.Forms.FlatStyle            |               "                                      |
|System.Windows.Forms.ScrollBars           |               "                                      | 
|System.Windows.Forms.Shortcut             |               "                                      | 
|System.Windows.Forms.PictureBoxSizeMode   |               "                                      | 
|System.Windows.Forms.HorizontalAlignment  |               "                                      | 
|System.Windows.Forms.FlowDirection        |               "                                      | 
|System.Windows.Forms.Appearance           |               "                                      | 
|System.Windows.Forms.ImageLayout          |               "                                      | 
|System.Windows.Forms.Orientation          |               "                                      | 
|System.Windows.Forms.ErrorIconAlignment   |               "                                      |
|System.Windows.Forms.HelpNavigator        |               "                                      | 
|System.Windows.Forms.TabAppearance        |               "                                      | 
|System.Windows.Forms.Keys                 |               "                                      |  
|System.Windows.Forms.ToolStripItemImageScaling|           "                                      | 
|System.Windows.Forms.TextImageRelation    |               "                                      | 
|System.Windows.Forms.TabAlignment         |               "                                      | 
|System.Windows.Forms.Padding              | *struct*                                             |
|System.Windows.Forms.LinkArea             |               "                                      |

**Comment by RussKie** [comment]
docs - https://github.com/dotnet/docs/issues/14175
