### ISSUE TITLE
A drag image remnant remains when dragging between different application instances

### ISSUE THREAD

**Issue by willibrandon** [dotnet/winforms#8903]
### .NET version

.NET 7

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

This feature is new as of .NET 7.

### Issue description

When dragging between different application instances, and when a drag image is specified, a remnant of the drag image is incorrectly left displayed due to what I believe is a possible oversight in the DropSource implementation. Note that this issue does not occur when dragging within the same application instance.

A video demonstrating the drag image remnant when dragging between different application instances.

https://user-images.githubusercontent.com/5017479/227811248-964e91b9-bff8-491d-a045-1b0940a2e35e.mp4

A video demonstrating the drag image behavior when dragging within the same application instance.

https://user-images.githubusercontent.com/5017479/227811261-fdb8457b-64a2-4e6d-8ad8-eb9acfa275c9.mp4

### Steps to reproduce

WinformsControlTest project -> DragDrop

See the video demonstrating the issue when dragging between different application instances.

**Comment by willibrandon** [comment]
I have a fix!

**Comment by willibrandon** [comment]
Great. I’m afk right now but I’ll be back on Monday and will make it a priority.

**Comment by elachlan** [comment]
@willibrandon did your fix work and is it possible to submit a PR?

**Comment by willibrandon** [comment]
@elachlan  - I had to take a break from this issue, but will take another look at it now.

**Comment by willibrandon** [comment]
@weltkante - Sorry to bother you, but I'm curious if you have any thoughts on this one, or any ideas on how I could've messed up the implementation? Things go wrong when dragging between different applications, and a drag image remnant remains.

**Comment by willibrandon** [comment]
@elachlan - I'll see if I can first reproduce the issue in a test, and if so, I'll open a draft PR to better facilitate this discussion.

**Comment by weltkante** [comment]
There are various things that look wrong
- contrary to what the [docs](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-idroptargethelper) require, the WinForms IDataObject doesn't support arbitrary private data formats and I see `NotImplementedExceptions` being thrown because things are failing to be stored. They don't seem to be related to the displayed artefact but its still worrying that the required contract is not correctly implemented and may lead to other failure cases.
> Note   The drag-and-drop helper object calls [IDataObject::SetData](https://learn.microsoft.com/en-us/windows/desktop/api/objidl/nf-objidl-idataobject-setdata) to load private formats—used for cross-process support—into the data object. It later retrieves these formats by calling [IDataObject::GetData](https://learn.microsoft.com/en-us/windows/desktop/api/objidl/nf-objidl-idataobject-getdata). To support the drag-and-drop helper object, the data object's SetData and GetData implementations must be able to accept and return arbitrary private formats.
- the DropSource in GiveFeedback calls a DropTarget API on the "last seen HWND" (which ultimately is causing the artifact, it dissapears when you comment it out). Calling a DropTarget API from the DropSource seems suspicious to me and it might not be a supported scenario (but I didn't study the docs about this one so it _might_ be ok). If its not a supported scenario you may be able to get it working by applying more tricks but it may break again in other edge cases.
- the HWND used by GiveFeedback to call DropTarget methods is only updated in DragEnterTarget but not in DragLeaveTarget, but fixing this doesn't fix the artefact because when you don't have a DropTarget you can't call the DropTarget-API

So in summary, you are probably misusing the DragDropHelper API and while doing so, incorrectly tracking the DropTarget.

I don't know why it works better in-process but my guess is that in the cross-process scenario you have two DragDropHelper instances (one in each process) while in-process you just have one shared by everyone, so that might mitigate the incorrect tracking of the DropTarget

I don't really have a good suggestion how to fix the problem, since its not part of the API design, when you move off a DropTarget you may actually not immediately move into a new DropTarget (and in fact you don't when you do the final Drop). After fixing the tracking you might want to do one final call against the old DropTarget inside DragLeaveTarget. This might cause flicker when immediately moving inside a new target which you could mitigate by a delayed call only done when DragLeaveTarget was not followed by a DragEnterTarget.

**Comment by willibrandon** [comment]
You are the man! I can't say that I have all of the issues you've identified here fixed yet, but I am close.

Please bear with me as I try to communicate this as precisely as I can, which is a big struggle for me.

It seems that in the cross-process scenario I'm not properly detecting that we're in a drag loop and because of that, I fail to set one of the arbitrary private drag and drop data formats, such as IsShowingLayer or IsShowingText, into the data object, thus resulting in the `NotImplementedException`. This issue, I believe, is straight-forward to fix. However, as you've also identified, this issue doesn't appear to be related to the issue with the displayed artefact in the cross-process scenario.

For the issue with the displayed artefact in the cross-process scenario, the only other thing I have to add to your observation is that I see a possible issue with the `GiveFeedbackEventArgs` equality implementation in that I'm not sure if the `Effect` property should also be included in the comparison.

**Comment by willibrandon** [comment]
I agree, that looks like a problem to me. Taking a look now.

**Comment by willibrandon** [comment]
@Nora-Zhou01 - Interesting! I haven't seen this behavior before. There is something different about the `RichtTextBox` in the cross-process scenario. Please give me a little bit to take a closer look and experiment.

**Comment by willibrandon** [comment]
Note how the `TextBox` doesn't have this issue in the cross-process scenario, but the `RichTextBox` does.

https://github.com/dotnet/winforms/assets/5017479/1ab3de9b-44f1-48bd-9dcd-381d96667887

I'm looking at `RichTextBox.OleCallback` now to see if there is a straightforward fix.

**Comment by willibrandon** [comment]
We might have to compromise slightly with the `RichTextBox`, and if the application sets the `Effect` to `DragDropEffects.None`, prevent the `RichTextBox` from displaying the drag image and drop description, even if the application also specifies a `DropImageType `of `DropImageType.None`.

For some reason the `RichTextBox` behaves differently in the cross-process scenario and the drag image manager doesn't automatically synthesize a call to `DragLeave` like it does in the in-process scenario.

**Comment by willibrandon** [comment]
I see another problem here.

@Nora-Zhou01 - If you do what you did before and drag the _DragAcceptFiles_ item and drop it onto the `RichTextBox`, cross-process, over and over and over. Does it crash your application?

Doing so crashes the application on my machine, and I've attached the associated mini dump.
[WinformsControlsTest.exe.78824.dmp](https://github.com/dotnet/winforms/files/13644987/WinformsControlsTest.exe.78824.dmp)

I'm learning how to use WinDbg right now to see if I extract more information.

**Comment by willibrandon** [comment]
Here is a video of the crash for reference.

https://github.com/dotnet/winforms/assets/5017479/8e289485-7af7-4268-8290-3d84cdebf86a

**Comment by Nora-Zhou01** [comment]
> Here is a video of the crash for reference.
> 
>  RichTextBoxDragDropCrash.mp4

I reproduced the problem you mentioned, but it seems that it is not limited to dragging and dropping DragAcceptFiles items onto the RichTextBox. Dragging multiple times will cause the application to crash. Below are my results.

https://github.com/dotnet/winforms/assets/104609169/b4521cb5-e665-4f45-9f64-1be3edc2377a

**Comment by elachlan** [comment]
Stack overflow in the drag drop interop code somewhere? Is it only when doing cross process?

**Comment by weltkante** [comment]
> Security check failure or stack buffer overrun
> The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.

thats no stack overflow, its bad interop writing into memory it shouldn't be writing into

**Comment by weltkante** [comment]
I don't see any change in interop declarations in the PR, so this might be triggering a bug thats existing independently from the PR. Memory corruptions are hard to detect, you might find them randomly by doing a totally unrelated operations.

**Comment by elachlan** [comment]
@merriemcgaw this needs to be reopened and looked at.

**Comment by weltkante** [comment]
I don't think this PR broke anything (i.e. doesn't need to be reopened), from what I can tell the RichTextBox interop is broken @JeremyKuhne do you know where the refactoring of RichTextBox.OleCallback happened? the file has no history to me since it was moved during some folder restructuring.

Looks to me like the new com interop is doing manual reference counting and its doing it wrong, leading to use-after-free memory corruption when you do drag'n'drop interop with a winforms RichTextBox.

For example [this line](https://github.com/dotnet/winforms/blob/7582758b1856c86bbaee36296f8cc76058040704/src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.OleCallback.cs#L142) in `IRichEditOleCallback.QueryAcceptData` does a `DataObject.FromComPointer` which [takes ownership](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs#L69) (aka releases) a COM object passed as argument. As far as I'm aware COM objects passed as arguments are not owned by the called function, right? So this is releasing a COM reference its not owning?

If I misinterpreted the source, I am able to repro the crashes and doing TTD dumps with full history so I can inspect further to find the root cause if I'm guessing wrong. Might want to continue the conversation somewhere else though, like I said, don't think this issue/PR is causing problems.

**Comment by weltkante** [comment]
Actualls this memory corruption/crash is in the .NET 8 release and repros without doing anything special, just dragging images and text from the browser into a RichTextBox, so I'm opening a new issue for it #10470

**Comment by willibrandon** [comment]
@weltkante - Thank you, I appreciate you taking time to look into this.

**Comment by willibrandon** [comment]
I've tested the fix in #10475 and I believe it alleviates the remaining issue found by @Nora-Zhou01 here.

**Comment by Nora-Zhou01** [comment]
@willibrandon I tested PR 10475, which had fixed the crash issue placed on RichTextBox, but the issue with image artifacts in cross-process scenarios still persisted.

**Comment by willibrandon** [comment]
> The stack trace is likely not relevant. If it is relevant then its caused by bad reference counting, but I doubt you do manual reference counting? Its more likely that its just now detecting a memory corruption caused earlier.

@weltkante - The only time I've had to look at reference counting so far is in DragDropFormat.cs. It isn't a topic I know well which is why I know I have been very fortunate to have your help with this project. I'm trying to bring myself up to speed on the topic right now by working through the samples in the inside com book.

**Comment by MandiMan** [comment]
Verified on the main branch of the Winforms repo that this issue has been fixed, RichTextBox Drag image and dropdown description is hidden.

https://github.com/dotnet/winforms/assets/108860782/9c64aa83-a616-46f2-97b6-45997c542116
