### ISSUE TITLE
System.Drawing.Design.FontNameEditor and System.ComponentModel.Design.MultilineStringEditor are missing

### ISSUE THREAD

**Issue by cadilhac** [dotnet/winforms#892]
I can't see System.Drawing.Design.FontNameEditor and System.ComponentModel.Design.MultilineStringEditor.

**Comment by JuditRose** [comment]
I checked these:
- System.Drawing.Design.FontNameEditor: it is not ported either in winforms, nor in corefx, based on the namespace I'd assume it belongs to corefx, I am not sure if it was not ported intentionally or unintentionally.
- System.ComponentModel.Design.MultilineStringEditor: it's not ported to winforms dotnet core yet, but we can relatively easily take it from dotnet framework, dependency-wise: a few native methods and resources are missing, but nothing seriously big as far as I can tell.

**Comment by 87Alex** [comment]
Hello,
We also use the System.ComponentModel.Design.MultilineStringEditor class in our designers.
[Editor("System.ComponentModel.Design.MultilineStringEditor, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", typeof(System.Drawing.Design.UITypeEditor))]
string ToolTip { get; set; }
Do you plan to port it in dotnet core?

**Comment by JuditRose** [comment]
Hi,
Multiline string editor is in a PR now. @87Alex Feel free to take a look at it.
@merriemcgaw or @OliaG do any of you know who can I talk to in the coreFX team to figure out what is the plan with the font name editor?

**Comment by merriemcgaw** [comment]
@JuditRose I'd start with @ericstj to see if he's thought about this.

**Comment by ericstj** [comment]
@merriemcgaw these are all in System.Design on desktop which isn't something we'd bring back in CoreFx.  I believe in our past discussions the plan was that a lot of this stuff only lives in VS and for the things that need to be part of winforms they'd be added to assemblies in the WinForms repo, EG: https://github.com/dotnet/winforms/tree/master/src/System.Windows.Forms.Design or https://github.com/dotnet/winforms/tree/master/src/System.Drawing.Design.  This type must live in winforms or higher because that's where the UITypeEditor [lives](https://github.com/dotnet/winforms/blob/82634b7a59c5d1253fc3ee2107092868546c6f79/src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs).

**Comment by zsd4yr** [comment]
* [ ] Font Name Editor
* [ ] Multiline String Editor

**Comment by zsd4yr** [comment]
@JuditRose we will need to port Font Name Editor. Perhaps this is something @RussKie can take on since it is due by Preview 8

**Comment by ericstj** [comment]
You may want to review all types that derive from UITypeEditor to determine if any others are missing.  https://docs.microsoft.com/en-us/dotnet/api/system.drawing.design.uitypeeditor?view=netframework-4.8

**Comment by RussKie** [comment]
Both missing editors have been ported:
* https://github.com/dotnet/winforms/blob/8ab5acfadacb7962dfba401b7f1422fe4cd22712/src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/FontNameEditor.cs
* https://github.com/dotnet/winforms/blob/f38a7a167d8f83924d43f8d2d8f2b03034351eb7/src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/MultilineStringEditor.cs

We'll review the list from https://github.com/dotnet/winforms/issues/892#issuecomment-495455585 separately.
