### ISSUE TITLE
The error message for add a toolstrip button through IList has changed

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#9114]
### .NET version

.NET 8.0.100-preview.5.23261.16

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .NET 6.0/7.0/8.0(without latest winforms dlls)

### Minimal Reproduction Scenario: 
1. Create a WinForms .NET Core project.
2. Add 
```
ToolStrip wb = new ToolStrip();
Button btn = new Button();
((IList)wb.Items).Add(btn);
```
   in Form1.cs.
3. Build and run the project.

Or
1. Extract and open [testilist.zip](https://github.com/dotnet/winforms/files/11463404/testilist.zip)
2. Build and run the project.

### Current Behavior:
Show error message: System.InvalidCastException: 'Unable to cast object of type 'System.Windows.Forms.Button' to type 'System.Windows.Forms.ToolStripItem'.'

![image](https://github.com/dotnet/winforms/assets/86937911/e0f466af-5a7b-4edb-a202-8a41f2b0cc94)

### Expected Behavior:
Show error message: System.ArgumentNullException: Message=Value cannot be null. Parameter name: value
![image](https://github.com/dotnet/winforms/assets/86937911/518ef38b-e008-44b4-a01d-80e41236f699)

### More Info:
This issue may be caused by https://github.com/dotnet/winforms/pull/9072

**Comment by dreddy-work** [comment]
Well, the current exception suits better in this context. There are no `null `items present in this scenario. Should we consider this a breaking change? I am not certain on that. 

@JeremyKuhne / @Tanya-Solyanik for comments.

**Comment by JeremyKuhne** [comment]
This is by design and in this particular case I don't think a breaking change doc is worth it.

The question of whether to document or not is mostly a case of expected user impact. This is extremely unlikely to cause issues for current users when they move to .NET 8, and it isn't likely to be confusing if they hit it.

Even if we had unlimited bandwidth documenting this sort of thing is likely to make finding and understanding impactful breaking changes difficult. And, importantly, we can always add clarifying details if user feedback shows our original assessment wasn't correct.
