### ISSUE TITLE
Add `BeforeMaximize` and `AfterMaximize` events to Form

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#9124]
### Background and motivation

We manually implemented Before/After Maximize events to pause the layout calculations on the certain control heavy forms until it has been fully resized.

This reduced the time the operation took from 2.2sec to 0.37 seconds.

### API Proposal

```csharp
namespace System.Windows.Forms

public partial class Form : ContainerControl
{
    public event EventHandler? BeforeMaximize
    public event EventHandler? AfterMaximize

    private void WmSysCommand(ref Message m)
    {
        ...
        case User32.SC.MAXIMIZE
            OnBeforeMaximize();
            base.WndProc(ref m);
            OnAfterMaximize();
    }
}
```

### API Usage

```csharp
 private void MyForm_BeforeMaximize(object sender, EventArgs e)
    {
        this.SuspendLayout();
    }
    private void MyForm_AfterMaximize(object sender, EventArgs e)
    {
        this.ResumeLayout();
    }
```

### Alternative Designs

Team might know a better way.

### Risks

Unknown

### Will this feature affect UI controls?

N/A

**Comment by merriemcgaw** [comment]
Thanks for the suggestion! Because there is a simple workaround (thanks for putting it in the suggestion, by the way!), we're a little hesitant to add new events to the Form. If we get a lot of feedback from folks in the community we will certainly take another look at it. We'll close this for now, but we'll re-triage if we get demand from the community.

**Comment by elachlan** [comment]
> we're a little hesitant to add new events to the Form.
Could you explain the reasoning behind this? Is it performance related?
