### ISSUE TITLE
[Accessibility] HC themes: The color contrast of indeterminate state icon for toolStripMenuItem is less than 3:1

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9166]
### .NET version

.Net 8.0 SDK build: 8.0.100-preview.5.23268.13

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

The color contrast of indeterminate state icon for toolStripMenuItem in some non-focused and mouse over situations is less than 3:1 on Windows 11 high contrast themes and Windows 10 themes

**Windows 11 non-focused:**
![image](https://github.com/dotnet/winforms/assets/26474449/02e7e3a4-2660-467f-a852-eb21b4b76467)

**Windows 11 mouse over:** 
![image](https://github.com/dotnet/winforms/assets/26474449/c36bdd49-287d-4f07-add9-4f62dab91c0f)

### Steps to reproduce

Use following test sample application:
[WinFormsApp24.zip](https://github.com/dotnet/winforms/files/11551183/WinFormsApp24.zip)

**Comment by v-elnovikova** [comment]
There was a similar issue with checked menu item: #7725, fixed by replacing [Checked.ico](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/Resources/System/Windows/Forms/Checked.ico) with more contrasting icon. For this issue a new version of [IndeterminateChecked.ico](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/Resources/System/Windows/Forms/IndeterminateChecked.ico) is probably needed. 

Another option is to use ColorMap or ColorMatrix to modify current icon in [ToolStripHighContrastRenderer](https://github.com/dotnet/winforms/blob/274e7a0f0f2dd6d51a8153594408f4aa99e57d5f/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs#L106) class. [ToolStripRenderer.CreateDisabledImage](https://github.com/dotnet/winforms/blob/274e7a0f0f2dd6d51a8153594408f4aa99e57d5f/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripRenderer.cs#L1035) contains an example of applying ColorMatrix to create a grayscale image.

**Comment by MandiMan** [comment]
Verified this issue in feature/9.0 branch, now the color contrast of indeterminate state icon for toolStripMenuItem in non-focused and mouse over situations can be showed clearly.
Windows 11 non-focused:
![image](https://github.com/dotnet/winforms/assets/108860782/86f64a95-2bd4-4a34-bcb6-3b21e0425eac)
Windows 11 mouse over:
![image](https://github.com/dotnet/winforms/assets/108860782/abea9b47-cfb7-4e2b-b7f8-ef57660a3de7)
