### ISSUE TITLE
Designer modifies resx file needlessly

### ISSUE THREAD

**Issue by mocakturk** [dotnet/winforms#9211]
### Environment

Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.6.2

### .NET version

.NET 7

### Did this work in a previous version of Visual Studio and/or previous .NET release?

I was using .NET framework and Visual Studio 2017. There was no such problem.

### Issue description

I migrated my WinForms project from .NET framework 4_8. I was using VS2017.
I'm using VS2022 with NET7 now.
When I do a minor modification on the Form using the designer, VS2022 modifies the cs file and resx file as well.
* The modification in cs file is **indentation**.
* The modification in resx file is including a **"** character to a comment part.
![image](https://github.com/dotnet/winforms/assets/106665359/466539ed-0131-4c73-87d4-03b60abb8b62)

I need to **undo** the changes in **cs** and **resx**.

### Steps to reproduce

Just move a control some pixels in designer.

**Comment by elachlan** [comment]
@Olina-Zhang Has your team ran into this in testing?

**Comment by John-Qiao** [comment]
## Minimal Reproduction Scenario

1. Create a .NET Core Winforms core application.
2. Open project location folder, then open the Form1.resx file in [Notepad++](https://notepad-plus-plus.org/downloads/v8.4.9/), check the comment out content in it. --don't close the Notepad++
3. Switch to VS, resize the form1 designer and save the project.
4. Switch to Notepad++, click Yes button, check the comment out content in Form1.resx file again.
![9211-reprosteps](https://github.com/dotnet/winforms/assets/45864985/93dc0554-915a-42b4-b55a-d8a19abd0490)

## Current Behavior

There's an extra " in comment out content.
![Actual](https://github.com/dotnet/winforms/assets/45864985/a54cd7cf-e8fa-440b-b716-8493d5baea32)

## Expected Behavior

There's no extra " in comment out content.
![Expected](https://github.com/dotnet/winforms/assets/45864985/ae269dbf-d02f-471d-b1e0-0a14f4355faa)

## Test Environment

17.7.0 Preview 2.0 [33801.574.main]

## Have you experienced this same issue with .NET Framework designer?

No

## Have you experienced this same issue with previous previews of VisualStudio?

Yes, this issue caused by this PR: [4930](https://github.com/microsoft/winforms-designer/pull/4930)

**Comment by John-Qiao** [comment]
Verified on VS latest build: 17.7.0 Preview 3.0 [33812.346.main] from main branch, issue was fixed, there's no extra " in comment out content now.
![9211-testresult](https://github.com/dotnet/winforms/assets/45864985/2081058b-13bc-42a8-a461-4c32c78ed104)
