### ISSUE TITLE
Infinite designer loading since migration from .net 4.8 to .NET7

### ISSUE THREAD

**Issue by alexdess** [dotnet/winforms#9317]
### Environment

Microsoft Visual Studio Professional 2022
Version 17.6.3
VisualStudio.17.Release/17.6.3+33801.468

### .NET version

net7.0-windows

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes, .NET48.

### Issue description

I've had this window and warning since my migration to .NET7.
![image](https://github.com/dotnet/winforms/assets/8177780/599c0e36-3bdf-4f6b-8bc4-3b173974327a)

The project builds and runs, the windows also work at runtime. The VBproj concerned:

```
  <PropertyGroup>
	  <TargetFramework>net7.0-windows</TargetFramework>
    <AssemblyVersion>2023.5.31.1448</AssemblyVersion>
    <FileVersion>2023.5.31.1448</FileVersion>
    <Version>2023.5.31.1448</Version>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
	<MyType>WindowsForms</MyType>
  </PropertyGroup>
```

I've already spent more than 2 days trying to correct my problem and in particular tried all the steps in the guide https://github.com/dotnet/winforms/blob/main/docs/designer/troubleshooting.md

### Steps to reproduce

- Rebuild
- Open a simple Designer

### Diagnostics

```text
warn: Cannot update selection in server process as Session is not connected.
```

**Comment by merriemcgaw** [comment]
@alexdess Are you reproducing this with a blank project? What does the solution contain? Are there custom controls or 3rd party components?

There may be something there that is incompatible with the new out of process designer for WinForms .NET. In order to diagnose the problems we would need to have your solution and/or the verbose logs from opening your solution. If you aren't comfortable sharing them on GitHub you could use the VS Feedback tool which gives us a way to communicate privately and share files securely.
