### ISSUE TITLE
InputBox is hidden by TopMost forms in VB.Net

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#9351]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/InputBox-is-hidden-by-TopMost-forms-in-V/10394412)._

---
[severity:It's more difficult to complete my work]
An InputBox is hidden beneath forms with their TopMost property set to true.  Since the InputBox is modal, it becomes impossible to continue and the program must be terminated.  An InputBox should appear on top of even a TopMost form to be usable in all cases.  I ran into this a few times in the past and I'm surprised this still hasn't been addressed.  I'm using VisualStudio 2019 and VB.net.

I can work around this by temporarily setting the TopMost property of my form(s) to false, but in my opinion, the InputBox should not require this so that it can be used.

---
#### Feedback Bot on 6/19/2023, 08:29 AM: 

(private comment, text removed)
#### Mandi Man [MSFT] on 6/20/2023, 10:58 AM: 

(private comment, text removed)
#### Randy Hill on 6/21/2023, 03:44 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by elachlan** [comment]
@dreddy-work do you want the inputform when it's shown to set it parent to topmost=false and then reset it afterwards? It do you want a more complex solution for forms that open topmost when their parent is also topmost? Maybe track the topmost count of parents?

**Comment by RandyInNashua** [comment]
This is a bug report, not a wish request.  The InputBox is not really a form, it's a utility used to get input from the user.  In my opinion when an InputBox is called by a form, the user should be able to input the requested information.  Right now that function is impeded by a form with its TopMost setting set to true.  In my opinion, that is a bug.  I realize how easy it is to work around this and that is what I've been doing for the last few years and what I will continue to do if nobody else agrees with me that this is a bug that should be fixed.  The InputBox should work the same for all forms, regardless of the TopMost setting and should not require a "work around".

**Comment by elachlan** [comment]
So my comment is to try to arrive at a design solution so I can submit a PR. I understand your use case. But this brings up another point of a form showing another form with both having topmost set.

InputForm is a form. So the solution can either be just for it or solve it for all forms.

**Comment by RandyInNashua** [comment]
two forms both with TopMost set to true, works fine.  The form with focus is on top.

**Comment by KlausLoeffelmann** [comment]
We earlier discussed to obsolete `InputBox`, since it is the old Visual Basic 6 programming paradigm. We decided not to do that, but at the same time we a) discourage people from using it since it was a pure backwards compatibility API to VB6 to begin with, and b) we definitely won't change its current behavior, all the more, since it's the same in Framework.

I am not considering this to be a bug; this is in the nature of Windows: If you have a Top-Level-Window and a model Dialog created by the Windows Win32 API, that's exactly the behavior that you get. If you don't want that, you would indeed need to temporarily undo the Top-Most property for the Window in the way.

Closing this as won't fix.
