### ISSUE TITLE
The next focus position is not correct when setting GripStyle = hidden and selecting on a ToolStripButton using mouse or typing "enter" keyboard and then typing "right or left" keyboard. 

### ISSUE THREAD

**Issue by SimonZhao888** [dotnet/winforms#9438]
### .NET version

.NET SDK 8.0.100-preview.5.23274.2

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

For .NET core 3.1 and .NET 5.0, the behavior is same as .NET framework, setting GripStyle = hidden:
When typing Right keyboard, the next focus position is first item on the left.
When typing Left keyboard, the next focus position is first item on the Right.

For .NET 6.0/7.0/8.0, the behavior is: the next focus position is first item on the left, regardless of whether the right or left key is typed.

### Issue description

When selecting on a ToolStripButton using mouse or typing "enter" keyboard and then typing "right or left" keyboard, the next focus position is first item on the left, regardless of whether the right or left key is typed.
![ToolStrip](https://github.com/dotnet/winforms/assets/133954995/6229313a-8f41-45c3-8d4f-2e1d72444e71)

### Steps to reproduce

1. Extract and open the test app. [TestApp.zip](https://github.com/dotnet/winforms/files/11973778/TestApp.zip)
2. Build and run this project.
3. Select on a ToolStripButton using mouse or typing "enter" keyboard.
4. Type "right or left" keyboard.

**Comment by MelonWang1** [comment]
Verified with .NET SDK 8.0.100-preview.7.23376.3 test pass build, this issue was fixed, set GripStyle = hidden, when typing Right keyboard, the next focus position is first item on the left, and if typing Left keyboard, the next focus position is first item on the Right.Test result video as below:

https://github.com/dotnet/winforms/assets/94418985/e3ac0e80-2e89-4cb3-96db-681f8ebd982d
