### ISSUE TITLE
[HDPI]GDI+ HatchBrushes are virtually useless on high-dpi displays

### ISSUE THREAD

**Issue by Ashley-Li** [dotnet/winforms#9848]
### .NET version

dotnet-sdk-8.0.100-rc.1.23423.3

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it reproes in .Net 7.0 SDK/.NET 6.0 SDK build.

### Issue description

On High DPI environment, the patterns are rendered much too small to be useful on high-dpi displays and  the pattern of the graphic is inconsistent with the .NET Framework.

**Result on .Net 8.0 rc1 build with 300%DPI:**
![Core_300DPI](https://github.com/dotnet/winforms/assets/56664234/aae605b6-dcb1-4997-8575-81ea51b9f214)

Result on .NET Framework 4.8.1 with 300%DPI:
![Framework_300DPI](https://github.com/dotnet/winforms/assets/56664234/420a8cca-e3ee-461d-bd61-69223c84b758)

### Steps to reproduce

Sample app:
[WinFormsApp131.zip](https://github.com/dotnet/winforms/files/12534942/WinFormsApp131.zip)

Codes：
 ```C# Form f = new Form();
        HatchBrush h = new HatchBrush(HatchStyle.Sphere, Color.Navy, Color.NavajoWhite);
        Bitmap b = new Bitmap(f.ClientRectangle.Width, f.ClientRectangle.Height);
        using (Graphics g = Graphics.FromImage(b))
        {
            g.FillRectangle(h, new Rectangle(Point.Empty, f.ClientSize));
        }
        f.BackgroundImage = b;
        f.WindowState = FormWindowState.Maximized;
        f.Show();
  ```

The initial ticket link is here: https://devdiv.visualstudio.com/DevDiv/_queries/edit/1879680

**Comment by JeremyKuhne** [comment]
The rendering difference is a matter of DPI awareness settings. This is all GDI+ code and it's by design that these render raw pixels, so there isn't much we can do.

That said, here is one approach you could use to get a scalable brush: https://stackoverflow.com/a/33938352

You could take the current `DeviceDpi / 96f` as a scale to apply to the created brush in the example. You'd have to listen to DpiChanged to handle being moved around.

**Comment by JeremyKuhne** [comment]
This is by design.
